Repository kubesphere/kubekey, pull requests merged in 2020-08, with the labels that each got.

#182 update flannel to v0.12.0
  pkg/apis/kubekey/v1alpha1/default.go
  pkg/plugins/network/flannel/tmpl.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#184 update calico to v3.15.1
  pkg/apis/kubekey/v1alpha1/default.go
  pkg/cluster/preinstall/prepull_images.go
  pkg/plugins/network/calico/tmpl-v1.16+.go
  pkg/plugins/network/calico/tmpl-v1.16-.go
  pkg/plugins/network/network.go
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#185 add telemetry
  docs/config-example.md
  pkg/kubesphere/manifests.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#186 fix character
  pkg/kubesphere/manifests.go
Labels: approved, dco-signoff: yes

#187 update result path
  pkg/kubesphere/kubesphere.go
Labels: approved, dco-signoff: yes, size/XS

#189 deploy KubeSphere on the existing K8s
  cmd/deploy.go
  cmd/kubesphere.go
  cmd/root.go
  go.mod
  go.sum
  pkg/deploy/client.go
  pkg/deploy/kubesphere.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#192 remove useless parameters
  pkg/cluster/etcd/etcd.go
  pkg/cluster/kubernetes/master.go
  pkg/cluster/kubernetes/nodes.go
  pkg/cluster/kubernetes/upgrade.go
  pkg/cluster/preinstall/init_os.go
  pkg/cluster/preinstall/precheck.go
  pkg/cluster/preinstall/prepull_images.go
  pkg/container-engine/docker/docker.go
  pkg/delete/delete.go
  pkg/kubesphere/kubesphere.go
  pkg/plugins/network/network.go
  pkg/plugins/storage/images.go
  pkg/plugins/storage/storage.go
  pkg/upgrade/policy.go
  pkg/util/manager/task_run.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#195 add SUSE Linux to the supported OS list
  README.md
  README_zh-CN.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#194 refactor deploy ks
  pkg/apis/kubekey/v1alpha1/cluster_types.go
  pkg/apis/kubekey/v1alpha1/default.go
  pkg/cluster/preinstall/preinstall.go
  pkg/config/generate.go
  pkg/config/parse.go
  pkg/kubesphere/kubesphere.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#196 update telemetry
  docs/config-example.md
  pkg/kubesphere/manifests.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#197 update cc
  pkg/kubesphere/manifests.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#198 refactor deploy ks
  cmd/deployKs.go
  cmd/manager/main.go
  cmd/upgradeKs.go
  pkg/apis/kubekey/v1alpha1/cluster_types.go
  pkg/apis/kubekey/v1alpha1/register.go
  pkg/config/from_cluster.go
  pkg/config/generate.go
  pkg/config/parse.go
  pkg/deploy/kubesphere.go
  pkg/kubesphere/kubesphere.go
  pkg/kubesphere/v2/types.go
  pkg/kubesphere/v3/types.go
  pkg/upgrade/config.go
  pkg/upgrade/kubernetes.go
  pkg/upgrade/kubesphere.go
  pkg/upgrade/policy.go
  pkg/upgrade/precheck.go
  pkg/upgrade/upgrade.go
  pkg/util/client.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#199 add version info
  Makefile
  build.sh
  cmd/upgrade_ks.go
  cmd/version.go
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#202 update delete cluster
  cmd/delete.go
  cmd/delete_cluster.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#205 refine deploy kubernetes
  pkg/cluster/kubernetes/master.go
  pkg/cluster/kubernetes/nodes.go
  pkg/delete/delete.go
  pkg/plugins/dns/dns.go
  pkg/plugins/dns/nodelocaldns.go
  pkg/plugins/network/network.go
  pkg/upgrade/kubernetes.go
  pkg/upgrade/kubesphere.go
  pkg/upgrade/upgrade.go
  pkg/util/runner/runner.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#211 server side apply
  go.mod
  go.sum
  pkg/deploy/create_objects.go
  pkg/deploy/kubesphere.go
  pkg/upgrade/kubesphere.go
  pkg/util/client.go
  pkg/util/manager/task_run.go
Labels: approved, dco-signoff: yes, size/L

#209 Add a little note（SELinux） to the readme
  README.md
  README_zh-CN.md
  docs/turn-off-SELinux.md
  docs/turn-off-SELinux_zh-CN.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#212 use the correct apostrophe
  docs/turn-off-SELinux.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#224 add node delete
  README.md
  README_zh-CN.md
  cmd/delete_node.go
  pkg/delete/delete.go
Labels: approved, dco-signoff: no, lgtm, size/L

#233 update delete node
  pkg/delete/delete.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#235 refine upgrade
  pkg/cluster/kubernetes/master.go
  pkg/cluster/kubernetes/nodes.go
  pkg/cluster/preinstall/init_os.go
  pkg/install/install.go
  pkg/scale/scale.go
  pkg/upgrade/kubernetes.go
  pkg/upgrade/precheck.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#236 Make sure the iptables utility doesn't use the nftables backend.
  pkg/cluster/preinstall/tmpl/init_os.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#240 update docker judgement conditions
  pkg/container-engine/docker/docker.go
  scripts/docker-install.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#241 get kubeconfig automatically
  pkg/upgrade/precheck.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#242 add k8s-v1.16.0
  pkg/files/file.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#255 update add nodes
  README.md
  README_zh-CN.md
  cmd/add.go
  cmd/add_nodes.go
  cmd/version.go
  pkg/add/add.go
  pkg/upgrade/upgrade.go
Labels: approved, dco-signoff: no, lgtm, size/M

#256 support for custom addons
  README.md
  README_zh-CN.md
  cmd/config.go
  docs/addons.md
  docs/config-example.md
  docs/glusterfs.yaml
  go.mod
  go.sum
  pkg/addons/charts/install.go
  pkg/addons/install.go
  pkg/addons/manifests/install.go
  pkg/apis/kubekey/v1alpha1/addons_types.go
  pkg/apis/kubekey/v1alpha1/cluster_types.go
  pkg/apis/kubekey/v1alpha1/default.go
  pkg/apis/kubekey/v1alpha1/zz_generated.deepcopy.go
  pkg/cluster/kubernetes/master.go
  pkg/cluster/preinstall/prepull_images.go
  pkg/config/generate.go
  pkg/config/parse.go
  pkg/deploy/create_objects.go
  pkg/deploy/kubesphere.go
  pkg/install/install.go
  pkg/kubesphere/kubesphere.go
  pkg/plugins/storage/ceph-rbd/ceph_rbd.go
  pkg/plugins/storage/glusterfs/glusterfs.go
  pkg/plugins/storage/local-volume/openebs.go
  pkg/plugins/storage/nfs-client/nfs_client.go
  pkg/plugins/storage/storage.go
  pkg/upgrade/kubernetes.go
  pkg/upgrade/kubesphere.go
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#257 refine cmds
  cmd/add_nodes.go
  cmd/cluster.go
  cmd/config.go
  cmd/delete.go
  cmd/delete_cluster.go
  cmd/delete_node.go
  cmd/deploy.go
  cmd/deployKs.go
  cmd/upgrade.go
  cmd/upgrade_ks.go
  pkg/config/generate.go
  pkg/upgrade/precheck.go
  pkg/upgrade/upgrade.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#259 add docs about csi-qingcloud
  docs/addons.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#260 refine install steps
  pkg/install/install.go
  pkg/kubesphere/kubesphere.go
  pkg/plugins/storage/storage.go
  pkg/upgrade/kubernetes.go
  pkg/util/manager/run_task.go
  pkg/util/manager/task_control.go
  pkg/util/runner/runner.go
Labels: approved, dco-signoff: no, size/L

#261 update format
  docs/addons.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#262 support for k8s v1.19.0
  pkg/cluster/kubernetes/tmpl/kubeadm.go
  pkg/cluster/preinstall/prepull_images.go
  pkg/files/file.go
  pkg/upgrade/kubernetes.go
  pkg/upgrade/precheck.go
  pkg/util/util.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#263 refresh kubelet config
  pkg/upgrade/kubernetes.go
Labels: approved, dco-signoff: yes, size/XS

#266 refine install step
  pkg/addons/install.go
  pkg/addons/manifests/install.go
  pkg/cluster/kubernetes/master.go
  pkg/deploy/kubesphere.go
  pkg/kubesphere/kubesphere.go
  pkg/plugins/dns/dns.go
  pkg/upgrade/kubernetes.go
  pkg/upgrade/kubesphere.go
Labels: approved, dco-signoff: yes, size/L

#267 use cluster kubeconfig
  pkg/addons/install.go
Labels: approved, dco-signoff: yes, size/XS

#265 support kubernetes versions
  README.md
  README_zh-CN.md
  docs/kubernetes-versions.md
Labels: approved, dco-signoff: no, lgtm, size/M

#268 rbd addon examples
  docs/addons.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#270 update docs
  README.md
  README_zh-CN.md
  docs/kubectl-autocompletion.md
  pkg/cluster/kubernetes/master.go
  pkg/cluster/preinstall/precheck.go
  pkg/kubesphere/kubesphere.go
  pkg/upgrade/precheck.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#271 scene:
  pkg/upgrade/precheck.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#272 Create release.yml
  .github/workflows/release.yml
Labels: approved, dco-signoff: no, size/M

#276 Adjust legacy notification description
  docs/config-example.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#275 Adjust legacy notification description
  docs/config-example.md
Labels: approved, dco-signoff: yes, lgtm, size/XS
