Repository kubesphere/kubekey, pull requests merged in 2020-12, with the labels that each got.

#388 add download script
  pkg/cluster/preinstall/precheck.go
  scripts/docker-install.sh
  scripts/downloadKubekey.sh
Labels: approved, dco-signoff: yes, size/M

#389 multi container runtime
  apis/kubekey/v1alpha1/default.go
  pkg/cluster/kubernetes/master.go
  pkg/cluster/kubernetes/tmpl/kubeadm.go
  pkg/cluster/kubernetes/tmpl/kubelet.go
  pkg/cluster/preinstall/prepull_images.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#390 Use kubekey as the offical binary name instead of kk
  .github/workflows/release.yaml
  .goreleaser.yml
Labels: approved, dco-signoff: yes, lgtm, size/S

#392 update etcd certs file
  pkg/cluster/kubernetes/tmpl/kubeadm.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#396 Add contributors name
  CONTRIBUTORS.md
Labels: approved, dco-signoff: yes, size/S

#395 Update nodes.go
  pkg/cluster/kubernetes/nodes.go
Labels: dco-signoff: no, size/XS

#399 Typo fixing with the word failed
  pkg/add/add.go
  pkg/bootstrap/init.go
  pkg/config/from_cluster.go
  pkg/config/generate.go
  pkg/install/install.go
  pkg/upgrade/upgrade.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#402 support aliyun images repo
  pkg/cluster/etcd/tmpl/certs.go
  pkg/cluster/etcd/tmpl/etcd.go
  pkg/cluster/etcd/tmpl/etcdbackup.go
  pkg/cluster/kubernetes/tmpl/kubeadm.go
  pkg/cluster/kubernetes/tmpl/kubelet.go
  pkg/cluster/preinstall/prepull_images.go
  pkg/config/from_cluster.go
  pkg/config/generate.go
  pkg/config/parse.go
  pkg/deploy/kubesphere.go
  pkg/images/images.go
  pkg/kubesphere/kubesphere.go
  pkg/kubesphere/manifests.go
  pkg/plugins/storage/local-volume/openebs.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#407 Add nightly build support
  cmd/cluster.go
  cmd/kk/main.go
  cmd/version.go
  pkg/config/parse.go
  pkg/deploy/kubesphere.go
  version/k8s.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#408 update contributors
  CONTRIBUTORS.md
  README.md
  README_zh-CN.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#409 support none network plugin installation
  pkg/install/install.go
  pkg/plugins/network/network.go
  pkg/util/manager/manager.go
  pkg/util/manager/run_task.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#411 Fix the nightly installation errors
  pkg/kubesphere/kubesphere.go
  pkg/kubesphere/manifests.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#412 update calico manifests
  pkg/plugins/network/calico/tmpl-v1.16+.go
  pkg/plugins/network/calico/tmpl-v1.16-.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#413 fix kubeadm template
  pkg/cluster/kubernetes/tmpl/kubeadm.go
Labels: approved, dco-signoff: yes, size/XS

#414 Add renew certificate readme
  README.md
  README_zh-CN.md
  docs/check-renew-certificate.md
Labels: approved, dco-signoff: yes, lgtm, size/M
