Repository kubesphere/kubekey, pull requests merged in 2020-06, with the labels that each got.

#56 Update logging timestamp, refine logging msg, add short config param
  cmd/create/cluster.go
  pkg/cluster/preinstall/precheck.go
  pkg/delete/delete.go
  pkg/install/install.go
  pkg/scale/scale.go
Labels: approved, lgtm, size/S

#57 support custom calico and flannel
  pkg/cluster/preinstall/preinstall.go
  pkg/plugins/network/network.go
Labels: approved, lgtm, size/M

#60 check storage client
  pkg/cluster/preinstall/precheck.go
Labels: approved, lgtm, size/XS

#62 add waiting prompt
  go.mod
  go.sum
  pkg/cluster/etcd/etcd.go
  pkg/cluster/kubernetes/master.go
  pkg/cluster/kubernetes/nodes.go
  pkg/cluster/preinstall/initOS.go
  pkg/delete/delete.go
  pkg/kubesphere/kubesphere.go
  pkg/plugins/dns/dns.go
  pkg/plugins/network/network.go
  pkg/plugins/storage/storage.go
  pkg/util/runner/runner.go
Labels: approved, lgtm, size/XXL

#67 refactor cmds
  cmd/cluster.go
  cmd/cmd.go
  cmd/config.go
  cmd/create.go
  cmd/create/cluster.go
  cmd/create/config.go
  cmd/create/etcd.go
  cmd/delete.go
  cmd/manager/main.go
  cmd/root.go
  cmd/scale.go
  cmd/version.go
  go.sum
  kubekey.go
  pkg/apis/kubekey/v1alpha1/cluster_types.go
  pkg/apis/kubekey/v1alpha1/default.go
  pkg/apis/kubekey/v1alpha1/kubesphere_types.go
  pkg/apis/kubekey/v1alpha1/zz_generated.deepcopy.go
  pkg/cluster/kubernetes/tmpl/kubeadm.go
  pkg/cluster/preinstall/preinstall.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/delete/delete.go
  pkg/install/install.go
  pkg/kubesphere/kubesphere.go
  pkg/kubesphere/manifests.go
  pkg/plugins/network/calico/tmpl.go
  pkg/plugins/network/flannel/tmpl.go
  pkg/plugins/network/network.go
Labels: approved, lgtm, size/XXL

#68 update README.md
  README.md
Labels: approved, lgtm, size/M

#69 Update readme
  README.md
Labels: approved, lgtm, size/L

#71 update kubesphere manifests
  pkg/kubesphere/manifests.go
Labels: approved, lgtm, size/S

#72 Refactor images management
  pkg/apis/kubekey/v1alpha1/default.go
  pkg/cluster/etcd/etcd.go
  pkg/cluster/etcd/tmpl/etcd.go
  pkg/cluster/preinstall/init_os.go
  pkg/cluster/preinstall/prepull_images.go
  pkg/cluster/preinstall/tmpl/init_os.go
  pkg/images/default.go
  pkg/images/images.go
  pkg/install/install.go
  pkg/plugins/dns/nodelocaldns.go
  pkg/plugins/network/calico/tmpl.go
  pkg/plugins/network/flannel/tmpl.go
  pkg/plugins/storage/ceph-rbd/ceph_rbd.go
  pkg/plugins/storage/images.go
  pkg/plugins/storage/local-volume/openebs.go
  pkg/plugins/storage/nfs-client/nfs_client.go
  pkg/plugins/storage/storage.go
  pkg/util/manager/task_control.go
  pkg/util/manager/task_run.go
Labels: approved, size/XL

#73 remove the blank lines
  pkg/config/config.go
  pkg/kubesphere/manifests.go
Labels: approved, size/S

#74 fix: config doesn't take effect
  pkg/config/default.go
Labels: approved, lgtm, size/XS

#75 add wait tiller
  pkg/kubesphere/kubesphere.go
Labels: approved, lgtm, size/XS

#76 kubectl exec [POD] [COMMAND] is DEPRECATED, change to kubectl exec [P…
  pkg/kubesphere/kubesphere.go
Labels: approved, lgtm, size/XS

#77 add kubelet args:--node-ip --hostname-override
  pkg/cluster/kubernetes/nodes.go
  pkg/cluster/kubernetes/tmpl/kubelet.go
Labels: approved, lgtm, size/S

#82 add multicluster and networkPolicy
  pkg/kubesphere/manifests.go
Labels: approved, lgtm, size/S

#85 Refine msg
  pkg/install/install.go
Labels: approved, lgtm, size/XS

#87 multi-arch: arm64
  pkg/apis/kubekey/v1alpha1/cluster_types.go
  pkg/apis/kubekey/v1alpha1/default.go
  pkg/cluster/etcd/etcd.go
  pkg/cluster/etcd/tmpl/etcd.go
  pkg/cluster/kubernetes/nodes.go
  pkg/cluster/preinstall/preinstall.go
  pkg/cluster/preinstall/prepull_images.go
  pkg/config/default.go
  pkg/files/file.go
  pkg/install/install.go
  pkg/kubesphere/kubesphere.go
  pkg/plugins/storage/local-volume/openebs.go
  pkg/util/executor/executor.go
  pkg/util/manager/manager.go
Labels: approved, lgtm, size/L

#90 IfNotPresent to Always
  go.mod
  pkg/kubesphere/manifests.go
Labels: size/XS

#92 update calico to 2.14.1
  pkg/apis/kubekey/v1alpha1/default.go
  pkg/kubesphere/kubesphere.go
  pkg/plugins/network/calico/tmpl.go
  pkg/plugins/network/network.go
  pkg/plugins/storage/images.go
Labels: approved, lgtm, size/L

#95 update commands
  pkg/cluster/kubernetes/master.go
Labels: approved, size/S

#97 update kubesphere manifests
  pkg/config/default.go
  pkg/kubesphere/kubesphere.go
  pkg/kubesphere/manifests.go
Labels: approved, size/L

#99 update config-example.md
  docs/config-example.md
Labels: approved, size/M

#102 update kubesphere manifests
  pkg/kubesphere/manifests.go
Labels: approved, size/XS
