Repository kubesphere/kubekey, pull requests merged in 2020-09, with the labels that each got.

#274 added a higher version upgrade check not included in kk
  pkg/upgrade/precheck.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#277 update README
  README.md
  README_zh-CN.md
Labels: dco-signoff: yes, size/S

#279 update get version
  pkg/upgrade/precheck.go
Labels: approved, dco-signoff: yes

#280 fix get k8s version
  pkg/upgrade/precheck.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#281 fix get k8s version
  pkg/upgrade/kubernetes.go
Labels: dco-signoff: yes, lgtm, size/XS

#285 Dependency requirement update
  README.md
  README_zh-CN.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#283 update docker
  pkg/container-engine/docker/docker.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#289 add ulimit
  pkg/cluster/preinstall/tmpl/init_os.go
Labels: dco-signoff: yes, lgtm, size/XS

#287 update docker install
  scripts/docker-install.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#292 modify bash
  pkg/cluster/preinstall/tmpl/init_os.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#293 Modify print cmd
  pkg/cluster/preinstall/tmpl/init_os.go
  pkg/delete/delete.go
  pkg/util/runner/runner.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#294 add ulimit
  cmd/root.go
Labels: approved, dco-signoff: no, lgtm, size/XS

#295 Add Backup etcd data regularly
  pkg/add/add.go
  pkg/cluster/etcd/etcd.go
  pkg/cluster/etcd/tmpl/etcdbackup.go
  pkg/install/install.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#297 support specify chart version
  pkg/addons/charts/install.go
  pkg/apis/kubekey/v1alpha1/addons_types.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#298 add zombie processing and add sudo
  pkg/cluster/etcd/etcd.go
  pkg/cluster/kubernetes/master.go
  pkg/cluster/preinstall/tmpl/init_os.go
  pkg/delete/delete.go
Labels: approved, dco-signoff: no, lgtm, size/L

#299 fix exec command
  cmd/root.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#303 fix sed-erro about PrivateRegistry
  pkg/kubesphere/kubesphere.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#304 uppercaseNodeName
  README.md
  README_zh-CN.md
  pkg/install/install.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#307 add init operating system
  cmd/init.go
  cmd/init_os.go
  cmd/root.go
  go.mod
  go.sum
  pkg/add/add.go
  pkg/bootstrap/init.go
  pkg/bootstrap/os.go
  pkg/cluster/etcd/etcd.go
  pkg/cluster/kubernetes/master.go
  pkg/delete/delete.go
  pkg/install/install.go
  pkg/kubesphere/kubesphere.go
  pkg/upgrade/upgrade.go
  pkg/util/executor/executor.go
  pkg/util/manager/manager.go
  scripts/docker-install.sh
  version/version.go
Labels: approved, dco-signoff: no, size/L

#308 Refine version number
  Makefile
  build.sh
  version/version.go
Labels: approved, dco-signoff: no, lgtm, size/S

#309 add the detection address at LB
  pkg/install/install.go
Labels: approved, lgtm

#310 update the detection policy
  pkg/install/install.go
Labels: approved, lgtm, size/S

#312 update lb precheck
  api/v1alpha1/cluster_types.go
  api/v1alpha1/default.go
  pkg/install/install.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#313 fix firewalld typo
  pkg/cluster/preinstall/tmpl/init_os.go
Labels: approved, dco-signoff: no, lgtm, size/XS

#314 Update eted odd check and Whether a node exists
  api/v1alpha1/cluster_types.go
Labels: approved, dco-signoff: yes, size/M

#315 update etcd backup parameter exposure
  api/v1alpha1/default.go
  api/v1alpha1/kubernetes_types.go
  pkg/cluster/etcd/etcd.go
  pkg/cluster/etcd/tmpl/etcdbackup.go
  pkg/cluster/preinstall/tmpl/init_os.go
Labels: approved, dco-signoff: no, lgtm, size/M

#316 update cluster object
  Makefile
  api/v1alpha1/addons_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  build.sh
  build/Makefile
  cmd/manager/main.go
  go.mod
  go.sum
  kubekey.go
  main.go
  pkg/addons/charts/install.go
  tools.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#318 update docker version to 19.03.13
  scripts/docker-install.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#319 update define etcd script dir
  api/v1alpha1/default.go
  api/v1alpha1/kubernetes_types.go
  pkg/cluster/etcd/etcd.go
  pkg/cluster/etcd/tmpl/etcdbackup.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#320 update crd scop
  api/v1alpha1/cluster_types.go
  config/crd/bases/kubekey.kubesphere.io_clusters.yaml
  config/rbac/role.yaml
  config/samples/kubekey_v1alpha1_cluster.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#321 Add the exposure of the flannel parameter
  api/v1alpha1/default.go
  api/v1alpha1/network_types.go
  pkg/plugins/network/flannel/tmpl.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#322 add cluster status
  api/v1alpha1/cluster_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/kubekey.kubesphere.io_clusters.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#323 Add the cilium supported
  api/v1alpha1/default.go
  pkg/cluster/preinstall/prepull_images.go
  pkg/plugins/network/cilium/tmpl.go
  pkg/plugins/network/network.go
Labels: approved, dco-signoff: yes, lgtm, size/XL
