Repository kubesphere/kubekey, pull requests merged in 2020-10, with the labels that each got.

#324 Update error display
  pkg/delete/delete.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#327 Change to user.Username
  pkg/bootstrap/os.go
  pkg/config/parse.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#328 update controller
  api/v1alpha1/cluster_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/kubekey.kubesphere.io_clusters.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/cluster_controller.go
  controllers/install.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#329 Update the judgment of nodes in a group
  api/v1alpha1/cluster_types.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#330 update Dockerfile
  Dockerfile
  config/manager/manager.yaml
  controllers/cluster_controller.go
  controllers/install.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#334 fix typos in messages
  pkg/add/add.go
  pkg/cluster/preinstall/init_os.go
  pkg/install/install.go
  pkg/upgrade/upgrade.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#335 update K8s with the kube-bench tool
  pkg/cluster/kubernetes/master.go
  pkg/cluster/kubernetes/tmpl/kubeadm.go
  pkg/util/executor/executor.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#336 update etcd to v3.4.13
  api/v1alpha1/default.go
  pkg/cluster/etcd/etcd.go
  pkg/cluster/etcd/tmpl/etcd.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#337 supported privateKey
  Dockerfile
  api/v1alpha1/default.go
  pkg/install/install.go
  pkg/util/ssh/ssh.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#339 update calico to v3.16.3
  api/v1alpha1/default.go
  pkg/plugins/network/calico/tmpl-v1.16+.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#338 return validate result
  api/v1alpha1/cluster_types.go
  api/v1alpha1/default.go
  pkg/cluster/kubernetes/master.go
  pkg/util/executor/executor.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#340 Upgrade configuration when upgrading etcd
  pkg/cluster/etcd/etcd.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#341 update parameters' type
  api/v1alpha1/cluster_types.go
  api/v1alpha1/default.go
  api/v1alpha1/kubernetes_types.go
  api/v1alpha1/network_types.go
  config/crd/bases/kubekey.kubesphere.io_clusters.yaml
  manifests/deploy.yaml
  pkg/cluster/etcd/tmpl/etcdbackup.go
  pkg/cluster/kubernetes/tmpl/kubeadm.go
  pkg/config/parse.go
  pkg/plugins/network/calico/tmpl-v1.16+.go
  pkg/util/ssh/dialer.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#345 fix lb check
  api/v1alpha1/cluster_types.go
  api/v1alpha1/default.go
Labels: approved, dco-signoff: yes, lgtm, size/S
