Repository kubesphere/kubekey, pull requests merged in 2020-11, with the labels that each got.

#354 update controller
  apis/kubekey/v1alpha1/cluster_types.go
  apis/kubekey/v1alpha1/default.go
  controllers/kubekey/cluster_controller.go
  controllers/kubekey/update_cluster.go
  manifests/parameters.yaml
  pkg/add/add.go
  pkg/addons/charts/install.go
  pkg/addons/install.go
  pkg/cluster/kubernetes/master.go
  pkg/cluster/kubernetes/nodes.go
  pkg/cluster/preinstall/precheck.go
  pkg/config/parse.go
  pkg/install/install.go
  pkg/kubesphere/kubesphere.go
  pkg/util/executor/executor.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#356 update kube-rbac-proxy image
  config/default/manager_auth_proxy_patch.yaml
  manifests/deploy.yaml
Labels: approved, lgtm

#358 update controller
  apis/kubekey/v1alpha1/cluster_types.go
  apis/kubekey/v1alpha1/default.go
  controllers/kubekey/cluster_controller.go
  manifests/parameters.yaml
  pkg/addons/charts/install.go
  pkg/addons/install.go
  pkg/cluster/kubernetes/master.go
  pkg/cluster/kubernetes/nodes.go
  pkg/cluster/preinstall/init_os.go
  pkg/kubesphere/kubesphere.go
  pkg/util/executor/executor.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#360 Remove redundant newline with fmt.Println
  .gitignore
  pkg/bootstrap/os.go
  pkg/kubesphere/kubesphere.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#366 update download script
  README.md
  README_zh-CN.md
  pkg/cluster/preinstall/preinstall.go
  scripts/downloadKubekey.sh
Labels: approved, dco-signoff: no, size/M

#361 Using a separate entry-point can reduce the size of the binary file
  Makefile
  README.md
  cmd/kk/main.go
  main.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#367 google object storage is supported
  Dockerfile
  Makefile
  README.md
  README_zh-CN.md
  build.sh
  main.go
  pkg/cluster/preinstall/preinstall.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#369 kubekey support kubeovn network plugin with kube-ovn v1.5.0
  apis/kubekey/v1alpha1/default.go
  apis/kubekey/v1alpha1/network_types.go
  pkg/cluster/preinstall/prepull_images.go
  pkg/delete/delete.go
  pkg/plugins/network/kubeovn/kubectl-ko.go
  pkg/plugins/network/kubeovn/kubeovn.go
  pkg/plugins/network/kubeovn/tmpl-v1.16+.go
  pkg/plugins/network/kubeovn/tmpl-v1.16-.go
  pkg/plugins/network/network.go
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#370 Fix the missing errors handle of kk delete cluster command
  cmd/delete_cluster.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#372 Added cluster certificate expiration date to list
  cmd/cert.go
  cmd/list_cert.go
  pkg/cert/cert.go
  scripts/docker-install.sh
Labels: approved, dco-signoff: no, lgtm, size/M

#377 Giving a friendly tips with the network isseus
  pkg/cluster/preinstall/preinstall.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#373 Align the default k8s version with the doc said
  cmd/cluster.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#374 Add an option to print all supported k8s versions
  apis/kubekey/v1alpha1/zz_generated.deepcopy.go
  cmd/version.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#375 Add completion support for kk
  cmd/completion.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#378 Using goreleaser to publish deb and rpm package
  .github/workflows/release.yaml
  .goreleaser.yml
  Makefile
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#379 update secret name
  .github/workflows/release.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#380 add cluster certs check and cluster certs renew
  cmd/cert.go
  cmd/list_cert.go
  cmd/renew_cert.go
  go.mod
  pkg/cert/cert.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#382 fix(openebs): update openebs version to 2.3.0
  pkg/cluster/preinstall/prepull_images.go
  pkg/plugins/storage/images.go
  pkg/plugins/storage/local-volume/openebs.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#386 support multi container-runtime
  apis/kubekey/v1alpha1/cluster_types.go
  apis/kubekey/v1alpha1/default.go
  apis/kubekey/v1alpha1/kubernetes_types.go
  apis/kubekey/v1alpha1/zz_generated.deepcopy.go
  pkg/cluster/etcd/etcd.go
  pkg/cluster/etcd/tmpl/etcd.go
  pkg/cluster/kubernetes/master.go
  pkg/cluster/kubernetes/nodes.go
  pkg/cluster/kubernetes/tmpl/kubeadm.go
  pkg/cluster/kubernetes/tmpl/kubelet.go
  pkg/cluster/preinstall/preinstall.go
  pkg/cluster/preinstall/prepull_images.go
  pkg/cluster/preinstall/tmpl/init_os.go
  pkg/config/generate.go
  pkg/container-engine/docker/docker.go
  pkg/files/file.go
  pkg/images/images.go
  pkg/plugins/network/calico/tmpl-v1.16+.go
  pkg/util/executor/executor.go
  pkg/util/manager/manager.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#387 Reduce the binary file size by upx
  .goreleaser.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS
