Repository kubesphere/kubekey, pull requests merged in 2020-07, with the labels that each got.

#107 add retries
  pkg/cluster/etcd/etcd.go
  pkg/cluster/kubernetes/master.go
  pkg/cluster/kubernetes/nodes.go
  pkg/cluster/preinstall/init_os.go
  pkg/cluster/preinstall/precheck.go
  pkg/container-engine/docker/docker.go
  pkg/delete/delete.go
  pkg/images/images.go
  pkg/kubesphere/kubesphere.go
  pkg/plugins/dns/dns.go
  pkg/plugins/network/network.go
  pkg/plugins/storage/storage.go
  pkg/util/executor/executor.go
  pkg/util/manager/manager.go
  pkg/util/manager/task_control.go
  pkg/util/manager/task_run.go
  pkg/util/runner/runner.go
  pkg/util/ssh/dialer.go
  pkg/util/ssh/ssh.go
Labels: approved, size/XL

#108 refine readme
  README.md
Labels: approved, lgtm, size/M

#113 add more K8s versions
  README.md
  cmd/cluster.go
  cmd/config.go
  pkg/files/file.go
Labels: approved, lgtm, size/S

#114 update config-example.md for ssh port hints
  docs/config-example.md
Labels: approved, lgtm, size/XS

#120 add more K8s versions
  README.md
  pkg/files/file.go
  pkg/plugins/network/network.go
Labels: approved, lgtm, size/M

#121 separation of install and scale
  cmd/scale.go
  pkg/scale/executor.go
  pkg/scale/scale.go
Labels: approved, lgtm, size/L

#126 Update support K8s versions, we only need to tell users the latest su…
  README.md
Labels: size/XS

#124 provide -y
  cmd/cluster.go
  cmd/scale.go
  pkg/cluster/preinstall/init_os.go
  pkg/cluster/preinstall/precheck.go
  pkg/delete/delete.go
  pkg/install/install.go
  pkg/scale/scale.go
  pkg/util/executor/executor.go
  pkg/util/manager/manager.go
Labels: approved, lgtm, size/M

#129 print more information
  pkg/config/default.go
Labels: approved, lgtm, size/XS

#131 update helm repo
  pkg/plugins/storage/storage.go
Labels: approved, lgtm, size/XS

#130 retry download binary
  pkg/cluster/preinstall/preinstall.go
Labels: approved, lgtm, size/S

#132 Increase timeout
  pkg/util/ssh/dialer.go
Labels: approved, lgtm, size/XS

#136 Add file docs/README_zh-CN.md
  README.md
  docs/README_zh-CN.md
Labels: approved, lgtm, size/L

#137 Update readme
  README.md
  README_zh-CN.md
Labels: size/M

#139 update
  README.md
  pkg/cluster/preinstall/init_os.go
  pkg/kubesphere/manifests.go
Labels: approved, lgtm, size/XS

#138 add auto build and upload
  .github/workflows/ci.yml
  README.md
  README_zh-CN.md
Labels: approved, lgtm, size/M

#140 fix doc error
  .github/workflows/ci.yml
  OWNERS
  README.md
  README_zh-CN.md
Labels: approved, size/S

#141 add stale.yaml
  .github/.stale.yaml
Labels: approved, lgtm, size/S

#144 update KubeKey docs
  README.md
  README_zh-CN.md
  docs/config-example.md
Labels: approved, lgtm, size/L

#145 extended custom parameters
  README.md
  README_zh-CN.md
  docs/config-example.md
  pkg/apis/kubekey/v1alpha1/cluster_types.go
  pkg/apis/kubekey/v1alpha1/default.go
  pkg/apis/kubekey/v1alpha1/kubernetes_types.go
  pkg/apis/kubekey/v1alpha1/network_types.go
  pkg/apis/kubekey/v1alpha1/zz_generated.deepcopy.go
  pkg/cluster/kubernetes/master.go
  pkg/cluster/kubernetes/tmpl/kubeadm.go
  pkg/config/config.go
  pkg/plugins/network/calico/tmpl.go
Labels: approved, lgtm, size/L

#152 add jwtSecret
  pkg/kubesphere/manifests.go
Labels: approved, lgtm, size/XS

#153 add storage clusterrole
  pkg/kubesphere/manifests.go
Labels: approved, lgtm, size/XS

#154 use "supported-access-modes"
  pkg/plugins/storage/ceph-rbd/ceph_rbd.go
  pkg/plugins/storage/glusterfs/glusterfs.go
  pkg/plugins/storage/local-volume/openebs.go
Labels: approved, lgtm, size/XS

#158 update kubernetes version
  cmd/cluster.go
  pkg/apis/kubekey/v1alpha1/default.go
  pkg/cluster/preinstall/init_os.go
  pkg/files/file.go
  pkg/kubesphere/kubesphere.go
  pkg/plugins/dns/dns.go
  pkg/plugins/network/network.go
  pkg/plugins/storage/storage.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#156 Update supported K8s versions
  README.md
  README_zh-CN.md
Labels: approved, dco-signoff: no, lgtm, size/S

#163 fix tag
  pkg/config/default.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#165 fix deploy rbd provisioner
  pkg/plugins/storage/storage.go
Labels: approved, dco-signoff: yes, size/XS

#169 supprot custom kube-proxy mode
  docs/config-example.md
  pkg/apis/kubekey/v1alpha1/default.go
  pkg/apis/kubekey/v1alpha1/kubernetes_types.go
  pkg/cluster/kubernetes/tmpl/kubeadm.go
Labels: approved, dco-signoff: yes, size/S

#170 privilege escalation
  go.sum
  pkg/cluster/kubernetes/master.go
  pkg/cluster/preinstall/precheck.go
Labels: dco-signoff: yes

#172 Change the default K8s version from 1.17.8 to 1.17.9
  README.md
  docs/config-example.md
Labels: approved, dco-signoff: yes, size/XS

#176 update cluster configuration
  docs/config-example.md
  pkg/cluster/kubernetes/tmpl/kubeadm.go
  pkg/config/config.go
  pkg/files/file.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#177 update config example
  docs/config-example.md
Labels: approved, dco-signoff: no, lgtm, size/S

#178 clean /etc/kubernetes
  pkg/delete/delete.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#180 Update config-example.md
  docs/config-example.md
Labels: approved, dco-signoff: no, lgtm, size/XS

#179 add skip pre pull images
  Makefile
  cmd/cluster.go
  cmd/root.go
  cmd/scale.go
  cmd/upgrade.go
  pkg/cluster/kubernetes/master.go
  pkg/cluster/preinstall/prepull_images.go
  pkg/delete/delete.go
  pkg/install/install.go
  pkg/scale/scale.go
  pkg/upgrade/upgrade.go
  pkg/util/executor/executor.go
  pkg/util/manager/manager.go
Labels: approved, dco-signoff: yes, lgtm, size/L
