Repository kubesphere/kubekey, pull requests merged in 2020-05, with the labels that each got.

#3 add owners
  OWNERS
Labels: size/S

#4 add motivation
  README.md
Labels: approved, size/XS

#6 Refine logging msg
  pkg/cluster/etcd/etcd.go
  pkg/cluster/kubernetes/master.go
  pkg/cluster/kubernetes/nodes.go
  pkg/cluster/preinstall/initOS.go
  pkg/cluster/preinstall/preinstall.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/container-engine/docker/docker.go
  pkg/controller/k2cluster/k2cluster_controller.go
  pkg/images/images.go
  pkg/install/install.go
  pkg/kubesphere/kubesphere.go
  pkg/plugins/dns/dns.go
  pkg/plugins/network/network.go
  pkg/plugins/storage/storage.go
  pkg/reset/reset.go
  pkg/scale/scale.go
  pkg/util/manager/task-control.go
  pkg/util/manager/task-run.go
  pkg/util/runner/runner.go
  pkg/util/ssh/dialer.go
  pkg/util/ssh/sftp.go
  pkg/util/ssh/ssh.go
  pkg/util/util.go
Labels: size/L

#11 Add go module proxy in China
  README.md
  build.sh
Labels: lgtm, size/XS

#12 add checksum
  pkg/apis/kubekey/v1alpha1/default.go
  pkg/cluster/kubernetes/master.go
  pkg/cluster/kubernetes/nodes.go
  pkg/cluster/preinstall/preinstall.go
  pkg/files/file.go
  pkg/install/install.go
  pkg/kubesphere/kubesphere.go
Labels: approved, size/L

#13 Fix typo
  pkg/apis/kubekey/v1alpha1/k2cluster_types.go
  pkg/config/config.go
  pkg/images/images.go
Labels: lgtm, size/XS

#16 privilege escalation
  pkg/cluster/etcd/etcd.go
Labels: size/XS

#17 add authorized_keys
  pkg/cluster/kubernetes/tmpl/kubeadm.go
  pkg/config/default.go
Labels: approved, size/S

#18 display docker install info
  pkg/container-engine/docker/docker.go
Labels: approved, size/S

#19 change variable name
  pkg/cluster/kubernetes/master.go
  pkg/cluster/preinstall/preinstall.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/container-engine/docker/docker.go
  pkg/kubesphere/kubesphere.go
  pkg/scale/scale.go
Labels: approved, size/M

#20 support custom kubeadm config
  pkg/cluster/kubernetes/master.go
  pkg/util/executor/executor.go
Labels: approved, size/M

#21 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#24 Update build.sh to includee a proxy option
  build.sh
Labels: lgtm, size/S

#25 Update Readme
  README.md
Labels: approved, lgtm, size/M

#26 refine commands
  cmd/create/config.go
  cmd/delete.go
  pkg/config/config.go
  pkg/delete/delete.go
Labels: approved, size/M

#27 Update cmd options
  .gitignore
  build.sh
  cmd/create/config.go
  go.sum
Labels: approved, lgtm, size/XXL

#22 test lgtm label bug
  OWNERS
Labels: size/XS

#29 Update config-example.yaml
  docs/config-example.md
Labels: approved, lgtm, size/S

#30 Update readme for the installation
  README.md
Labels: approved, lgtm, size/S

#31 add RBD storage support
  README.md
  go.sum
  pkg/apis/kubekey/v1alpha1/default.go
  pkg/apis/kubekey/v1alpha1/plugins_types.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/images/default.go
  pkg/images/images.go
  pkg/kubesphere/tmpl.go
  pkg/plugins/storage/ceph-rbd/ceph-rbd.go
  pkg/plugins/storage/local-volume/openebs.go
  pkg/plugins/storage/nfs-client/nfs-client.go
  pkg/plugins/storage/storage.go
Labels: approved, lgtm, size/XL

#32 add glusterfs storage support
  docs/storage-client.md
  pkg/plugins/storage/glusterfs/glusterfs.go
  pkg/plugins/storage/storage.go
Labels: approved, lgtm, size/L

#34 multi k8s version support
  README.md
  cmd/apply.go
  cmd/create/cluster.go
  cmd/create/config.go
  cmd/create/etcd.go
  go.mod
  go.sum
  pkg/cluster/kubernetes/master.go
  pkg/cluster/preinstall/preinstall.go
  pkg/config/default.go
  pkg/delete/delete.go
  pkg/files/file.go
  pkg/install/install.go
Labels: approved, lgtm, size/L

#35 Update README.md
  README.md
  pkg/apis/kubekey/v1alpha1/default.go
  pkg/config/config.go
Labels: approved, lgtm, size/M

#38 Update command and option description
  cmd/apply.go
  cmd/cmd.go
  cmd/create/cluster.go
  cmd/create/create.go
  cmd/create/etcd.go
  cmd/delete.go
  cmd/version.go
  docs/config-example.md
  pkg/util/util.go
Labels: approved, lgtm, size/S

#39 deprecated apply
  README.md
  cmd/scale.go
Labels: approved, size/XS

#40 task exits after timeout
  pkg/util/manager/task-run.go
  pkg/util/runner/runner.go
Labels: approved, lgtm, size/M

#43 check config file status
  pkg/config/config.go
  pkg/util/ssh/dialer.go
Labels: approved, size/M

#44 update roadmap
  README.md
  docs/roadmap.md
  pkg/config/config.go
Labels: approved, size/S

#45 Recognize home dir
  pkg/apis/kubekey/v1alpha1/default.go
  pkg/util/util.go
Labels: approved, lgtm, size/M

#46 Add LICENSE file
  LICENSE
  pkg/apis/kubekey/v1alpha1/kubesphere_types.go
Labels: approved, lgtm, size/L

#50 refine etcd steps
  pkg/cluster/etcd/etcd.go
  pkg/cluster/etcd/tmpl/etcd.go
  pkg/install/install.go
Labels: approved, lgtm, size/L

#51 update README.md
  README.md
  pkg/cluster/preinstall/tmpl/InitOS.go
Labels: approved, size/XS

#55 update kubesphere manifests
  pkg/config/default.go
  pkg/kubesphere/tmpl.go
Labels: approved, size/M
