Repository kubesphere/kubekey, pull requests merged in 2021-08, with the labels that each got.

#605 Experiment: solve task and action recycle dependency
  experiment/kubernetes/control-plane/tasks/tasks.go
  experiment/utils/action/command.go
  experiment/utils/action/copy.go
  experiment/utils/action/interface.go
  experiment/utils/action/template.go
  experiment/utils/action/webserver.go
  experiment/utils/ending/ending.go
  experiment/utils/ending/status_enum.go
  experiment/utils/ending/task_result.go
  experiment/utils/pipeline/task.go
  experiment/utils/vars/vars.go
Labels: approved, size/M

#609 Fix "Println arg list ends with redundant newline" when exec go vet
  pkg/cluster/upgrade/precheck.go
Labels: approved, lgtm

#613 Experiment: Add logger
  experiment/kubernetes/control-plane/tasks/module.go
  experiment/kubernetes/control-plane/tasks/tasks.go
  experiment/utils/action/base.go
  experiment/utils/action/command.go
  experiment/utils/action/copy.go
  experiment/utils/action/interface.go
  experiment/utils/action/template.go
  experiment/utils/action/webserver.go
  experiment/utils/cache/cache.go
  experiment/utils/config/manager.go
  experiment/utils/ending/task_result.go
  experiment/utils/logger/logger.go
  experiment/utils/logger/logger_test.go
  experiment/utils/pipeline/module.go
  experiment/utils/pipeline/pipeline.go
  experiment/utils/pipeline/task.go
  go.mod
  go.sum
Labels: approved

#614 Experiment: fix some logger bug
  experiment/utils/config/manager.go
  experiment/utils/logger/logger_test.go
  experiment/utils/pipeline/const.go
  experiment/utils/pipeline/task.go
Labels: approved, size/L

#617 Experiment: make pipeline module Lazy Initialization
  experiment/core/pipeline/const.go
  experiment/core/pipeline/module.go
  experiment/core/pipeline/pipeline.go
  experiment/pipeline/kubernetes/create.go
  experiment/pipeline/kubernetes/module/control_plane/module.go
Labels: approved

#619 Refine the verification of the lb configuration
  apis/kubekey/v1alpha1/default.go
Labels: approved, lgtm, size/S

#620 Experiment: add scp and fetch function
  experiment/core/action/base.go
  experiment/core/config/nodeConfig.go
  experiment/core/connector/connection.go
  experiment/core/connector/ssh/ssh.go
  experiment/core/runner/runner.go
  experiment/core/util/file.go
  experiment/core/util/util.go
  experiment/pipeline/kubernetes/module/control_plane/module.go
Labels: approved, size/XL

#622 Experiment: Add a loadblancer demo pipeline
  experiment/core/action/template.go
  experiment/core/common/common.go
  experiment/core/connector/connection.go
  experiment/core/connector/ssh/ssh.go
  experiment/core/logger/logger.go
  experiment/core/pipeline/module.go
  experiment/core/pipeline/task.go
  experiment/core/prepare/base.go
  experiment/core/prepare/prepare.go
  experiment/core/runner/runner.go
  experiment/core/util/file.go
  experiment/pipeline/kubernetes/module/control_plane/module.go
  experiment/pipeline/loadbalancer/module/module.go
  experiment/pipeline/loadbalancer/module/templates/haproxy.cfg
  experiment/pipeline/loadbalancer/module/templates/haproxy.yaml
Labels: approved, size/L

#621 Add issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/custom.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: approved, lgtm, size/L

#623 fix: same id exists in body
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: approved, lgtm, size/XS

#625 Experiment: complete loadbalancer module
  experiment/core/prepare/base.go
  experiment/core/prepare/prepare.go
  experiment/pipeline/loadbalancer/module/module.go
  experiment/pipeline/loadbalancer/module/tasks.go
Labels: approved

#627 Remove the asNumber and peerIP dependencies
  pkg/plugins/network/calico/tmpl-v1.16+.go
Labels: approved, lgtm, size/XS

#629 Experiment: successfully run a demo pipeline
  experiment/cmd/cluster.go
  experiment/cmd/kk/main.go
  experiment/core/action/base.go
  experiment/core/action/interface.go
  experiment/core/cache/cache.go
  experiment/core/ending/status_enum.go
  experiment/core/ending/task_result.go
  experiment/core/logger/logger.go
  experiment/core/modules/base.go
  experiment/core/modules/const.go
  experiment/core/modules/custom_module.go
  experiment/core/modules/interface.go
  experiment/core/modules/task.go
  experiment/core/modules/task_module.go
  experiment/core/pipeline/const.go
  experiment/core/pipeline/pipeline.go
  experiment/core/prepare/base.go
  experiment/core/prepare/fast_prepare.go
  experiment/core/prepare/interface.go
  experiment/core/runner/runner.go
  experiment/pipeline/kubernetes/create.go
  experiment/pipeline/kubernetes/module/control_plane/module.go
  experiment/pipelines/create_cluster.go
  experiment/pipelines/initialization/const.go
  experiment/pipelines/initialization/module.go
  experiment/pipelines/initialization/tasks.go
  experiment/pipelines/kubernetes/delete.go
  experiment/pipelines/kubernetes/scale.go
  experiment/pipelines/loadbalancer/const.go
  experiment/pipelines/loadbalancer/module.go
  experiment/pipelines/loadbalancer/tasks.go
  experiment/pipelines/loadbalancer/templates/haproxyConfig.go
  experiment/pipelines/loadbalancer/templates/haproxyManifest.go
  go.mod
  go.sum
Labels: approved, size/XL

#633 Add the requirement for Linux Kernel Version
  README.md
  README_zh-CN.md
Labels: approved, lgtm, size/XS

#634 Support kubernetes v1.21.4 v1.22.1
  README.md
  README_zh-CN.md
  apis/kubekey/v1alpha1/cluster_types.go
  apis/kubekey/v1alpha1/default.go
  apis/kubekey/v1alpha1/kubernetes_types.go
  docs/kubernetes-versions.md
  pkg/files/file.go
  pkg/k3s/config/service.go
  pkg/kubernetes/config/v1beta2/kubeadm.go
  pkg/kubernetes/preinstall/prepull_images.go
  pkg/plugins/dns/coredns.go
  pkg/plugins/dns/dns.go
  pkg/plugins/dns/nodelocaldns.go
  pkg/plugins/network/calico/tmpl-v1.16+.go
  pkg/util/executor/executor.go
  version/k8s.go
Labels: approved, lgtm, size/XL

#635 Experiment: redesign the way to control task exec
  apis/kubekey/v1alpha1/cluster_types.go
  cmd/root.go
  go.mod
  go.sum
  pkg/core/action/base.go
  pkg/core/action/command.go
  pkg/core/action/interface.go
  pkg/core/action/template.go
  pkg/core/cache/cache.go
  pkg/core/common/common.go
  pkg/core/config/runtime.go
  pkg/core/connector/ssh/ssh.go
  pkg/core/ending/ending.go
  pkg/core/ending/task_result.go
  pkg/core/logger/formatter.go
  pkg/core/logger/logger.go
  pkg/core/logger/logger_test.go
  pkg/core/modules/base.go
  pkg/core/modules/interface.go
  pkg/core/modules/task.go
  pkg/core/modules/task_module.go
  pkg/core/pipeline/pipeline.go
  pkg/core/prepare/base.go
  pkg/core/prepare/fast_prepare.go
  pkg/core/prepare/interface.go
  pkg/core/prepare/prepare.go
  pkg/core/runner/runner.go
  pkg/pipelines/binaries/module.go
  pkg/pipelines/binaries/tasks.go
  pkg/pipelines/create_cluster.go
  pkg/pipelines/initialization/module.go
  pkg/pipelines/initialization/tasks.go
  pkg/pipelines/loadbalancer/module.go
  pkg/pipelines/loadbalancer/tasks.go
Labels: approved, size/XXL

#637 Fix dns address configuration error in cluster
  apis/kubekey/v1alpha1/cluster_types.go
  apis/kubekey/v1alpha1/default.go
  apis/kubekey/v1alpha1/kubernetes_types.go
  apis/kubekey/v1alpha1/zz_generated.deepcopy.go
  pkg/k3s/config/service.go
  pkg/kubernetes/preinstall/prepull_images.go
  pkg/plugins/dns/coredns.go
  pkg/plugins/dns/dns.go
  pkg/plugins/dns/nodelocaldns.go
Labels: approved, lgtm, size/M

#646 Experiment: support display multiple error task result
  experiment/pipeline/loadbalancer/module/templates/haproxy.cfg
  experiment/pipeline/loadbalancer/module/templates/haproxy.yaml
  pkg/core/ending/task_result.go
  pkg/core/modules/task.go
  pkg/core/modules/task_module.go
Labels: approved, size/L

#648 fix: solve the bug that kk lacks a task to install docker
  pkg/container-engine/docker/docker.go
Labels: approved, lgtm, size/XS
