Repository kubesphere/kubekey, pull requests merged in 2021-02, with the labels that each got.

#441 Update KubeKey desc
  .github/settings.yml
  .goreleaser.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#443 Fix download-cmd parameter about adding nodes and updating cluster
  cmd/add_nodes.go
  cmd/upgrade.go
  go.mod
  go.sum
  pkg/add/add.go
  pkg/upgrade/upgrade.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#445 Add GitHub action for release drafter
  .github/OWNERS
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M

#449 Fix: compile the abnormal
  go.mod
  pkg/add/add.go
Labels: approved, dco-signoff: yes, lgtm, size/XS
