Repository kubesphere/kubekey, pull requests merged in 2021-05, with the labels that each got.

#525 use go std-library's SHA256Sum to check download binary file
  pkg/kubernetes/preinstall/preinstall.go
  pkg/kubernetes/preinstall/preinstall_test.go
  pkg/kubernetes/preinstall/testdata/goodby.txt
  pkg/kubernetes/preinstall/testdata/hello.txt
Labels: approved, dco-signoff: no, lgtm, size/M

#529 update addons doc
  docs/addons.md
Labels: approved, dco-signoff: yes, size/XS

#531 support close for connection
  pkg/util/ssh/ssh.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#533 chore(openebs): update openebs version to 2.9.0
  pkg/kubernetes/preinstall/prepull_images.go
  pkg/plugins/storage/local-volume/openebs.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#534 update example config
  docs/config-example.md
Labels: approved, dco-signoff: yes, size/L

#535 Update config example
  docs/config-example.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#537 Table becomes space
  pkg/plugins/storage/local-volume/openebs.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#544 Fix typo: helthCheck -> healthCheck
  pkg/etcd/etcd.go
Labels: approved, dco-signoff: yes, lgtm, size/S
