Repository kubesphere/kubekey, pull requests merged in 2021-11, with the labels that each got.

#739 dev-v2.0.0: add AutoRenewCertsModule
  .github/workflows/ci.yml
  cmd/cluster.go
  pkg/bootstrap/precheck/module.go
  pkg/certs/module.go
  pkg/certs/prepares.go
  pkg/certs/tasks.go
  pkg/certs/templates/certs_renew_script.go
  pkg/certs/templates/certs_renew_service.go
  pkg/common/loader.go
  pkg/kubesphere/tasks.go
  pkg/pipelines/add_nodes.go
  pkg/pipelines/create_cluster.go
  pkg/pipelines/delete_cluster.go
  pkg/pipelines/upgrade_cluster.go
  pkg/version/kubesphere/version_enum.go
Labels: approved, lgtm, size/L

#743 dev-v2.0.0: add ignore-err option
  cmd/add_nodes.go
  cmd/cluster.go
  cmd/root.go
  config/manager/manager.yaml
  controllers/kubekey/cluster_controller.go
  pkg/common/kube_action.go
  pkg/common/kube_module.go
  pkg/common/kube_prepare.go
  pkg/common/kube_runtime.go
  pkg/core/connector/host.go
  pkg/core/connector/interface.go
  pkg/core/connector/runtime.go
  pkg/core/module/task_module.go
  pkg/core/pipeline/pipeline.go
  pkg/core/task/remote_task.go
  pkg/pipelines/add_nodes.go
Labels: approved, lgtm, size/L

#748 dev-v2.0.0: fix permission denied error
  pkg/bootstrap/os/tasks.go
  pkg/certs/tasks.go
  pkg/container/containerd.go
  pkg/container/docker.go
  pkg/core/connector/interface.go
  pkg/core/connector/runner.go
  pkg/core/connector/ssh.go
  pkg/etcd/tasks.go
  pkg/k3s/tasks.go
  pkg/kubernetes/tasks.go
  pkg/utils/util.go
Labels: approved, lgtm, size/L

#749 dev-v2.0.0: reconcile func clear condition before run new job
  controllers/kubekey/cluster_controller.go
Labels: approved, lgtm, size/S

#742 Change externalElasticsearchUrl to externalElasticsearchHost at cc
  docs/config-example.md
  pkg/kubesphere/manifests.go
  pkg/kubesphere/templates.go
Labels: approved, lgtm, size/S

#750 Revert "Change externalElasticsearchUrl to externalElasticsearchHost at cc"
  docs/config-example.md
  pkg/kubesphere/manifests.go
  pkg/kubesphere/templates.go
Labels: approved, lgtm, size/S

#753 dev-v2.0.0: save kube config after create cluster
  controllers/kubekey/cluster_controller.go
  controllers/kubekey/update_cluster.go
  pkg/common/kube_action.go
  pkg/k3s/module.go
  pkg/k3s/tasks.go
  pkg/kubernetes/module.go
  pkg/kubernetes/tasks.go
  pkg/pipelines/create_cluster.go
Labels: approved, lgtm, size/L

#754 dev-v2.0.0: fix conditions bug
  controllers/kubekey/cluster_controller.go
  controllers/kubekey/update_cluster.go
  pkg/pipelines/add_nodes.go
  pkg/pipelines/create_cluster.go
Labels: approved, lgtm, size/S

#752 Update preinstall.go
  pkg/k3s/preinstall/preinstall.go
Labels: approved, lgtm, size/XS

#756 dev-v2.0.0: operator delete err job
  controllers/kubekey/cluster_controller.go
Labels: approved, lgtm, size/XS

#760 dev-v2.0.0: fix operator spends to much time to creating new job
  controllers/kubekey/cluster_controller.go
Labels: approved, lgtm, size/S

#761 dev-v2.0.0: save base64 encode kubeconfig by configmap
  controllers/kubekey/cluster_controller.go
  controllers/kubekey/update_cluster.go
  pkg/k3s/tasks.go
  pkg/kubernetes/kubernetes_status.go
  pkg/kubernetes/tasks.go
Labels: approved, lgtm, size/M

#763 dev-v2.0.0: fix etcd certs error
  pkg/etcd/tasks.go
Labels: approved, lgtm, size/XS

#765 dev-v2.0.0: refactor cmd package
  .goreleaser.yml
  Dockerfile
  Makefile
  build.sh
  cmd/add.go
  cmd/add_nodes.go
  cmd/cert.go
  cmd/cluster.go
  cmd/config.go
  cmd/ctl/add/add.go
  cmd/ctl/add/add_nodes.go
  cmd/ctl/cert/cert.go
  cmd/ctl/cert/list_cert.go
  cmd/ctl/cert/renew_cert.go
  cmd/ctl/completion/completion.go
  cmd/ctl/create/cluster.go
  cmd/ctl/create/config.go
  cmd/ctl/create/create.go
  cmd/ctl/delete/delete.go
  cmd/ctl/delete/delete_cluster.go
  cmd/ctl/delete/delete_node.go
  cmd/ctl/init/init.go
  cmd/ctl/init/init_os.go
  cmd/ctl/options/persistent_options.go
  cmd/ctl/root.go
  cmd/ctl/upgrade/upgrade.go
  cmd/ctl/util/helpers.go
  cmd/ctl/version/version.go
  cmd/delete_cluster.go
  cmd/delete_node.go
  cmd/init_os.go
  cmd/kk/main.go
  cmd/list_cert.go
  cmd/main.go
  cmd/renew_cert.go
  cmd/root.go
  cmd/upgrade.go
  go.sum
Labels: approved, lgtm, size/XXL

#767 merge master into release-1.2 branch
  .all-contributorsrc
  CONTRIBUTORS.md
  README.md
  README_zh-CN.md
  pkg/k3s/preinstall/preinstall.go
Labels: approved, lgtm, size/S

#775 dev-v2.0.0: support plugin mode
  cmd/ctl/options/io_options.go
  cmd/ctl/plugin/list.go
  cmd/ctl/plugin/plugin.go
  cmd/ctl/root.go
  pkg/binaries/k3s.go
Labels: approved, lgtm, size/L

#776 Support kubernetes and k3s to v1.21.6
  Dockerfile.binaries
  apis/kubekey/v1alpha1/zz_generated.deepcopy.go
  config/manager/kustomization.yaml
  pkg/files/file.go
Labels: approved, lgtm, size/S

#780 dev-v2.0.0: update config example
  README.md
  README_zh-CN.md
  docs/config-example.md
Labels: approved, lgtm, size/XS

#781 Add an architecture pic in ha-mode.md and fix a version match bug
  docs/ha-mode.md
  docs/img/internalLoadBalancer.png
  pkg/bootstrap/precheck/tasks.go
  pkg/common/loader.go
  pkg/config/generate.go
  pkg/kubesphere/modules.go
  pkg/version/kubesphere/version_enum.go
  pkg/version/kubesphere/version_enum_test.go
Labels: approved, lgtm, size/L

#787 dev-v2.0.0: sync master branch kube-ovn module
  pkg/kubernetes/module.go
  pkg/plugins/network/modules.go
  pkg/plugins/network/prepares.go
  pkg/plugins/network/tasks.go
  pkg/plugins/network/templates/kubectl_ko.go
  pkg/plugins/network/templates/kubeovn_v1.16+.go
  pkg/plugins/network/templates/kubeovn_v1.16-.go
Labels: approved, lgtm, size/XXL

#788 dev-v2.0.0: fix a kube config file owner bug
  pkg/certs/tasks.go
  pkg/k3s/tasks.go
  pkg/kubernetes/tasks.go
Labels: approved, lgtm, size/M

#796 dev-v2.0.0: fix binary file's name are different from their origin name
  pkg/container/containerd.go
  pkg/container/docker.go
  pkg/k3s/tasks.go
  pkg/kubernetes/tasks.go
Labels: approved, lgtm, size/S

#799 [release-1.2] support kubesphere v3.2.1
  cmd/cluster.go
  pkg/cluster/upgrade/kubernetes.go
  pkg/cluster/upgrade/precheck.go
  pkg/config/generate.go
  pkg/config/parse.go
  pkg/kubesphere/kubesphere.go
  pkg/kubesphere/manifests.go
  pkg/kubesphere/templates.go
Labels: approved, lgtm, size/L

#800 [release-1.2]: fix a bug that private registry can't be set when os env KKZONE is cn
  pkg/kubesphere/manifests.go
Labels: approved, lgtm, size/XS

#801 fix a bug that private registry can't be set when os env KKZONE is cn
  pkg/kubesphere/modules.go
Labels: approved, lgtm, size/S

#803 fix kk controller-manager can't get correct etcd nodes info
  config/manager/manager.yaml
  controllers/kubekey/cluster_controller.go
  controllers/kubekey/cluster_controller_test.go
Labels: approved, lgtm, size/L

#806 Add 'PiplineInfo' field for cluster status
  apis/kubekey/v1alpha2/cluster_types.go
  apis/kubekey/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/kubekey.kubesphere.io_clusters.yaml
  controllers/kubekey/cluster_controller.go
  controllers/kubekey/update_cluster.go
Labels: approved, lgtm, size/M

#805 support kubesphere v3.2.1
  cmd/ctl/create/cluster.go
  cmd/ctl/upgrade/upgrade.go
  cmd/ctl/version/version.go
  pkg/version/kubernetes/version_enum.go
  pkg/version/kubesphere/ks_installer.go
  pkg/version/kubesphere/templates/cc_v321.go
  pkg/version/kubesphere/version_enum.go
  version/k8s.go
Labels: approved, lgtm, size/L

#813 Fix typo.
  pkg/container/module.go
Labels: approved, lgtm, size/XS

#814 Refactoring code.
  apis/kubekey/v1alpha1/cluster_types.go
  apis/kubekey/v1alpha1/kubernetes_types.go
  apis/kubekey/v1alpha2/kubernetes_types.go
  controllers/kubekey/cluster_controller.go
  pkg/certs/prepares.go
  pkg/container/prepares.go
  pkg/core/connector/host.go
  pkg/core/task/local_task.go
  pkg/core/task/remote_task.go
  pkg/etcd/prepares.go
  pkg/etcd/tasks.go
  pkg/k3s/prepares.go
  pkg/plugins/network/modules.go
  pkg/plugins/network/prepares.go
  pkg/version/kubesphere/version_enum.go
Labels: approved, lgtm, size/M
