Repository kubesphere/kubekey, pull requests merged in 2021-04, with the labels that each got.

#495 Update tools.go
  hack/tools.go
Labels: approved, dco-signoff: no, lgtm, size/S

#497 supported k3s and ks latest
  apis/kubekey/v1alpha1/default.go
  pkg/cluster/upgrade/precheck.go
  pkg/config/generate.go
  pkg/config/parse.go
  pkg/deploy/kubesphere.go
  pkg/kubesphere/manifests.go
Labels: approved, lgtm

#498 supported upgrade ks
  pkg/cluster/upgrade/kubesphere.go
  pkg/cluster/upgrade/precheck.go
  pkg/kubesphere/kubesphere.go
Labels: approved, dco-signoff: yes, size/L

#499 Rename binary filename from kubekey to kk
  .github/workflows/release.yaml
  .goreleaser.yml
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#500 Fix the release-drafter errors
  .github/workflows/release-drafter.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#502 supported k8s v1.19.9
  pkg/files/file.go
  version/k8s.go
Labels: approved, dco-signoff: no, size/XS

#503 Use master's IP as advertise-address
  pkg/cluster/upgrade/kubernetes.go
  pkg/kubernetes/master.go
  pkg/kubernetes/tmpl/kubeadm.go
Labels: approved, dco-signoff: yes, size/S

#504 update install-docker script
  scripts/docker-install.sh
Labels: approved, dco-signoff: yes, size/XL

#505 Support custom k8s args
  apis/kubekey/v1alpha1/kubernetes_types.go
  apis/kubekey/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
  pkg/cluster/upgrade/kubernetes.go
  pkg/k3s/config/service.go
  pkg/k3s/master.go
  pkg/k3s/nodes.go
  pkg/kubernetes/config/kubelet.go
  pkg/kubernetes/config/v1beta2/kubeadm.go
  pkg/kubernetes/master.go
  pkg/kubernetes/nodes.go
  pkg/kubernetes/tmpl/kubeadm.go
  pkg/util/util.go
Labels: approved, dco-signoff: yes, size/XXL

#506 sync ks-installer cluster configuration
  pkg/kubesphere/manifests.go
Labels: approved, dco-signoff: yes, size/XS

#511 add configuration parameters
  pkg/kubesphere/manifests.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#512 Set the bind-adress default to 0.0.0.0
  pkg/kubernetes/config/v1beta2/kubeadm.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#514 Add default parameters for k3s
  pkg/k3s/config/service.go
  pkg/kubesphere/kubesphere.go
Labels: approved, dco-signoff: yes, size/S

#515 don't retain the old manifeats of network plugin
  .goreleaser.yml
  pkg/plugins/network/network.go
Labels: approved, dco-signoff: yes, size/L

#516 retain etcd and kubectl that already exists
  pkg/cluster/delete/delete.go
  pkg/etcd/etcd.go
Labels: approved, dco-signoff: yes, size/S

#517 update initialization configuration
  pkg/bootstrap/configuration/init_script.go
  pkg/bootstrap/dependencies/os.go
  pkg/container-engine/docker/docker.go
  scripts/docker-install.sh
Labels: approved, dco-signoff: yes, size/M

#518 Support setting zone for KubeSphere
  pkg/kubesphere/manifests.go
Labels: approved, dco-signoff: yes, size/XS

#519 add docker version checking
  pkg/cluster/upgrade/precheck.go
  pkg/kubernetes/preinstall/precheck.go
  pkg/util/util.go
Labels: approved, dco-signoff: yes, size/M

#522 Update k8s and ks version to latest
  README.md
  README_zh-CN.md
  cmd/config.go
  cmd/upgrade.go
  config/samples/kubekey_v1alpha1_cluster.yaml
  docs/config-example.md
Labels: approved, dco-signoff: yes, lgtm, size/S
