Repository kubesphere/kubekey, pull requests merged in 2021-03, with the labels that each got.

#477 Improve the documentation for kk bash completion
  README.md
  cmd/completion.go
  docs/kubekey-autocompletion.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#480 add k8s version support:v1.19.8, v1.20.4
  pkg/files/file.go
  version/k8s.go
Labels: dco-signoff: yes, size/S

#482 add logo
  docs/img/kubekey-logo.svg
  docs/img/kukekey-logo.png
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#484 fix logo svg
  docs/img/kubekey-logo.svg
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#485 support for choosing whether to deploy local storage
  cmd/cluster.go
  cmd/root.go
  pkg/cluster/delete/delete.go
  pkg/cluster/install/install.go
  pkg/cluster/install/tasks.go
  pkg/cluster/upgrade/precheck.go
  pkg/config/parse.go
  pkg/k3s/config/service.go
  pkg/k3s/master.go
  pkg/k3s/nodes.go
  pkg/kubesphere/kubesphere.go
  pkg/kubesphere/manifests.go
  pkg/util/executor/executor.go
  pkg/util/manager/manager.go
Labels: approved, dco-signoff: yes, size/L

#488 fix readme zh_CN
  README_zh-CN.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#492 update default kubernetes version to v1.19.8
  apis/kubekey/v1alpha1/default.go
  pkg/cluster/upgrade/kubesphere.go
  pkg/kubernetes/preinstall/precheck.go
Labels: approved, dco-signoff: yes, lgtm, size/S
