Repository kubesphere/kubekey, pull requests merged in 2021-12, with the labels that each got.

#820 Fix pipeline name and add some error handle.
  cmd/ctl/plugin/list.go
  controllers/kubekey/update_cluster.go
  pkg/addons/manifests.go
  pkg/config/generate.go
  pkg/pipelines/delete_node.go
  pkg/pipelines/renew_certs.go
Labels: approved, lgtm, size/M

#828 [release-1.2] fix variable is an empty string
  pkg/kubesphere/kubesphere.go
Labels: approved, lgtm, size/XS

#827 modify all-in-one cluster name
  pkg/common/loader.go
Labels: approved, lgtm, size/XS

#834 fix cp file text busy error
  pkg/core/common/common.go
  pkg/core/connector/runner.go
Labels: approved, lgtm, size/XS

#835 fix flag --with-kubernetes is not working
  pkg/common/loader.go
Labels: approved, lgtm, size/S

#836 fix: sed is not working in init script
  pkg/bootstrap/os/templates/init_script.go
Labels: approved, lgtm, size/XS

#840 [release-1.2] fix upgrade check ks version error
  pkg/cluster/upgrade/precheck.go
Labels: approved, lgtm, size/S

#841 show the download progress.
  pkg/binaries/k3s.go
  pkg/binaries/kubernetes.go
Labels: approved, lgtm, size/M

#844 fix the default flag value makes kk can't create k3s cluster
  cmd/ctl/create/cluster.go
Labels: approved, lgtm, size/XS

#850 Support [--yes] parameter when upgrade cluster
  cmd/ctl/upgrade/upgrade.go
  pkg/pipelines/upgrade_cluster.go
Labels: approved, lgtm, size/XS

#852 fix handle error node bug
  pkg/core/connector/runtime.go
  pkg/core/task/remote_task.go
Labels: approved, lgtm, size/XS

#856 fix handle error node nil pointer
  pkg/core/task/remote_task.go
Labels: approved, lgtm, size/XS

#866 fix(cilium&flannel): remove `OldK8sVersion` of `prepare` in `deployFlannel` and `deployCilium`
  pkg/plugins/network/modules.go
Labels: approved, lgtm, size/S

#870 fix(kk): kk recreate cluster with error #851 :get etcd local certs di…
  pkg/etcd/tasks.go
Labels: approved, lgtm, size/XS

#872 fix kubeovn yaml lint bug
  pkg/plugins/network/tasks.go
  pkg/plugins/network/templates/kubeovn_v1.16+.go
Labels: approved, lgtm, size/XS

#869 Optimize the operator logic
  controllers/kubekey/cluster_controller.go
Labels: approved, lgtm, size/S

#880 multus support
  apis/kubekey/v1alpha2/default.go
  apis/kubekey/v1alpha2/network_types.go
  pkg/config/templates/cluster.go
  pkg/images/tasks.go
  pkg/plugins/network/modules.go
  pkg/plugins/network/tasks.go
  pkg/plugins/network/templates/multus.go
Labels: approved, lgtm, size/L

#882 Fix savekubeconfig： use InternalAddress that can't be connected when kk is not running in k8s node internal network.
  pkg/kubernetes/tasks.go
Labels: approved, lgtm, size/M

#884 [release-1.2] fix pipeline doesn't skip
  pkg/cluster/upgrade/upgrade.go
Labels: approved, lgtm, size/XS

#878 fix containerd file not found error
  pkg/container/containerd.go
Labels: approved, lgtm, size/XS

#885 fix error file mode on $HOME/.kube
  pkg/bootstrap/precheck/tasks.go
  pkg/certs/tasks.go
  pkg/filesystem/module.go
  pkg/filesystem/task.go
  pkg/k3s/tasks.go
  pkg/kubernetes/tasks.go
  pkg/pipelines/add_nodes.go
  pkg/pipelines/create_cluster.go
  pkg/pipelines/upgrade_cluster.go
Labels: approved, lgtm, size/L

#887 Support Kubernetes 1.23
  pkg/files/file.go
  pkg/images/tasks.go
Labels: approved, lgtm, size/S

#888 Support Kubernetes 1.23
  docs/kubernetes-versions.md
  pkg/version/kubernetes/version_enum.go
Labels: approved, lgtm, size/XS

#895 [release-2.0] Manual cherrypick #888 Support Kubernetes 1.23
  docs/kubernetes-versions.md
  pkg/version/kubernetes/version_enum.go
Labels: approved, lgtm, size/XS

#896 fix(kk): #889 Remove AddonsModule must need a network plugin enabled
  pkg/pipelines/create_cluster.go
Labels: approved, lgtm, size/M

#898 use raw string for regexp to avoid escape twice.
  controllers/kubekey/cluster_controller.go
Labels: approved, lgtm, size/XS

#902 fea(kk): add enable featureGates in kubernetes of cluster-config
  apis/kubekey/v1alpha1/zz_generated.deepcopy.go
  apis/kubekey/v1alpha2/kubernetes_types.go
  apis/kubekey/v1alpha2/zz_generated.deepcopy.go
  docs/config-example.md
  pkg/kubernetes/tasks.go
  pkg/kubernetes/templates/v1beta2/kubeadm_config.go
Labels: approved, lgtm, size/M

#909 docs: Update kk upgrade parameters
  README.md
  README_zh-CN.md
Labels: approved, lgtm, size/S

#910 fix: --container-manager flag doesn't work
  cmd/ctl/create/cluster.go
  pkg/common/kube_runtime.go
  pkg/common/loader.go
Labels: approved, lgtm, size/S

#914 fea(#913): [kk] disable SELINUX in init the OS
  pkg/bootstrap/os/templates/init_script.go
Labels: approved, lgtm, size/S

#916 fix: remove unneed logs in GetKubeletConfiguration
  pkg/kubernetes/templates/v1beta2/kubeadm_config.go
Labels: approved, lgtm, size/S

#919 modify the github workflow and build using go 1.17
  .github/workflows/ci.yml
  .github/workflows/release.yaml
Labels: approved, lgtm, size/S

#921 fea(#915): support custom private registry authorization
  apis/kubekey/v1alpha2/cluster_types.go
  apis/kubekey/v1alpha2/zz_generated.deepcopy.go
  docs/config-example.md
  pkg/container/docker.go
  pkg/container/module.go
  pkg/container/templates/containerd_config.go
  pkg/container/templates/docker_config.go
Labels: approved, lgtm, size/L

#934 fix install container runtime failed
  pkg/container/module.go
  pkg/container/prepares.go
Labels: approved, lgtm, size/S

#937 bump helm/v3, image-spec and logr
  config/crd/bases/kubekey.kubesphere.io_clusters.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/M, dependencies

#941 modify manifest's containerRuntime to a list
  apis/kubekey/v1alpha2/manifest_types.go
  apis/kubekey/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/kubekey.kubesphere.io_manifests.yaml
  pkg/artifact/manifest.go
  pkg/artifact/templates/manifest.go
  pkg/binaries/kubernetes.go
  pkg/files/file.go
Labels: approved, lgtm, size/L

#942 modify ImagePushModule to use the containerd SDK
  cmd/ctl/artifact/export.go
  pkg/images/images.go
  pkg/images/module.go
  pkg/images/tasks.go
  pkg/utils/containerruntime/runtime.go
Labels: approved, lgtm, size/L

#944 Support kubekey to independently generate certificates
  cmd/ctl/create/cluster.go
  go.mod
  pkg/common/kube_runtime.go
  pkg/core/connector/ssh.go
  pkg/etcd/certs.go
  pkg/etcd/module.go
  pkg/etcd/tasks.go
  pkg/etcd/templates/certs_script.go
  pkg/etcd/templates/openssl_config.go
  pkg/utils/certs/certs.go
  pkg/utils/certs/utils.go
Labels: approved, lgtm, size/XXL

#946 fix: generate kubesphere repo error
  cmd/ctl/create/cluster.go
  pkg/kubesphere/kubesphere_test.go
  pkg/kubesphere/modules.go
  pkg/version/kubesphere/version_enum.go
  pkg/version/kubesphere/version_enum_test.go
Labels: approved, lgtm, size/L

#948 fix: push image failed by containerd client
  pkg/images/images.go
  pkg/images/tasks.go
Labels: approved, lgtm, size/M

#949 fix: images name and tar parse failed
  pkg/artifact/tasks.go
  pkg/images/images.go
Labels: approved, lgtm, size/M

#947 fix cmd delete node.
  cmd/ctl/delete/delete.go
  cmd/ctl/delete/delete_node.go
  pkg/pipelines/delete_node.go
Labels: approved, lgtm, size/S
