Repository kubesphere/kubekey, pull requests merged in 2021-01, with the labels that each got.

#415 support for adding node labels
  apis/kubekey/v1alpha1/cluster_types.go
  pkg/cluster/kubernetes/master.go
  pkg/cluster/kubernetes/nodes.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#416 show all contributors
  .all-contributorsrc
  .gitignore
  CONTRIBUTORS.md
  README.md
  README_zh-CN.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#417 update RotateKubeletServerCertificate and RotateKubeletClientCertificate
  pkg/cluster/kubernetes/tmpl/kubeadm.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#421 update config-example format
  docs/config-example.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#422 update roadmap
  docs/roadmap.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#419 add init script
  pkg/cluster/preinstall/tmpl/init_os.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#423 add developer guide
  README.md
  README_zh-CN.md
  docs/developer-guide.md
  docs/img/KubeKey-Addons.jpg
  docs/img/KubeKey-Architecture.jpg
Labels: approved, dco-signoff: yes, size/M

#426 Automatic the go depend, release draft, project settings
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/settings.yml
Labels: approved, dco-signoff: yes, lgtm, size/L

#425 Add user defined tools download command option
  cmd/cluster.go
  cmd/root.go
  pkg/cluster/preinstall/preinstall.go
  pkg/install/install.go
  pkg/util/executor/executor.go
  pkg/util/manager/manager.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#439 Revert "Bump github.com/go-logr/logr from 0.1.0 to 0.4.0"
  go.mod
  go.sum
Labels: approved, dco-signoff: no, size/XS
