Repository kubesphere/kubekey, pull requests merged in 2021-09, with the labels that each got.

#651 Experiment: add more modules and fix schedule bug
  cmd/cluster.go
  go.mod
  go.sum
  pkg/core/action/base.go
  pkg/core/connector/dialer.go
  pkg/core/connector/host.go
  pkg/core/connector/interface.go
  pkg/core/connector/runner.go
  pkg/core/connector/runtime.go
  pkg/core/connector/ssh.go
  pkg/core/logger/logger.go
  pkg/core/modules/base.go
  pkg/core/modules/custom_module.go
  pkg/core/modules/interface.go
  pkg/core/modules/task.go
  pkg/core/modules/task_module.go
  pkg/core/pipeline/pipeline.go
  pkg/core/prepare/base.go
  pkg/core/prepare/file_check.go
  pkg/core/prepare/interface.go
  pkg/core/util/file.go
  pkg/core/util/ip.go
  pkg/core/util/util.go
  pkg/pipelines/binaries/k3s.go
  pkg/pipelines/binaries/kubernetes.go
  pkg/pipelines/binaries/module.go
  pkg/pipelines/binaries/tasks.go
  pkg/pipelines/common/common.go
  pkg/pipelines/common/const.go
  pkg/pipelines/common/kube_action.go
  pkg/pipelines/common/kube_module.go
  pkg/pipelines/common/kube_prepare.go
  pkg/pipelines/common/kube_runtime.go
  pkg/pipelines/continer/docker/module.go
  pkg/pipelines/continer/docker/tasks.go
  pkg/pipelines/continer/docker/templates/docker_config.go
  pkg/pipelines/create_cluster.go
  pkg/pipelines/images/images.go
  pkg/pipelines/images/module.go
  pkg/pipelines/images/tasks.go
  pkg/pipelines/initialization/module.go
  pkg/pipelines/initialization/tasks.go
  pkg/pipelines/initialization/templates/init_script.go
  pkg/pipelines/loadbalancer/module.go
  pkg/pipelines/loadbalancer/templates/haproxyManifest.go
Labels: approved, size/XXL

#656 Experiment: add some modules
  pkg/core/connector/host.go
  pkg/core/connector/interface.go
  pkg/core/connector/runner.go
  pkg/core/connector/runtime.go
  pkg/core/connector/ssh.go
  pkg/core/modules/base.go
  pkg/core/modules/task_module.go
  pkg/core/modules/task_test.go
  pkg/core/prepare/fast_prepare.go
  pkg/pipelines/binaries/kubernetes.go
  pkg/pipelines/binaries/module.go
  pkg/pipelines/common/common.go
  pkg/pipelines/common/kube_prepare.go
  pkg/pipelines/common/kube_runtime.go
  pkg/pipelines/continer/docker/module.go
  pkg/pipelines/continer/docker/tasks.go
  pkg/pipelines/continer/docker/templates/docker_config.go
  pkg/pipelines/create_cluster.go
  pkg/pipelines/etcd/module.go
  pkg/pipelines/etcd/prepares.go
  pkg/pipelines/etcd/tasks.go
  pkg/pipelines/etcd/templates/backup_script.go
  pkg/pipelines/etcd/templates/certs_script.go
  pkg/pipelines/etcd/templates/etcd_env.go
  pkg/pipelines/etcd/templates/etcd_service.go
  pkg/pipelines/etcd/templates/openssl_config.go
  pkg/pipelines/images/images.go
  pkg/pipelines/images/module.go
  pkg/pipelines/images/tasks.go
  pkg/pipelines/initialization/module.go
  pkg/pipelines/initialization/tasks.go
  pkg/pipelines/kubernetes/kubernetes_status.go
  pkg/pipelines/kubernetes/module.go
  pkg/pipelines/kubernetes/prepares.go
  pkg/pipelines/kubernetes/tasks.go
  pkg/pipelines/kubernetes/templates/kubelet_env.go
  pkg/pipelines/kubernetes/templates/kubelet_service.go
  pkg/pipelines/kubernetes/templates/v1beta2/kubeadm_config.go
  pkg/pipelines/loadbalancer/const.go
  pkg/pipelines/loadbalancer/module.go
  pkg/pipelines/loadbalancer/prepares.go
  pkg/pipelines/loadbalancer/tasks.go
  pkg/pipelines/loadbalancer/templates/haproxyConfig.go
  pkg/pipelines/loadbalancer/templates/haproxyManifest.go
  pkg/pipelines/plugins/dns/module.go
  pkg/pipelines/plugins/dns/prepares.go
  pkg/pipelines/plugins/dns/tasks.go
  pkg/pipelines/plugins/dns/templates/coredns_service.go
  pkg/pipelines/plugins/dns/templates/nodelocaldns_configmap.go
  pkg/pipelines/plugins/dns/templates/nodelocaldns_service.go
Labels: approved, size/XXL

#659 Experiment: add NetworkPluginModule(calico)
  pkg/core/action/template.go
  pkg/core/common/common.go
  pkg/core/connector/interface.go
  pkg/core/connector/runtime.go
  pkg/core/pipeline/pipeline.go
  pkg/pipelines/common/common.go
  pkg/pipelines/common/kube_prepare.go
  pkg/pipelines/common/kube_runtime.go
  pkg/pipelines/create_cluster.go
  pkg/pipelines/etcd/module.go
  pkg/pipelines/initialization/tasks.go
  pkg/pipelines/kubernetes/kubernetes_status.go
  pkg/pipelines/kubernetes/module.go
  pkg/pipelines/kubernetes/prepares.go
  pkg/pipelines/kubernetes/tasks.go
  pkg/pipelines/plugins/network/modules.go
  pkg/pipelines/plugins/network/prepares.go
  pkg/pipelines/plugins/network/tasks.go
  pkg/pipelines/plugins/network/templates/calico_v1.16+.go
  pkg/pipelines/plugins/network/templates/calico_v1.16-.go
Labels: approved, size/XXL

#663 Experiment: support more network plugin and modify task result
  pkg/core/ending/task_result.go
  pkg/core/modules/task.go
  pkg/pipelines/plugins/network/modules.go
  pkg/pipelines/plugins/network/tasks.go
  pkg/pipelines/plugins/network/templates/cilium.go
  pkg/pipelines/plugins/network/templates/flannel.go
Labels: approved, size/XXL

#661 fix:create cluster failed when no default router in system
  pkg/kubernetes/master.go
Labels: approved, lgtm, size/XS

#666 fix:create cluster failed on hosts manager by jumpserver
  pkg/kubernetes/config/v1beta2/kubeadm.go
  pkg/kubernetes/master.go
Labels: approved, lgtm, size/S

#667 Experiment: add delete_cluster pipeline and modify some design
  cmd/cluster.go
  cmd/delete_cluster.go
  pkg/core/common/common.go
  pkg/core/connector/interface.go
  pkg/core/connector/runtime.go
  pkg/core/connector/ssh.go
  pkg/core/logger/logger.go
  pkg/core/pipeline/pipeline.go
  pkg/core/render/render.go
  pkg/core/render/render_test.go
  pkg/core/util/file.go
  pkg/pipelines/addons/addons.go
  pkg/pipelines/addons/charts.go
  pkg/pipelines/addons/manifests.go
  pkg/pipelines/addons/module.go
  pkg/pipelines/bootstrap/confirm/module.go
  pkg/pipelines/bootstrap/initialization/const.go
  pkg/pipelines/bootstrap/initialization/module.go
  pkg/pipelines/bootstrap/initialization/tasks.go
  pkg/pipelines/bootstrap/os/module.go
  pkg/pipelines/bootstrap/os/tasks.go
  pkg/pipelines/bootstrap/os/templates/init_script.go
  pkg/pipelines/common/kube_runtime.go
  pkg/pipelines/common/loader.go
  pkg/pipelines/create_cluster.go
  pkg/pipelines/delete_cluster.go
  pkg/pipelines/kubernetes/module.go
  pkg/pipelines/kubernetes/tasks.go
Labels: approved, size/XXL

#606 Add support for flannel vxlan+Directrouting
  apis/kubekey/v1alpha1/network_types.go
  pkg/plugins/network/flannel/tmpl.go
Labels: approved, lgtm, size/S

#657 Supports installing docker and conatinerd using binaries
  apis/kubekey/v1alpha1/default.go
  cmd/add_nodes.go
  cmd/cluster.go
  cmd/root.go
  docs/kubernetes-versions.md
  go.sum
  pkg/bootstrap/dependencies/init.go
  pkg/bootstrap/dependencies/os.go
  pkg/bootstrap/registry/registry.go
  pkg/cluster/add/add.go
  pkg/cluster/certs/cert.go
  pkg/cluster/delete/delete.go
  pkg/cluster/install/install.go
  pkg/cluster/install/tasks.go
  pkg/cluster/upgrade/kubernetes.go
  pkg/cluster/upgrade/precheck.go
  pkg/cluster/upgrade/upgrade.go
  pkg/config/generate.go
  pkg/container-engine/container.go
  pkg/container-engine/containerd.go
  pkg/container-engine/docker.go
  pkg/container-engine/docker/docker.go
  pkg/files/file.go
  pkg/kubernetes/config/v1beta2/kubeadm.go
  pkg/kubernetes/master.go
  pkg/kubernetes/nodes.go
  pkg/kubernetes/preinstall/preinstall.go
  pkg/kubernetes/preinstall/prepull_images.go
  pkg/util/executor/executor.go
  pkg/util/manager/manager.go
  pkg/util/util.go
  version/k8s.go
Labels: approved, lgtm, size/XXL

#670 Experiment：add init dependencies pipeline
  cmd/init_os.go
  pkg/core/action/base.go
  pkg/core/config/const.go
  pkg/core/config/loader.go
  pkg/core/config/nodeConfig.go
  pkg/core/config/runtime.go
  pkg/core/connector/host.go
  pkg/core/connector/interface.go
  pkg/core/modules/base.go
  pkg/core/modules/interface.go
  pkg/core/modules/task.go
  pkg/core/modules/task_module.go
  pkg/core/prepare/base.go
  pkg/pipelines/binaries/kubernetes.go
  pkg/pipelines/binaries/module.go
  pkg/pipelines/bootstrap/confirm/module.go
  pkg/pipelines/bootstrap/os/common.go
  pkg/pipelines/bootstrap/os/module.go
  pkg/pipelines/bootstrap/os/tasks.go
  pkg/pipelines/bootstrap/precheck/const.go
  pkg/pipelines/bootstrap/precheck/module.go
  pkg/pipelines/bootstrap/precheck/tasks.go
  pkg/pipelines/common/common.go
  pkg/pipelines/common/kube_runtime.go
  pkg/pipelines/create_cluster.go
  pkg/pipelines/etcd/module.go
  pkg/pipelines/etcd/prepares.go
  pkg/pipelines/etcd/tasks.go
  pkg/pipelines/init_dependencies.go
  pkg/pipelines/kubernetes/module.go
  pkg/pipelines/kubernetes/prepares.go
  pkg/pipelines/kubernetes/tasks.go
  pkg/pipelines/loadbalancer/common.go
  pkg/pipelines/loadbalancer/module.go
  pkg/pipelines/loadbalancer/tasks.go
Labels: approved, size/XXL

#672 Experiment: go mod tidy
  go.sum
Labels: approved, size/M

#673 Experiment: move logo to pipeline init function
  cmd/cluster.go
  pkg/core/pipeline/pipeline.go
Labels: approved, size/S

#674 fix: localAPIEndpoint of each master is set to master1's address
  pkg/kubernetes/config/v1beta2/kubeadm.go
Labels: approved, lgtm, size/XS

#675 Experiment: sync master branch latest k8s installation process
  pkg/core/util/util.go
  pkg/pipelines/binaries/kubernetes.go
  pkg/pipelines/common/common.go
  pkg/pipelines/create_cluster.go
  pkg/pipelines/kubernetes/kubernetes_status.go
  pkg/pipelines/kubernetes/module.go
  pkg/pipelines/kubernetes/prepares.go
  pkg/pipelines/kubernetes/tasks.go
  pkg/pipelines/kubernetes/templates/v1beta2/kubeadm_config.go
Labels: approved, size/L

#677 Experiment: sync master branch latest ContainerRuntimeEndpoint config
  apis/kubekey/v1alpha1/default.go
  pkg/core/util/util.go
  pkg/pipelines/common/common.go
  pkg/pipelines/images/tasks.go
  pkg/pipelines/kubernetes/tasks.go
Labels: approved, size/M

#676 fix: if the node is exist in cluster that will not pull images
  pkg/kubernetes/preinstall/prepull_images.go
Labels: approved, lgtm, size/M

#678 Experiment: sync master branch latest container install process
  apis/kubekey/v1alpha1/default.go
  pkg/pipelines/common/common.go
  pkg/pipelines/container/containerd.go
  pkg/pipelines/container/docker.go
  pkg/pipelines/container/module.go
  pkg/pipelines/container/prepares.go
  pkg/pipelines/container/templates/containerd_config.go
  pkg/pipelines/container/templates/containerd_service.go
  pkg/pipelines/container/templates/crictl_config.go
  pkg/pipelines/container/templates/docker_config.go
  pkg/pipelines/container/templates/docker_service.go
  pkg/pipelines/continer/docker/module.go
  pkg/pipelines/continer/docker/tasks.go
  pkg/pipelines/create_cluster.go
Labels: approved, size/XL

#679 Experiment: add AddNodesPipeline
  cmd/add_nodes.go
  pkg/pipelines/add_nodes.go
Labels: approved, size/M

#680 Experiment: add DeleteNodePipeline
  cmd/delete_node.go
  pkg/core/connector/interface.go
  pkg/core/connector/runtime.go
  pkg/pipelines/bootstrap/config/module.go
  pkg/pipelines/bootstrap/confirm/module.go
  pkg/pipelines/common/kube_runtime.go
  pkg/pipelines/delete_node.go
  pkg/pipelines/kubernetes/module.go
  pkg/pipelines/kubernetes/tasks.go
Labels: approved, size/L

#682 Support Kubernetes v1.21.5
  README.md
  README_zh-CN.md
  apis/kubekey/v1alpha1/default.go
  docs/kubernetes-versions.md
  pkg/files/file.go
  version/k8s.go
Labels: approved, lgtm, size/S

#684 Support KubeSphere v3.2.0
  cmd/cluster.go
  cmd/upgrade.go
  pkg/cluster/upgrade/kubernetes.go
  pkg/cluster/upgrade/precheck.go
  pkg/cluster/upgrade/upgrade.go
  pkg/config/generate.go
  pkg/config/parse.go
  pkg/kubesphere/kubesphere.go
  pkg/kubesphere/manifests.go
  pkg/kubesphere/templates.go
Labels: approved, lgtm, size/XL

#685 Release 1.2.0-alpha.4
  README.md
  README_zh-CN.md
  apis/kubekey/v1alpha1/default.go
  apis/kubekey/v1alpha1/network_types.go
  cmd/add_nodes.go
  cmd/cluster.go
  cmd/root.go
  cmd/upgrade.go
  docs/kubernetes-versions.md
  go.sum
  pkg/bootstrap/dependencies/init.go
  pkg/bootstrap/dependencies/os.go
  pkg/bootstrap/registry/registry.go
  pkg/cluster/add/add.go
  pkg/cluster/certs/cert.go
  pkg/cluster/delete/delete.go
  pkg/cluster/install/install.go
  pkg/cluster/install/tasks.go
  pkg/cluster/upgrade/kubernetes.go
  pkg/cluster/upgrade/precheck.go
  pkg/cluster/upgrade/upgrade.go
  pkg/config/generate.go
  pkg/config/parse.go
  pkg/container-engine/container.go
  pkg/container-engine/containerd.go
  pkg/container-engine/docker.go
  pkg/container-engine/docker/docker.go
  pkg/files/file.go
  pkg/kubernetes/config/v1beta2/kubeadm.go
  pkg/kubernetes/master.go
  pkg/kubernetes/nodes.go
  pkg/kubernetes/preinstall/preinstall.go
  pkg/kubernetes/preinstall/prepull_images.go
  pkg/kubesphere/kubesphere.go
  pkg/kubesphere/manifests.go
  pkg/kubesphere/templates.go
  pkg/plugins/network/flannel/tmpl.go
  pkg/util/executor/executor.go
  pkg/util/manager/manager.go
  pkg/util/util.go
  version/k8s.go
Labels: approved, lgtm, size/XXL

#688 Experiment: add pipelines that about certificates
  cmd/list_cert.go
  cmd/renew_cert.go
  pkg/cluster/install/install_test.go
  pkg/pipelines/certs/module.go
  pkg/pipelines/certs/tasks.go
  pkg/pipelines/check_certs.go
  pkg/pipelines/common/common.go
  pkg/pipelines/common/loader.go
  pkg/pipelines/renew_certs.go
Labels: approved, size/XL

#691 Experiment: renew certs support k8s version > v1.20.0
  pkg/pipelines/certs/tasks.go
Labels: approved, size/M

#690 fix: renew certs support k8s version > v1.20.0
  pkg/cluster/certs/cert.go
Labels: approved, lgtm, size/M

#694 github ci upgrade go 1.16
  .github/workflows/ci.yml
  .github/workflows/release.yaml
Labels: approved, lgtm, size/S

#696 dev v2.0.0 sync master
  .all-contributorsrc
  .github/workflows/ci.yml
  .github/workflows/release.yaml
  CONTRIBUTORS.md
  README.md
  README_zh-CN.md
  apis/kubekey/v1alpha1/default.go
  cmd/cluster.go
  cmd/upgrade.go
  docs/kubernetes-versions.md
  pkg/cluster/certs/cert.go
  pkg/cluster/upgrade/kubernetes.go
  pkg/cluster/upgrade/precheck.go
  pkg/cluster/upgrade/upgrade.go
  pkg/config/generate.go
  pkg/config/parse.go
  pkg/files/file.go
  pkg/kubernetes/config/v1beta2/kubeadm.go
  pkg/kubernetes/preinstall/prepull_images.go
  pkg/kubesphere/kubesphere.go
  pkg/kubesphere/manifests.go
  pkg/kubesphere/templates.go
  version/k8s.go
Labels: approved, size/XXL

#695 dockerfile build from golang:1.16
  .github/workflows/ci.yml
  .github/workflows/release.yaml
  Dockerfile
  Makefile
  build.sh
Labels: approved, lgtm, size/S

#697 dev-v2.0.0: Add UpgradeClusterPipeline
  cmd/upgrade.go
  pkg/core/cache/cache.go
  pkg/core/common/common.go
  pkg/core/modules/interface.go
  pkg/core/modules/local_task.go
  pkg/core/modules/task.go
  pkg/core/modules/task_module.go
  pkg/core/modules/task_test.go
  pkg/core/util/util.go
  pkg/pipelines/binaries/module.go
  pkg/pipelines/binaries/tasks.go
  pkg/pipelines/bootstrap/confirm/module.go
  pkg/pipelines/bootstrap/os/module.go
  pkg/pipelines/bootstrap/precheck/dependency_matrix.go
  pkg/pipelines/bootstrap/precheck/module.go
  pkg/pipelines/bootstrap/precheck/prepares.go
  pkg/pipelines/bootstrap/precheck/tasks.go
  pkg/pipelines/certs/module.go
  pkg/pipelines/common/common.go
  pkg/pipelines/container/module.go
  pkg/pipelines/etcd/module.go
  pkg/pipelines/images/module.go
  pkg/pipelines/kubernetes/module.go
  pkg/pipelines/kubernetes/prepares.go
  pkg/pipelines/kubernetes/tasks.go
  pkg/pipelines/kubernetes/upgrade_step_enum.go
  pkg/pipelines/loadbalancer/module.go
  pkg/pipelines/plugins/dns/module.go
  pkg/pipelines/plugins/network/modules.go
  pkg/pipelines/upgrade_cluster.go
Labels: approved, size/XXL

#699 upgrade ks-installer manifest
  pkg/kubesphere/manifests.go
Labels: approved, lgtm, size/S

#701 modify git fetch depth
  .github/workflows/ci.yml
  .github/workflows/release.yaml
Labels: approved, lgtm, size/XS
