Repository kubesphere/kubekey, pull requests merged in 2021-06, with the labels that each got.

#547 Set Etcdendpoint to local node instead of all etcd members in etcd-backup.sh
  pkg/etcd/tmpl/etcdbackup.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#549 match image's registry
  controllers/kubekey/cluster_controller.go
Labels: approved, dco-signoff: yes, size/S

#550 support kubernetes v1.20.6
  docs/kubernetes-versions.md
  pkg/files/file.go
  version/k8s.go
Labels: approved, dco-signoff: yes, size/XS

#554 Fix: modified the timer in run_task.go
  pkg/util/manager/run_task.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#558 fix: quotation marks change to the english
  docs/turn-off-SELinux_zh-CN.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#564 fix: modify the shell scripts
  scripts/downloadKubekey.sh
Labels: dco-signoff: yes, size/S
