Repository kubesphere/kubekey, pull requests merged in 2021-07, with the labels that each got.

#568 Upgrade openebs to 2.10.1
  pkg/kubernetes/preinstall/prepull_images.go
  pkg/plugins/storage/local-volume/openebs.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#576 fix: missing APIEndpoints when multiple masters
  pkg/kubernetes/config/v1beta2/kubeadm.go
Labels: approved, dco-signoff: yes, size/XS

#567 Feature: Add internal LB haproxy for kubernetes.
  apis/kubekey/v1alpha1/cluster_types.go
  apis/kubekey/v1alpha1/default.go
  config/crd/bases/kubekey.kubesphere.io_clusters.yaml
  pkg/cluster/add/add.go
  pkg/cluster/install/install.go
  pkg/cluster/install/tasks.go
  pkg/cluster/upgrade/upgrade.go
  pkg/config/from_cluster.go
  pkg/config/generate.go
  pkg/k3s/config/service.go
  pkg/k3s/nodes.go
  pkg/kubernetes/config/v1beta2/kubeadm.go
  pkg/kubernetes/master.go
  pkg/kubernetes/nodes.go
  pkg/kubernetes/preinstall/prepull_images.go
  pkg/loadbalancer/haproxy.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#577 fix: upgrade cluster make kubernetes endpoint change
  pkg/cluster/upgrade/kubernetes.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#579 docs: update kubernetes-versions.md [skip ci]
  docs/kubernetes-versions.md
Labels: approved, dco-signoff: no, lgtm, size/XS

#581 fix: prevent setting lb and internal load balancer at the same time
  apis/kubekey/v1alpha1/default.go
Labels: approved, size/XS

#578 docs: add ha-mode.md
  docs/ha-mode.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#588 fix: #586 use bash to exec set -o pipifail
  pkg/kubernetes/nodes.go
Labels: approved, size/XS

#584 fix: the bug that the config file is different from the original order
  apis/kubekey/v1alpha1/cluster_types.go
  pkg/cluster/add/add.go
  pkg/cluster/install/install.go
  pkg/etcd/etcd.go
  pkg/etcd/tmpl/etcd.go
  pkg/kubernetes/master.go
Labels: approved, lgtm, size/L

#594 Experiment: abstract config interface
  experiment/kubernetes/control-plane/tasks/tasks.go
  experiment/kubernetes/piplines/create.go
  experiment/main.go
  experiment/utils/config/config.go
  experiment/utils/config/loader.go
  experiment/utils/pipline/action.go
  experiment/utils/pipline/ending.go
  experiment/utils/pipline/module.go
  experiment/utils/pipline/pipeline.go
  experiment/utils/pipline/pipline.go
  experiment/utils/pipline/prepare.go
  experiment/utils/pipline/status_enum.go
  experiment/utils/pipline/task.go
  experiment/utils/pipline/vars.go
  experiment/utils/render/render.go
  experiment/utils/render/render_test.go
Labels: approved
