Repository kubesphere/kubekey, pull requests merged in 2022-07, with the labels that each got.

#1366 Upgrade calico and set the default veth_mtu to 0
  apis/kubekey/v1alpha2/default.go
  docs/config-example.md
  pkg/plugins/network/templates/calico_v1.16+.go
Labels: approved, kind/feature, lgtm, size/XL

#1371 fix: GreetingModule sometimes occurs a timeout error
  apis/kubekey/v1alpha2/default.go
  pkg/bootstrap/precheck/module.go
  pkg/core/task/local_task.go
  pkg/core/task/remote_task.go
  pkg/core/util/time.go
  pkg/core/util/time_test.go
Labels: approved, kind/bug, lgtm, size/L

#1370 update cilium to v1.11.6
  apis/kubekey/v1alpha2/default.go
  apis/kubekey/v1alpha2/kubernetes_types.go
  pkg/common/kube_prepare.go
  pkg/images/tasks.go
  pkg/kubernetes/tasks.go
  pkg/loadbalancer/module.go
  pkg/plugins/network/cilium-1.11.6.tgz
  pkg/plugins/network/modules.go
  pkg/plugins/network/tasks.go
Labels: approved, kind/feature, lgtm, size/L

#1384 update supported kubernetes versions
  README.md
  README_zh-CN.md
Labels: approved, kind/documentation, lgtm, size/S

#1391 [#1390] fix kk bash completion doc
  docs/kubekey-autocompletion.md
Labels: approved, kind/documentation, lgtm, size/XS

#1394 fix：remove GreetingModule that is in the ArtifactPipeline
  pkg/pipelines/artifact_export.go
Labels: approved, lgtm, size/XS

#1397 default enable kernel cpu and memory accounting
  pkg/kubernetes/templates/kubelet_service.go
Labels: approved, kind/feature, lgtm, size/XS

#1396 feat: support k8s and kubesphere version without "v"
  pkg/common/loader.go
Labels: approved, kind/feature, lgtm, size/M, tide/merge-method-squash

#1375 support docker's data-root config
  apis/kubekey/v1alpha2/cluster_types.go
  pkg/container/module.go
  pkg/container/templates/docker_config.go
  pkg/kubernetes/module.go
  pkg/kubernetes/tasks.go
  pkg/kubernetes/templates/v1beta2/kubeadm_config.go
Labels: approved, lgtm, size/S

#1400 fix: etcd backup service does not work
  pkg/etcd/module.go
  pkg/etcd/tasks.go
  pkg/etcd/templates/backup_script.go
  pkg/etcd/templates/backup_service.go
  pkg/etcd/templates/backup_service_test.go
Labels: approved, kind/bug, lgtm, size/L

#1402 fix: check linux package manager error
  pkg/bootstrap/os/tasks.go
Labels: approved, kind/bug, lgtm, size/S

#1404 upgrade OpenEBS to 3.3.0
  pkg/images/tasks.go
  pkg/plugins/storage/templates/openebs.go
Labels: approved, kind/feature, lgtm, size/XS

#1407 [#1406] support for recent k8s patch versions
  README.md
  README_zh-CN.md
  apis/kubekey/v1alpha2/default.go
  docs/kubernetes-versions.md
  pkg/files/file.go
  pkg/version/kubernetes/version_enum.go
Labels: approved, kind/api-change, kind/feature, lgtm, size/M

#1409 [#1408] add fetch-kubernetes-hash script
  hack/fetch-kubernetes-hash.sh
Labels: approved, kind/feature, lgtm, size/M
