Repository kubesphere/kubekey, pull requests merged in 2022-09, with the labels that each got.

#1492 support kubernetes v1.23.10
  README.md
  README_zh-CN.md
  apis/kubekey/v1alpha2/default.go
  docs/kubernetes-versions.md
  hack/fetch-kubernetes-hash.sh
  pkg/files/file.go
  pkg/version/kubernetes/version_enum.go
Labels: approved, kind/feature, lgtm, size/S

#1496 Clean up the vip when delete cluster or nodes
  pkg/loadbalancer/module.go
  pkg/loadbalancer/tasks.go
Labels: approved, kind/feature, lgtm, size/S

#1493 Using Jenkins Pipeline to replace GitHub Actions
  .github/Jenkinsfile
Labels: approved, lgtm, size/M

#1500 fix delete VIP skip bug
  pkg/loadbalancer/module.go
Labels: approved, kind/bug, lgtm, size/XS

#1501 fix: failed to add labels to nodes
  pkg/kubernetes/module.go
  pkg/kubernetes/tasks.go
Labels: approved, kind/bug, lgtm, size/XS

#1499 support kubernetes v1.21.14
  README.md
  README_zh-CN.md
  docs/kubernetes-versions.md
  exp/cluster-api-provider-kubekey/pkg/service/operation/file/checksum/internal_checksum.go
  pkg/files/file.go
  pkg/version/kubernetes/version_enum.go
Labels: approved, kind/feature, lgtm, size/L

#1502 feat: auto generate k3s registries.yaml
  pkg/k3s/module.go
  pkg/k3s/prepares.go
  pkg/k3s/tasks.go
  pkg/k3s/templates/k3sRegistryConfig.go
  pkg/kubernetes/templates/v1beta2/kubeadm_config.go
  pkg/registry/k3s_registries.go
  pkg/utils/util.go
Labels: approved, kind/feature, lgtm, size/L

#1503 fix: registry node missing certs file
  pkg/bootstrap/registry/module.go
Labels: approved, kind/bug, lgtm, size/XS

#1507 fix #1506: update k8s-certs-renew.timer to run each monday of every week
  pkg/certs/templates/certs_renew_service.go
Labels: approved, lgtm, size/XS

#1508 fix get interface bug
  pkg/loadbalancer/tasks.go
Labels: approved, kind/bug, lgtm, size/XS

#1505 Add security enhancement command when create a cluster or add nodes
  cmd/ctl/create/cluster.go
  pkg/common/kube_runtime.go
  pkg/kubernetes/module.go
  pkg/kubernetes/tasks.go
  pkg/kubernetes/templates/v1beta2/kubeadm_config.go
  pkg/pipelines/create_cluster.go
Labels: approved, kind/feature, lgtm, size/L

#1525 Update Kube-ovn to 1.10.6
  apis/kubekey/v1alpha1/default.go
  apis/kubekey/v1alpha2/default.go
  pkg/plugins/network/modules.go
  pkg/plugins/network/tasks.go
  pkg/plugins/network/templates/kubectl_ko.go
  pkg/plugins/network/templates/kubeovn.go
Labels: approved, kind/feature, lgtm, size/L

#1524 feat: Add rpms and debs support.
  apis/kubekey/v1alpha1/groupversion_info.go
  apis/kubekey/v1alpha2/cluster_types.go
  apis/kubekey/v1alpha2/groupversion_info.go
  cmd/ctl/create/cluster.go
  pkg/bootstrap/os/repository/repository_deb.go
  pkg/bootstrap/os/repository/repository_rpm.go
  pkg/bootstrap/os/tasks.go
Labels: approved, kind/feature, lgtm, size/M

#1527 Add kubelet pod pid limit
  apis/kubekey/v1alpha2/default.go
  apis/kubekey/v1alpha2/kubernetes_types.go
  docs/config-example.md
  pkg/kubernetes/templates/v1beta2/kubeadm_config.go
Labels: approved, kind/feature, lgtm, size/S

#1529 docs: Update config-example.md
  docs/config-example.md
Labels: approved, kind/documentation, lgtm, size/XS

#1531 fix: remove "SupportPodPidsLimit" Feature Gate configuration
  pkg/kubernetes/templates/v1beta2/kubeadm_config.go
Labels: approved, lgtm, size/XS

#1519 add migrate_cri
  cmd/ctl/cri/cri.go
  cmd/ctl/cri/migrate_cri.go
  cmd/ctl/root.go
  docs/commands/kk-cri-migrate.md
  pkg/binaries/kubernetes.go
  pkg/binaries/module.go
  pkg/binaries/tasks.go
  pkg/bootstrap/confirm/module.go
  pkg/bootstrap/confirm/tasks.go
  pkg/common/kube_runtime.go
  pkg/container/containerd.go
  pkg/container/module.go
  pkg/pipelines/migrate_container.go
Labels: approved, lgtm, size/XL
