Repository kubesphere/kubekey, pull requests merged in 2022-12, with the labels that each got.

#1646 fix: a sha256 checking bug when downloading different versions of binary files
  pkg/service/operation/file/containerd.go
  pkg/service/operation/file/crictl.go
  pkg/service/operation/file/docker.go
  pkg/service/operation/file/k3s.go
  pkg/service/operation/file/kubeadm.go
  pkg/service/operation/file/kubecni.go
  pkg/service/operation/file/kubectl.go
  pkg/service/operation/file/kubelet.go
  pkg/service/operation/file/runc.go
Labels: approved, kind/bug, lgtm, size/S

#1650 Auto synchronize artifacts to OSS
  .github/workflows/kubernetes-auto-support.yaml
  .github/workflows/release.yaml
Labels: approved, kind/cleanup, lgtm, size/S

#1655 remove --force for qsctl
  hack/sync-components.sh
Labels: approved, kind/cleanup, lgtm, size/S

#1653 cleanup(kk): remove greeting module
  cmd/kk/cmd/artifact/images/push.go
Labels: approved, kind/cleanup, lgtm, size/XS

#1667 fix(kk): handle the duplicate image name which in the kk artifact
  cmd/kk/pkg/images/tasks.go
Labels: approved, kind/bug, lgtm, size/S

#1675 feat(capkk): add status to support autoscaling from zero operations
  api/v1beta1/kkmachinetemplate_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_kkmachinetemplates.yaml
Labels: approved, kind/feature, lgtm, size/M
