Repository kubesphere/kubekey, pull requests merged in 2022-11, with the labels that each got.

#1575 fix log print wrong message
  pkg/service/binary/k3s/binary.go
  pkg/service/binary/kubernetes/binary.go
  pkg/service/containermanager/containerd.go
  pkg/service/containermanager/docker.go
  pkg/service/repository/repository.go
  pkg/service/util/downloader.go
Labels: approved, kind/bug, lgtm, size/M

#1567 Feat: add k3s container runtime config
  cmd/kk/pkg/k3s/tasks.go
  cmd/kk/pkg/k3s/templates/k3sService.go
Labels: approved, kind/feature, lgtm, size/M

#1576 fix the bug generating two release pages
  .github/workflows/ci.yml
  .github/workflows/gen-repository-iso.yaml
Labels: approved, kind/bug, lgtm, size/S

#1577 Support more Kubernetes and k3s version
  cmd/kk/pkg/files/file.go
  cmd/kk/pkg/version/kubernetes/version_enum.go
  docs/k3s-versions.md
  docs/kubernetes-versions.md
  hack/fetch-kubernetes-hash.sh
  pkg/service/operation/file/checksum/internal_checksum.go
Labels: approved, kind/feature, lgtm, size/L

#1578 K3sControlPlane adds a scale subresource and additional printer columns
  cmd/kk/pkg/files/file.go
  cmd/kk/pkg/version/kubernetes/version_enum.go
  controlplane/k3s/api/v1beta1/k3scontrolplane_types.go
  controlplane/k3s/config/crd/bases/controlplane.cluster.x-k8s.io_k3scontrolplanes.yaml
  docs/kubernetes-versions.md
  pkg/service/operation/file/checksum/internal_checksum.go
Labels: approved, kind/feature, lgtm, size/M

#1583 fix set components yaml image name error
  Makefile
Labels: approved, kind/bug, lgtm, size/XS

#1586 docs: update README [skip ci]
  README.md
  README_zh-CN.md
Labels: approved, lgtm, size/S

#1580 docs: add versions of default plugins and components used by kubekey
  docs/components-versions.md
Labels: approved, kind/documentation, lgtm, size/S

#1587 doc:Update kubernetes-version.md
  docs/kubernetes-versions.md
Labels: approved, kind/documentation, lgtm, size/XS

#1588 doc:Update README.md
  README.md
  README_zh-CN.md
Labels: approved, kind/documentation, lgtm, size/XS

#1594 fix some feature-gates removed in k8s v1.25.x
  cmd/kk/pkg/bootstrap/confirm/tasks.go
  cmd/kk/pkg/images/tasks.go
  cmd/kk/pkg/kubernetes/tasks.go
  cmd/kk/pkg/kubernetes/templates/v1beta2/kubeadm_config.go
  cmd/kk/pkg/pipelines/add_nodes.go
  cmd/kk/pkg/pipelines/create_cluster.go
Labels: approved, kind/bug, lgtm, size/M

#1585 modify cluster-template.yaml
  templates/cluster-template.yaml
Labels: approved, kind/bug, lgtm, size/XS

#1595 fix the image name parsing panic
  cmd/kk/pkg/images/tasks.go
  cmd/kk/pkg/images/utils.go
Labels: approved, kind/bug, lgtm, size/S

#1597 print a warning log about download harbor arm64
  cmd/kk/pkg/binaries/registry.go
  cmd/kk/pkg/files/file.go
Labels: approved, kind/bug, lgtm, size/S

#1599 auto add kubernetes version
  .github/workflows/kubernetes-auto-support.yaml
  .gitignore
  Makefile
  cmd/kk/pkg/files/file.go
  docs/kubernetes-versions.md
  hack/auto-update-version.py
  hack/sync-components.sh
  pkg/service/operation/file/checksum/internal_checksum.go
  version/components.json
  version/version.go
Labels: approved, kind/cleanup, lgtm, size/XXL

#1601 fix the panic of parsing os release.
  bootstrap/k3s/PROJECT
  cmd/kk/pkg/bootstrap/os/tasks.go
  controlplane/k3s/PROJECT
  go.mod
  go.sum
  pkg/service/operation/file/repositoryISO.go
  pkg/service/operation/repository/service.go
  pkg/service/repository/repository.go
  pkg/service/repository/service.go
  util/osrelease/osrelease.go
  util/osrelease/osrelease_test.go
  util/osrelease/test/centos7
  util/osrelease/test/rhel7
  util/osrelease/test/ubuntu1804
  util/osrelease/test/ubuntu2004
  util/osrelease/test/ubuntu2204
Labels: approved, kind/bug, lgtm, size/S

#1609 Auto generate support versions list
  cmd/kk/pkg/version/kubernetes/version_enum.go
Labels: approved, kind/cleanup, lgtm, size/M

#1602 fix wrong path in go build ldflags
  hack/version.sh
Labels: approved, kind/bug, lgtm, size/XS

#1612 move cri command to alpha
  cmd/kk/cmd/alpha/alpha.go
  cmd/kk/cmd/alpha/cri/cri.go
  cmd/kk/cmd/alpha/cri/migrate_cri.go
  cmd/kk/cmd/root.go
Labels: approved, kind/api-change, kind/cleanup, lgtm, size/S

#1615 fix the field difference between yaml and json
  cmd/kk/apis/kubekey/v1alpha2/cluster_types.go
Labels: approved, kind/bug, lgtm, size/XS

#1618 [release-2.3] Fix etcd script to delete other files when there is no space left on device
  apis/kubekey/v1alpha2/default.go
  pkg/bootstrap/os/tasks.go
  pkg/etcd/tasks.go
  pkg/etcd/templates/backup_script.go
  pkg/etcd/templates/backup_service.go
Labels: approved, kind/bug, lgtm, size/S

#1619 [release-2.2] Fix etcd script to delete other files when there is no space left on device
  apis/kubekey/v1alpha2/default.go
  pkg/bootstrap/os/tasks.go
  pkg/etcd/tasks.go
  pkg/etcd/templates/backup_script.go
  pkg/etcd/templates/backup_service.go
Labels: approved, kind/bug, lgtm, size/S

#1620 [release-2.1] Fix etcd script to delete other files when there is no space left on device
  apis/kubekey/v1alpha2/default.go
  pkg/bootstrap/os/tasks.go
  pkg/etcd/tasks.go
  pkg/etcd/templates/backup_script.go
Labels: approved, kind/bug, lgtm, size/S

#1621 [release-2.0] Fix etcd script to delete other files when there is no space left on device
  apis/kubekey/v1alpha2/default.go
  pkg/bootstrap/os/tasks.go
  pkg/etcd/tasks.go
  pkg/etcd/templates/backup_script.go
Labels: approved, kind/bug, lgtm, size/M

#1622 [release-1.2] Fix etcd script to delete other files when there is no space left on device
  apis/kubekey/v1alpha1/default.go
  pkg/cluster/delete/delete.go
  pkg/etcd/tmpl/etcdbackup.go
Labels: approved, kind/bug, size/S

#1623 [release-1.1] Fix etcd script to delete other files when there is no space left on device
  apis/kubekey/v1alpha1/default.go
  pkg/cluster/delete/delete.go
  pkg/etcd/tmpl/etcdbackup.go
Labels: kind/bug, size/S

#1626 feat(capkk): add a field to set up the crictl version
  api/v1beta1/containermanager_types.go
  api/v1beta1/kkmachine_webhook.go
  api/v1beta1/kkmachine_webhook_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_kkinstances.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_kkmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_kkmachinetemplates.yaml
  config/manager/manager.yaml
  pkg/service/containermanager/containerd.go
  pkg/service/containermanager/containerd_test.go
  pkg/service/containermanager/docker.go
  templates/cluster-template.yaml
Labels: approved, kind/feature, lgtm, size/L

#1628 bump k8s.io apiserver to v0.25.4 and bump cluster-api to v1.2.6
  go.mod
  go.sum
Labels: approved, lgtm, size/M, dependencies
