Repository kubesphere/kubekey, pull requests merged in 2022-06, with the labels that each got.

#1309 Add support for building ubuntu 22.04 repository iso
  .github/workflows/gen-repository-iso.yaml
  Makefile
  hack/gen-repository-iso/dockerfile.ubuntu2204
  hack/gen-repository-iso/packages.yaml
Labels: approved, lgtm, size/M

#1307 Add support for missing Kubernetes versions v1.21.0 and up
  docs/kubernetes-versions.md
  pkg/files/file.go
  pkg/version/kubernetes/version_enum.go
Labels: approved, kind/feature, lgtm, size/L

#1315 fix: delete node nil pointer panic
  pkg/bootstrap/config/module.go
  pkg/bootstrap/config/tasks.go
  pkg/bootstrap/os/module.go
  pkg/bootstrap/os/prepares.go
  pkg/bootstrap/os/tasks.go
  pkg/certs/module.go
  pkg/core/connector/runtime.go
  pkg/kubernetes/module.go
  pkg/kubernetes/tasks.go
  pkg/pipelines/delete_node.go
Labels: approved, kind/bug, lgtm, size/L

#1317 Fix: remove kubekey/artifact dir after exporting an artifact
  pkg/artifact/tasks.go
Labels: approved, kind/bug, lgtm, size/S

#1319 feature: AutoRenewCerts is enabled by default for creating an all-in-one cluster
  pkg/common/loader.go
Labels: approved, kind/feature, lgtm, size/S

#1322 fix: remove kubelet pod pid limit
  pkg/kubernetes/templates/v1beta2/kubeadm_config.go
Labels: approved, kind/bug, lgtm, size/S

#1323 feat: show "WARN" and "ERRO" log level
  pkg/core/logger/logger.go
  pkg/core/logger/logger_test.go
Labels: approved, kind/feature, lgtm, size/S

#1324 feat: users can use "y" or "n" when confirming
  pkg/bootstrap/confirm/tasks.go
Labels: approved, kind/feature, lgtm, size/M

#1325 cleanup: remove unused host cache
  pkg/bootstrap/os/common.go
  pkg/bootstrap/os/tasks.go
Labels: approved, kind/cleanup, lgtm, size/S

#1326 feat: add a notice after creating a kubekey file
  pkg/artifact/manifest.go
  pkg/config/generate.go
  pkg/core/pipeline/pipeline.go
Labels: approved, kind/feature, lgtm, size/S

#1328 fix: print combined output when the cp command is executed with an error
  pkg/artifact/tasks.go
Labels: approved, kind/bug, lgtm, size/XS

#1327 doc: modify readme and make k8s v1.23.7 as the default version
  README.md
  apis/kubekey/v1alpha2/default.go
Labels: approved, kind/documentation, lgtm, size/S

#1329 fix: the generated kk config file contains the "containerManager" by default
  README.md
  pkg/config/generate.go
  pkg/config/templates/cluster.go
  pkg/kubernetes/tasks.go
Labels: approved, kind/bug, lgtm, size/M

#1330 fix: replace the "ClearOSEnvironmentModule" in the "DeleteNodePipeline" with the "ClearNodeOSModule"
  pkg/bootstrap/os/module.go
  pkg/bootstrap/os/tasks.go
  pkg/certs/module.go
  pkg/pipelines/delete_node.go
Labels: approved, kind/bug, lgtm, size/M

#1332 doc: modify prompt text
  docs/config-example.md
  pkg/bootstrap/confirm/tasks.go
Labels: approved, kind/documentation, lgtm, size/S

#1334 doc: modify the command flag description
  cmd/ctl/create/config.go
Labels: approved, lgtm, size/XS

#1338 fix: can't upgrade k8s version when ks version does not changed
  pkg/bootstrap/precheck/tasks.go
Labels: approved, kind/bug, lgtm, size/S

#1348 fix: the default cgroup driver wrong configured
  pkg/kubernetes/templates/v1beta2/kubeadm_config.go
Labels: approved, kind/bug, lgtm, size/XS

#1358 cleanup: do not need to exec init_os script when upgrading the k8s cluster
  pkg/pipelines/upgrade_cluster.go
Labels: approved, kind/cleanup, lgtm, size/XS

#1357 cleanup: do not need to generate kubeadm config and kubelet service file when upgrading the k8s cluster
  pkg/kubernetes/tasks.go
  pkg/pipelines/create_cluster.go
Labels: approved, kind/cleanup, lgtm, size/M
