Repository kubesphere/kubekey, pull requests merged in 2022-04, with the labels that each got.

#1163 fix manifest example yaml file indentation problem
  docs/manifest-example.md
Labels: approved, kind/documentation, lgtm, size/XS

#1160 reduce the size of KubeKey artifact
  cmd/ctl/artifact/export.go
  cmd/ctl/artifact/images/push.go
  go.mod
  go.sum
  pkg/artifact/containerd.go
  pkg/artifact/module.go
  pkg/artifact/tasks.go
  pkg/core/cache/cache.go
  pkg/core/pipeline/pipeline.go
  pkg/images/copy.go
  pkg/images/images.go
  pkg/images/images_test.go
  pkg/images/module.go
  pkg/images/tasks.go
  pkg/images/utils.go
  pkg/images/utils_test.go
  pkg/pipelines/artifact_export.go
  pkg/pipelines/create_cluster.go
Labels: approved, kind/api-change, kind/feature, lgtm, size/XXL

#1172 Disable cgo in the build script.
  Makefile
  build.sh
Labels: approved, kind/bug, lgtm, size/XS

#1175 update kk operator to latest
  Dockerfile
  Dockerfile.binaries
  config/default/manager_auth_proxy_patch.yaml
  config/manager/kustomization.yaml
  controllers/kubekey/cluster_controller.go
  go.mod
  manifests/deploy.yaml
Labels: approved, kind/cleanup, lgtm, size/XXL

#1179 support containerd v1.6.2 and separate it from docker
  apis/kubekey/v1alpha2/default.go
  docs/config-example.md
  docs/manifest-example.md
  pkg/artifact/manifest.go
  pkg/artifact/templates/manifest.go
  pkg/binaries/kubernetes.go
  pkg/bootstrap/confirm/tasks.go
  pkg/bootstrap/precheck/const.go
  pkg/bootstrap/precheck/tasks.go
  pkg/bootstrap/registry/module.go
  pkg/common/common.go
  pkg/config/templates/cluster.go
  pkg/container/containerd.go
  pkg/container/docker.go
  pkg/container/module.go
  pkg/container/templates/containerd_config.go
  pkg/container/templates/docker_config.go
  pkg/files/file.go
  pkg/images/tasks.go
  pkg/images/utils.go
  pkg/kubernetes/templates/v1beta2/kubeadm_config.go
  pkg/registry/docker_registry_config.go
Labels: approved, kind/feature, lgtm, size/XL

#1181 fix etcd client certs not found
  pkg/kubesphere/tasks.go
Labels: approved, lgtm, size/XS

#1177 Make kubekey namespace configurable
  cmd/ctl/add/add_nodes.go
  cmd/ctl/create/cluster.go
  cmd/ctl/options/common_options.go
  controllers/kubekey/cluster_controller.go
  controllers/kubekey/update_cluster.go
  main.go
  pkg/common/kube_runtime.go
Labels: approved, kind/feature, lgtm, size/M

#1169 Remove zombie process crontab
  pkg/bootstrap/os/templates/init_script.go
Labels: approved, kind/bug, lgtm, size/XS

#1182 support kubesphere v3.3.0
  pkg/config/generate.go
  pkg/version/kubesphere/ks_installer.go
  pkg/version/kubesphere/templates/cc_v330.go
  pkg/version/kubesphere/version_enum.go
Labels: approved, kind/feature, lgtm, size/L

#1186 bump k8s.io package from v0.23.4 to v0.23.5
  go.mod
  go.sum
Labels: approved, lgtm, size/M, dependencies

#1189 delete auths field
  pkg/config/templates/cluster.go
Labels: approved, kind/cleanup, lgtm, size/XS

#1197 fix sudo not work expected
  pkg/bootstrap/confirm/tasks.go
  pkg/bootstrap/precheck/tasks.go
Labels: approved, kind/bug, lgtm, size/M

#1200 add cc v3.3.0 "zone" and "namespace_override" fields
  pkg/version/kubesphere/templates/cc_v330.go
Labels: approved, kind/bug, lgtm, size/XS

#1185 Optimize the process of build repository iso
  .github/workflows/gen-repository-iso.yaml
  Makefile
  hack/gen-repository-iso/dockerfile.centos7
  hack/gen-repository-iso/dockerfile.debian10
  hack/gen-repository-iso/dockerfile.debian9
  hack/gen-repository-iso/dockerfile.ubuntu1604
  hack/gen-repository-iso/dockerfile.ubuntu1804
  hack/gen-repository-iso/dockerfile.ubuntu2004
  hack/gen-repository-iso/packages.yaml
Labels: approved, lgtm, size/L

#1205 Fix typo in kk-create-config.md
  docs/commands/kk-create-config.md
Labels: approved, kind/documentation, lgtm, size/XS

#1203 add a "timeout" option for the host TCP connection to establish
  apis/kubekey/v1alpha2/cluster_types.go
  apis/kubekey/v1alpha2/default.go
  cmd/ctl/artifact/images/push.go
  go.mod
  go.sum
  pkg/bootstrap/precheck/module.go
  pkg/bootstrap/precheck/tasks.go
  pkg/core/connector/dialer.go
  pkg/core/connector/host.go
  pkg/core/connector/interface.go
  pkg/core/connector/ssh.go
  pkg/core/task/remote_task.go
  pkg/pipelines/add_nodes.go
  pkg/pipelines/artifact_export.go
  pkg/pipelines/check_certs.go
  pkg/pipelines/create_cluster.go
  pkg/pipelines/delete_cluster.go
  pkg/pipelines/delete_node.go
  pkg/pipelines/init_dependencies.go
  pkg/pipelines/init_registry.go
  pkg/pipelines/renew_certs.go
  pkg/pipelines/upgrade_cluster.go
Labels: approved, kind/feature, lgtm, size/L

#1209 remove cri pre-check which is in the ImagesPushPipeline
  cmd/ctl/artifact/images/push.go
  pkg/bootstrap/precheck/module.go
  pkg/bootstrap/precheck/tasks.go
Labels: approved, kind/cleanup, lgtm, size/M

#1220 Fix Rick's info who is myself
  README.md
Labels: approved, kind/cleanup, lgtm, size/XS

#1222 support init os command to use artifact
  cmd/ctl/init/init_os.go
  pkg/artifact/manifest.go
  pkg/bootstrap/os/module.go
  pkg/bootstrap/os/repository/repository.go
  pkg/bootstrap/os/repository/repository_deb.go
  pkg/bootstrap/os/repository/repository_rpm.go
  pkg/bootstrap/os/rollback.go
  pkg/bootstrap/os/tasks.go
  pkg/common/kube_runtime.go
  pkg/pipelines/init_dependencies.go
  pkg/pipelines/init_registry.go
Labels: approved, kind/feature, lgtm, size/L

#1226 fix missing cc field value.
  pkg/version/kubesphere/templates/cc_v330.go
Labels: approved, kind/bug, lgtm, size/XS

#1230 fix centos iso file missing conntrack
  hack/gen-repository-iso/packages.yaml
Labels: approved, kind/bug, lgtm, size/XS

#1235 modify close ssh connect logic
  pkg/core/pipeline/pipeline.go
  pkg/core/task/remote_task.go
Labels: approved, kind/cleanup, lgtm, size/S

#1236 fix: when use docker runtime , the `kk` check cgroup driver wrong at the docker already deployed node
  pkg/kubernetes/templates/v1beta2/kubeadm_config.go
Labels: approved, lgtm, size/S

#1237 add auto-generate local ssh key in "localRuntime"
  pkg/bootstrap/confirm/tasks.go
  pkg/common/local_runtime.go
Labels: approved, kind/cleanup, lgtm, size/S

#1241 Support Kubernetes v1.22.9 and v1.23.6
  docs/kubernetes-versions.md
  pkg/files/file.go
  pkg/version/kubernetes/version_enum.go
Labels: approved, kind/feature, lgtm, size/M

#1242 Fix kernel module br_netfilter missing
  pkg/bootstrap/os/templates/init_script.go
Labels: approved, kind/bug, lgtm, size/XS

#1243 sync certs file to all nodes ssl dir
  pkg/binaries/registry.go
  pkg/bootstrap/registry/module.go
  pkg/bootstrap/registry/tasks.go
Labels: approved, kind/bug, lgtm, size/M

#1249 update artifact doc
  docs/commands/kk-artifact-export.md
  docs/commands/kk-init-os.md
  docs/manifest_and_artifact.md
  docs/zh/manifest_and_artifact.md
Labels: approved, kind/documentation, lgtm, size/S
