Repository kubesphere/kubekey, pull requests merged in 2022-01, with the labels that each got.

#953 fix: fix --debug not print the DEBUG LEVEL LOG
  pkg/core/logger/logger.go
Labels: approved, lgtm, size/S

#956 fix: upgrade cluster apply a wrong and default cc
  pkg/kubesphere/modules.go
  pkg/kubesphere/tasks.go
  pkg/pipelines/upgrade_cluster.go
Labels: approved, lgtm, size/M

#957 fix: upgrade check ks version error
  pkg/bootstrap/precheck/tasks.go
Labels: approved, lgtm, size/XS

#958 fix: report `are the same file` warning message when coping kubeconfig
  pkg/certs/tasks.go
Labels: approved, lgtm, size/M

#963 Add an md5 check function in UnArchiveModule
  pkg/artifact/module.go
  pkg/artifact/prepares.go
  pkg/artifact/tasks.go
Labels: approved, lgtm, size/M

#965 fix: kk will use the wrong binary's path in the multi-arch environment
  pkg/binaries/k3s.go
  pkg/binaries/kubernetes.go
  pkg/binaries/tasks.go
  pkg/container/containerd.go
  pkg/container/docker.go
  pkg/k3s/tasks.go
  pkg/kubernetes/tasks.go
Labels: approved, lgtm, size/S

#960 fix: no matches for kind "ClusterConfiguration" in version "installer…
  pkg/kubesphere/modules.go
Labels: approved, lgtm, size/XS

#955 Creating container images registry is supported
  apis/kubekey/v1alpha2/cluster_types.go
  apis/kubekey/v1alpha2/default.go
  apis/kubekey/v1alpha2/zz_generated.deepcopy.go
  cmd/ctl/init/init.go
  cmd/ctl/init/init_registry.go
  config/crd/bases/kubekey.kubesphere.io_clusters.yaml
  pkg/binaries/module.go
  pkg/binaries/registry.go
  pkg/binaries/tasks.go
  pkg/bootstrap/os/templates/init_script.go
  pkg/bootstrap/registry/certs.go
  pkg/bootstrap/registry/module.go
  pkg/bootstrap/registry/prepares.go
  pkg/bootstrap/registry/tasks.go
  pkg/bootstrap/registry/templates/harbor.go
  pkg/bootstrap/registry/templates/registry.go
  pkg/common/common.go
  pkg/common/kube_runtime.go
  pkg/common/loader.go
  pkg/config/templates/cluster.go
  pkg/container/templates/containerd_config.go
  pkg/etcd/certs.go
  pkg/files/file.go
  pkg/pipelines/add_nodes.go
  pkg/pipelines/init_registry.go
Labels: approved, lgtm, size/XXL

#966 artifact supports to contain registry binaries
  apis/kubekey/v1alpha2/cluster_types.go
  apis/kubekey/v1alpha2/manifest_types.go
  cmd/ctl/add/add_nodes.go
  cmd/ctl/init/init_registry.go
  cmd/ctl/options/common_options.go
  cmd/ctl/upgrade/upgrade.go
  pkg/artifact/tasks.go
  pkg/artifact/templates/manifest.go
  pkg/binaries/k3s.go
  pkg/binaries/kubernetes.go
  pkg/binaries/registry.go
  pkg/binaries/tasks.go
  pkg/config/templates/cluster.go
  pkg/files/file.go
  pkg/images/images.go
  pkg/pipelines/add_nodes.go
  pkg/pipelines/init_registry.go
  pkg/pipelines/upgrade_cluster.go
Labels: approved, lgtm, size/L

#952 fea(#915): support set ntp server and timezone when kk deloy k8s
  apis/kubekey/v1alpha2/cluster_types.go
  apis/kubekey/v1alpha2/default.go
  apis/kubekey/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/kubekey.kubesphere.io_clusters.yaml
  docs/config-example.md
  pkg/bootstrap/confirm/tasks.go
  pkg/bootstrap/os/module.go
  pkg/bootstrap/os/prepares.go
  pkg/bootstrap/os/tasks.go
  pkg/bootstrap/precheck/const.go
  pkg/bootstrap/precheck/tasks.go
Labels: approved, lgtm, size/L

#967 artifact supports pulling images with skipping SSL certificate validation
  pkg/artifact/containerd.go
  pkg/artifact/tasks.go
Labels: approved, lgtm, size/M

#990 Fix: wrong paths of registries' packages
  pkg/binaries/registry.go
  pkg/binaries/tasks.go
  pkg/bootstrap/registry/tasks.go
  pkg/common/common.go
  pkg/files/file.go
  pkg/images/images.go
Labels: approved, lgtm, size/L

#991 artifact supports to archive multi k8s version
  apis/kubekey/v1alpha2/manifest_types.go
  apis/kubekey/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/kubekey.kubesphere.io_clusters.yaml
  config/crd/bases/kubekey.kubesphere.io_manifests.yaml
  pkg/artifact/manifest.go
  pkg/artifact/templates/manifest.go
  pkg/binaries/kubernetes.go
  pkg/binaries/tasks.go
  pkg/pipelines/artifact_export.go
Labels: approved, lgtm

#992 add pod pid limit and pid available
  pkg/bootstrap/os/templates/init_script.go
  pkg/kubernetes/templates/v1beta2/kubeadm_config.go
Labels: approved, lgtm, size/XS

#999 modify MD5 file name and artifact directory tree.
  pkg/artifact/tasks.go
  pkg/bootstrap/os/tasks.go
  pkg/images/tasks.go
Labels: approved, lgtm, size/S

#1003 Support custom dnsDomain for cluster
  apis/kubekey/v1alpha2/cluster_types.go
  apis/kubekey/v1alpha2/default.go
  apis/kubekey/v1alpha2/kubernetes_types.go
  config/crd/bases/kubekey.kubesphere.io_clusters.yaml
  pkg/common/kube_runtime.go
  pkg/kubernetes/tasks.go
  pkg/kubernetes/templates/v1beta2/kubeadm_config.go
  pkg/plugins/dns/tasks.go
  pkg/plugins/dns/templates/nodelocaldns_configmap.go
Labels: approved, lgtm, size/S

#1005 modify workdir directory tree.
  pkg/binaries/k3s.go
  pkg/binaries/kubernetes.go
  pkg/binaries/registry.go
  pkg/binaries/tasks.go
  pkg/bootstrap/registry/tasks.go
  pkg/container/containerd.go
  pkg/container/docker.go
  pkg/etcd/tasks.go
  pkg/files/file.go
  pkg/k3s/tasks.go
  pkg/kubernetes/tasks.go
  pkg/utils/containerruntime/runtime.go
Labels: approved, lgtm, size/XL

#1011 remove yum install yum-utils
  hack/gen-repository-iso/dockerfile.centos7
  hack/gen-repository-iso/dockerfile.ubuntu1604
  hack/gen-repository-iso/dockerfile.ubuntu1804
  hack/gen-repository-iso/dockerfile.ubuntu2004
  hack/gen-repository-iso/download-pkgs.sh
  pkg/bootstrap/os/module.go
  pkg/bootstrap/os/repository/repository_deb.go
  pkg/bootstrap/os/repository/repository_rpm.go
  pkg/bootstrap/os/tasks.go
Labels: approved, lgtm, size/L

#1012 manifest module detects cluster images way by pods
  pkg/artifact/manifest.go
Labels: approved, lgtm, size/M

#1018 The roleGroups field supports to be customized
  apis/kubekey/v1alpha2/cluster_types.go
  apis/kubekey/v1alpha2/default.go
  apis/kubekey/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/kubekey.kubesphere.io_clusters.yaml
  controllers/kubekey/cluster_controller.go
  docs/config-example.md
  pkg/common/kube_action.go
  pkg/common/kube_module.go
  pkg/common/kube_prepare.go
  pkg/common/kube_runtime.go
  pkg/common/loader.go
  pkg/config/templates/cluster.go
  pkg/kubernetes/module.go
Labels: approved, lgtm, size/XL

#1021 Support the ArtifactModule for authorized pull images
  apis/kubekey/v1alpha2/cluster_types.go
  apis/kubekey/v1alpha2/manifest_types.go
  apis/kubekey/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/kubekey.kubesphere.io_manifests.yaml
  pkg/artifact/containerd.go
  pkg/artifact/tasks.go
  pkg/artifact/templates/manifest.go
  pkg/common/artifact_runtime.go
  pkg/images/images.go
Labels: approved, lgtm, size/L

#1010 Support Kata and Node Feature Discovery
  apis/kubekey/v1alpha2/kubernetes_types.go
  apis/kubekey/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/kubekey.kubesphere.io_clusters.yaml
  pkg/images/tasks.go
  pkg/pipelines/create_cluster.go
  pkg/plugins/kata.go
  pkg/plugins/modules.go
  pkg/plugins/nfd.go
Labels: approved, lgtm, size/XXL

#1025 fix logger nil pointer panic
  apis/kubekey/v1alpha2/kubernetes_types.go
  apis/kubekey/v1alpha2/network_types.go
  pkg/common/kube_runtime.go
  pkg/config/templates/cluster.go
  pkg/core/connector/runtime.go
  pkg/core/pipeline/pipeline.go
  pkg/plugins/network/modules.go
Labels: approved, lgtm, size/M

#1034 change field `skip-install-packages` to `with-packages`
  cmd/ctl/add/add_nodes.go
  cmd/ctl/create/cluster.go
  pkg/artifact/tasks.go
  pkg/artifact/templates/manifest.go
  pkg/common/kube_runtime.go
  pkg/images/tasks.go
  pkg/pipelines/add_nodes.go
  pkg/pipelines/create_cluster.go
Labels: approved, lgtm, size/L
