Repository kubesphere/kubekey, pull requests merged in 2022-05, with the labels that each got.

#1255 remove printing fatal log
  pkg/registry/docker_registry_config.go
Labels: approved, kind/cleanup, lgtm, size/XS

#1258 fix: fix docker login failure when auths username or password is empt…
  apis/kubekey/v1alpha2/cluster_types.go
  pkg/container/docker.go
  pkg/images/tasks.go
Labels: approved, kind/bug, lgtm, size/S

#1256 support kubernetes v1.24.0
  apis/kubekey/v1alpha2/default.go
  docs/kubernetes-versions.md
  pkg/files/file.go
  pkg/images/tasks.go
  pkg/kubernetes/tasks.go
  pkg/version/kubernetes/version_enum.go
Labels: approved, kind/feature, lgtm, size/M

#1259 fix "skipTLSVerify" field can not clearly distinguish between skipping TLS verify and using HTTP.
  docs/config-example.md
  docs/manifest-example.md
  pkg/config/templates/cluster.go
  pkg/images/tasks.go
  pkg/registry/docker_registry_config.go
Labels: approved, kind/bug, lgtm, size/S

#1260 add a debug log print in the ssh runner
  pkg/core/connector/runner.go
Labels: approved, kind/feature, lgtm, size/M

#1263 add an option to control k8s certs auto-renew script
  apis/kubekey/v1alpha2/kubernetes_types.go
  docs/config-example.md
  pkg/certs/module.go
  pkg/config/templates/cluster.go
  pkg/pipelines/add_nodes.go
  pkg/pipelines/create_cluster.go
  pkg/pipelines/upgrade_cluster.go
  pkg/version/kubesphere/templates/installer.go
Labels: approved, kind/feature, lgtm, size/S

#1271 fix: fix containerd does not apply insecureRegistries in config.toml
  pkg/container/module.go
  pkg/container/templates/containerd_config.go
Labels: approved, kind/bug, lgtm, size/XS

#1275 feature: support crictl v1.23.0 and v1.24.0, the default crictl versions up to v1.24.0
  apis/kubekey/v1alpha2/default.go
  pkg/files/file.go
Labels: approved, kind/feature, lgtm, size/XS

#1272 Add k8s v1.23 support for KubeSphere
  pkg/version/kubesphere/ks_installer.go
Labels: approved, lgtm, size/XS

#1283 Fix: --with-kubernetes override the configuration of spec.kubernetes
  pkg/bootstrap/confirm/tasks.go
  pkg/common/loader.go
  pkg/images/tasks.go
Labels: approved, kind/bug, lgtm, size/M

#1291 fix: all-in-one mode generate rsa-sha2-512 signature key
  pkg/common/loader.go
  pkg/common/local_runtime.go
Labels: approved, kind/bug, lgtm, size/XS

#1293 fix: change ks-installer label "app=ks-install" to "app=ks-installer"
  pkg/kubesphere/tasks.go
  pkg/pipelines/create_cluster.go
  pkg/version/kubesphere/templates/installer.go
Labels: approved, kind/cleanup, lgtm, size/S

#1294 doc: add a notice when deploying k8s v1.24
  pkg/bootstrap/confirm/tasks.go
  pkg/bootstrap/precheck/tasks.go
  pkg/common/common.go
Labels: approved, kind/documentation, lgtm, size/M

#1302 feature: support harbor automatically start
  pkg/bootstrap/registry/module.go
  pkg/bootstrap/registry/tasks.go
  pkg/bootstrap/registry/templates/harbor.go
Labels: approved, kind/feature, lgtm, size/M
