Repository kubesphere/kubekey, pull requests merged in 2022-08, with the labels that each got.

#1398 feat: add artifact import for phase run
  cmd/ctl/alpha/artifact.go
  cmd/ctl/artifact/artifact.go
  cmd/ctl/root.go
  cmd/ctl/upgrade/phase.go
  cmd/ctl/upgrade/upgrade.go
  pkg/alpha/artifact.go
Labels: approved, kind/feature, lgtm, size/L

#1418 feat: add upgrade binary cmd for cluster
  cmd/ctl/alpha/artifact.go
  cmd/ctl/alpha/binary.go
  cmd/ctl/upgrade/phase.go
  pkg/alpha/artifact/artifact.go
  pkg/alpha/binary/binary.go
  pkg/alpha/binary/modules.go
  pkg/alpha/precheck/modules.go
  pkg/alpha/precheck/task.go
  pkg/common/common.go
Labels: approved, kind/feature, lgtm, size/L

#1425 feat: add images pull cmd for upgrade phase
  cmd/ctl/alpha/images.go
  cmd/ctl/upgrade/phase.go
  pkg/alpha/images/images.go
  pkg/alpha/images/modules.go
  pkg/alpha/precheck/modules.go
Labels: approved, kind/feature, lgtm, size/L

#1412 support recent docker version 20.10.17 as an alternative.
  pkg/files/file.go
Labels: approved, kind/feature, lgtm, size/XS

#1426 fix: delete k3s cluster with kubenetes version
  cmd/ctl/delete/delete_cluster.go
Labels: approved, lgtm, size/XS

#1413 Support kube-vip
  apis/kubekey/v1alpha2/cluster_types.go
  apis/kubekey/v1alpha2/default.go
  docs/config-example.md
  pkg/images/tasks.go
  pkg/loadbalancer/module.go
  pkg/loadbalancer/tasks.go
  pkg/loadbalancer/templates/k3sKubevipManifest.go
  pkg/loadbalancer/templates/kubevipManifest.go
  pkg/pipelines/create_cluster.go
Labels: approved, kind/feature, lgtm, size/L

#1431 fix k3s(v1.21+) add other master nodes bug
  pkg/k3s/tasks.go
  pkg/loadbalancer/module.go
Labels: approved, kind/bug, lgtm, size/S

#1437 fix: fix ubuntu debian chrony bug
  pkg/bootstrap/os/module.go
  pkg/bootstrap/os/tasks.go
Labels: approved, kind/bug, lgtm, size/M

#1430 feat: add master and worker nodes upgrade cmd
  cmd/ctl/alpha/nodes.go
  cmd/ctl/upgrade/phase.go
  pkg/alpha/nodes/modules.go
  pkg/alpha/nodes/nodes.go
  pkg/alpha/precheck/modules.go
  pkg/alpha/precheck/task.go
Labels: approved, kind/feature, lgtm, size/L

#1427 upgrade helm and harbor
  apis/kubekey/v1alpha2/default.go
  pkg/files/file.go
Labels: approved, kind/feature, lgtm, size/XS

#1444 feat: support kubesphere v3.3.1
  pkg/version/kubesphere/ks_installer.go
  pkg/version/kubesphere/templates/cc_v331.go
  pkg/version/kubesphere/version_enum.go
Labels: approved, kind/feature, lgtm, size/L

#1435 [feature] Support clean CRI
  clients/clientset/versioned/fake/register.go
  clients/clientset/versioned/scheme/register.go
  cmd/ctl/delete/delete_cluster.go
  docs/commands/kk-delete-cluster.md
  pkg/common/kube_runtime.go
  pkg/container/containerd.go
  pkg/container/docker.go
  pkg/container/module.go
  pkg/core/util/file.go
  pkg/images/utils.go
  pkg/pipelines/delete_cluster.go
Labels: approved, kind/feature, lgtm, size/L

#1443 docs: add k3s versions support
  README.md
  docs/k3s-versions.md
  docs/kubernetes-versions.md
Labels: approved, kind/documentation, lgtm, size/S

#1450 [bug] add dataRoot configuration support for containerd
  pkg/container/module.go
  pkg/container/templates/containerd_config.go
Labels: approved, kind/bug, lgtm, size/XS

#1451 Update Kube-ovn to 1.10.5
  apis/kubekey/v1alpha2/default.go
  apis/kubekey/v1alpha2/network_types.go
  pkg/plugins/network/modules.go
  pkg/plugins/network/tasks.go
  pkg/plugins/network/templates/kubectl_ko.go
  pkg/plugins/network/templates/kubeovn.go
  pkg/plugins/network/templates/kubeovn_v1.16+.go
  pkg/plugins/network/templates/kubeovn_v1.16-.go
Labels: approved, kind/feature, lgtm, size/XXL

#1456 Stop support for k8s versions lower than 1.19
  docs/kubernetes-versions.md
  pkg/files/file.go
  pkg/version/kubernetes/version_enum.go
Labels: approved, lgtm, size/L

#1461 feat: add ca-certificates in Dockerfile
  exp/cluster-api-provider-kubekey/Dockerfile
  exp/cluster-api-provider-kubekey/pkg/service/operation/file/binary.go
Labels: approved, kind/bug, lgtm, size/S

#1454 fixed #1453 : invalid syntax of /etc/sysctl.conf after executing init os script
  pkg/bootstrap/os/templates/init_script.go
Labels: approved, kind/bug, lgtm, size/XS

#1470 feat: Add support for building AlmaLinux 9.0 repository iso
  .github/workflows/gen-repository-iso.yaml
  hack/gen-repository-iso/dockerfile.almalinux90
  hack/gen-repository-iso/packages.yaml
Labels: approved, lgtm, size/M

#1477 Fix the permission problem of sftp for non-root users.
  exp/cluster-api-provider-kubekey/Makefile
  exp/cluster-api-provider-kubekey/main.go
  exp/cluster-api-provider-kubekey/pkg/clients/ssh/client.go
  exp/cluster-api-provider-kubekey/pkg/service/bootstrap/bootstrap.go
  exp/cluster-api-provider-kubekey/pkg/service/operation/file/binary.go
  exp/cluster-api-provider-kubekey/pkg/service/provisioning/cloudinit/action.go
  exp/cluster-api-provider-kubekey/pkg/util/filesystem/common.go
Labels: approved, kind/bug, lgtm, size/L

#1476 fix: building AlmaLinux 9.0 repository iso
  hack/gen-repository-iso/dockerfile.almalinux90
  hack/gen-repository-iso/packages.yaml
Labels: approved, lgtm, size/S

#1478 Fix the bug that some OS root user cannot find kubeadm.
  exp/cluster-api-provider-kubekey/Dockerfile
  exp/cluster-api-provider-kubekey/controllers/kkinstance_controller_phase.go
  exp/cluster-api-provider-kubekey/pkg/service/binary/binary.go
  exp/cluster-api-provider-kubekey/pkg/service/interface.go
Labels: approved, kind/bug, lgtm, size/M

#1481 feat: support to modify the download url and checksum of the components
  exp/cluster-api-provider-kubekey/api/v1beta1/component_types.go
  exp/cluster-api-provider-kubekey/api/v1beta1/kkcluster_types.go
  exp/cluster-api-provider-kubekey/api/v1beta1/zz_generated.deepcopy.go
  exp/cluster-api-provider-kubekey/config/crd/bases/infrastructure.cluster.x-k8s.io_kkclusters.yaml
  exp/cluster-api-provider-kubekey/config/crd/bases/infrastructure.cluster.x-k8s.io_kkclustertemplates.yaml
  exp/cluster-api-provider-kubekey/pkg/interface.go
  exp/cluster-api-provider-kubekey/pkg/scope/cluster.go
  exp/cluster-api-provider-kubekey/pkg/scope/kkinstance.go
  exp/cluster-api-provider-kubekey/pkg/service/binary/binary.go
  exp/cluster-api-provider-kubekey/pkg/service/containermanager/containerd.go
  exp/cluster-api-provider-kubekey/pkg/service/operation/file/binary.go
  exp/cluster-api-provider-kubekey/pkg/service/operation/file/checksum/string_checksum.go
  exp/cluster-api-provider-kubekey/pkg/service/operation/file/containerd.go
  exp/cluster-api-provider-kubekey/pkg/service/operation/file/crictl.go
  exp/cluster-api-provider-kubekey/pkg/service/operation/file/docker.go
  exp/cluster-api-provider-kubekey/pkg/service/operation/file/kubeadm.go
  exp/cluster-api-provider-kubekey/pkg/service/operation/file/kubecni.go
  exp/cluster-api-provider-kubekey/pkg/service/operation/file/kubectl.go
  exp/cluster-api-provider-kubekey/pkg/service/operation/file/kubelet.go
  exp/cluster-api-provider-kubekey/pkg/service/operation/file/runc.go
  exp/cluster-api-provider-kubekey/pkg/service/operation/interface.go
  exp/cluster-api-provider-kubekey/test/e2e/data/infrastructure-kubekey/v1beta1/bases/cluster-with-kcp.yaml
Labels: approved, kind/feature, lgtm, size/XL

#1467 Support kube-vip BGP mode
  apis/kubekey/v1alpha2/cluster_types.go
  apis/kubekey/v1alpha2/default.go
  pkg/loadbalancer/module.go
  pkg/loadbalancer/tasks.go
  pkg/loadbalancer/templates/k3sKubevipManifest.go
  pkg/loadbalancer/templates/kubevipManifest.go
  pkg/pipelines/delete_cluster.go
  pkg/pipelines/delete_node.go
Labels: approved, kind/feature, lgtm, size/L

#1471 docs:update k8s version and ha-mode related contents
  README.md
  README_zh-CN.md
  docs/ha-mode.md
  docs/img/haproxy.png
  docs/img/kube-vip.png
Labels: approved, lgtm, size/L

#1485 fix: README format issue
  README.md
  README_zh-CN.md
Labels: approved, kind/documentation, lgtm, size/M

#1484 cleanup: modify e2e config template
  exp/cluster-api-provider-kubekey/test/e2e/config/e2e_conf.yaml
  exp/cluster-api-provider-kubekey/test/e2e/data/infrastructure-kubekey/v1beta1/bases/cluster-with-kcp.yaml
  exp/cluster-api-provider-kubekey/test/e2e/quick_start_test.go
Labels: approved, kind/cleanup, lgtm, size/S
