Repository kubesphere/kubekey, pull requests merged in 2022-03, with the labels that each got.

#1102 Remove the login registry task in the installation harbor module
  pkg/bootstrap/registry/module.go
Labels: approved, kind/cleanup, lgtm, size/S

#1106 make push image to support namespace override
  pkg/images/images.go
Labels: approved, kind/bug, lgtm, size/XS

#1112 fix the command missing default kubernetes type
  apis/kubekey/v1alpha2/default.go
  cmd/ctl/upgrade/upgrade.go
  pkg/common/common.go
Labels: approved, kind/bug, lgtm, size/XS

#1113 fix upgrade pipeline logic bug
  pkg/kubesphere/modules.go
  pkg/pipelines/upgrade_cluster.go
Labels: approved, kind/bug, lgtm, size/S

#1118 Fix the error of kubeconfig's permission in non-root user
  .goreleaser.yml
  pkg/k3s/tasks.go
  pkg/kubernetes/tasks.go
Labels: approved, kind/bug, lgtm, size/M

#1101 add manifest and artifact en doc
  cmd/ctl/artifact/artifact.go
  cmd/ctl/artifact/export.go
  cmd/ctl/create/manifest.go
  docs/manifest_and_artifact.md
Labels: approved, kind/documentation, lgtm, size/M

#1121 Update features doc
  README.md
  docs/features.md
  docs/manifest_and_artifact.md
  docs/zh/manifest_and_artifact.md
Labels: approved, kind/documentation, lgtm, size/S

#1132 add kk command doc
  docs/commands/kk-add-nodes.md
  docs/commands/kk-add.md
  docs/commands/kk-artifact-export.md
  docs/commands/kk-artifact-images-push.md
  docs/commands/kk-artifact-images.md
  docs/commands/kk-artifact.md
  docs/commands/kk-certs-check-expiration.md
  docs/commands/kk-certs-renew.md
  docs/commands/kk-certs.md
  docs/commands/kk-completion.md
  docs/commands/kk-create-cluster.md
  docs/commands/kk-create-config.md
  docs/commands/kk-create-manifest.md
  docs/commands/kk-create.md
  docs/commands/kk-delete-cluster.md
  docs/commands/kk-delete-node.md
  docs/commands/kk-delete.md
  docs/commands/kk-init-os.md
  docs/commands/kk-init-registry.md
  docs/commands/kk-init.md
  docs/commands/kk-plugin-list.md
  docs/commands/kk-plugin.md
  docs/commands/kk-upgrade.md
  docs/commands/kk-version.md
  docs/commands/kk.md
Labels: approved, kind/documentation, lgtm, size/XL

#1128 bump k8s.io package to v1.23.4
  apis/kubekey/v1alpha2/cluster_types.go
  go.mod
  go.sum
Labels: approved, lgtm, size/M, dependencies

#1138 update the roadmap
  README.md
  docs/roadmap.md
Labels: approved, kind/documentation, lgtm, size/S

#1142 Support the use of kubeadm to manage etcd and use of existing etcd
  apis/kubekey/v1alpha2/cluster_types.go
  apis/kubekey/v1alpha2/default.go
  apis/kubekey/v1alpha2/etcd_types.go
  apis/kubekey/v1alpha2/kubernetes_types.go
  apis/kubekey/v1alpha2/zz_generated.deepcopy.go
  cmd/ctl/create/cluster.go
  config/crd/bases/kubekey.kubesphere.io_clusters.yaml
  docs/config-example.md
  pkg/bootstrap/os/module.go
  pkg/bootstrap/os/prepares.go
  pkg/bootstrap/os/tasks.go
  pkg/bootstrap/registry/certs.go
  pkg/common/kube_runtime.go
  pkg/core/connector/runtime.go
  pkg/core/module/task_module.go
  pkg/core/task/remote_task.go
  pkg/etcd/certs.go
  pkg/etcd/module.go
  pkg/etcd/tasks.go
  pkg/etcd/templates/backup_script.go
  pkg/images/tasks.go
  pkg/k3s/tasks.go
  pkg/k3s/templates/k3sServiceEnv.go
  pkg/kubernetes/tasks.go
  pkg/kubernetes/templates/v1beta2/kubeadm_config.go
  pkg/kubesphere/tasks.go
  pkg/pipelines/add_nodes.go
  pkg/pipelines/create_cluster.go
  pkg/version/kubesphere/templates/cc_v320.go
  pkg/version/kubesphere/templates/cc_v321.go
Labels: approved, kind/feature, lgtm, size/XL

#1149 Fix #1147: Error in the script used to automatically update certificate in cluster.
  pkg/certs/module.go
Labels: approved, kind/bug, lgtm, size/S

#1152 Fix #1151: Probabilistic panic when create clusters with multiple nodes
  pkg/core/util/util.go
Labels: approved, kind/bug, lgtm, size/S

#1150 add containerManager kata NFD
  docs/config-example.md
Labels: documentation, approved, kind/documentation, lgtm, size/XS

#1144 fix #1051: Best efforts to clear ipvs rules.
  README.md
  README_zh-CN.md
  docs/commands/kk-init-os.md
  pkg/bootstrap/confirm/tasks.go
  pkg/bootstrap/os/repository/repository_deb.go
  pkg/bootstrap/os/repository/repository_rpm.go
  pkg/bootstrap/os/tasks.go
  pkg/bootstrap/precheck/const.go
Labels: approved, kind/bug, lgtm, size/S

#1072 Initialize choose container runtime
  README_zh-CN.md
Labels: approved, kind/documentation, lgtm, size/XS

#1158 add a build flag "containers_image_openpgp"
  .github/workflows/ci.yml
  .goreleaser.yml
  Makefile
  build.sh
Labels: approved, lgtm, size/M, dependencies

#1164 fix containerd registry authorization failed
  pkg/container/templates/containerd_config.go
Labels: approved, kind/bug, lgtm, size/XS
