Repository kubesphere/kubekey, pull requests merged in 2022-02, with the labels that each got.

#1037 update README and LOGO
  README.md
  docs/developer-guide.md
  docs/img/KubeKey-Architecture.png
  docs/img/kubekey-logo.svg
  docs/img/kubekey.svg
  docs/img/kukekey-logo.png
Labels: approved, lgtm, size/M

#1042 bump viper, cobra and golang-set
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#1046 bump k8s.io package
  go.mod
  go.sum
Labels: approved, lgtm, size/M, dependencies

#1048 fix a bug that "--with-local-storage" flag didn't work
  apis/kubekey/v1alpha2/zz_generated.deepcopy.go
  cmd/ctl/create/cluster.go
  pkg/common/kube_runtime.go
  pkg/pipelines/create_cluster.go
Labels: approved, lgtm, size/M

#1050 add namespaceOverride support for privateRegistry
  apis/kubekey/v1alpha2/cluster_types.go
  docs/config-example.md
  pkg/config/templates/cluster.go
  pkg/images/tasks.go
Labels: approved, lgtm, size/S

#1049 add a GitHub PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, size/M

#1052 fix manifest field typo
  apis/kubekey/v1alpha2/manifest_types.go
  apis/kubekey/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/kubekey.kubesphere.io_manifests.yaml
  pkg/artifact/manifest.go
  pkg/artifact/prepares.go
  pkg/artifact/tasks.go
  pkg/artifact/templates/manifest.go
Labels: approved, kind/cleanup, lgtm, size/M

#1054 fix image name parse err
  pkg/artifact/tasks.go
  pkg/images/images.go
  pkg/images/images_test.go
Labels: approved, kind/bug, lgtm, size/L

#1062 Fix: LocalApiEndpoint's bindPort uses controlPlane's port
  apis/kubekey/v1alpha2/default.go
  pkg/kubernetes/tasks.go
  pkg/kubernetes/templates/v1beta2/kubeadm_config.go
  pkg/loadbalancer/module.go
  pkg/loadbalancer/templates/haproxyConfig.go
Labels: approved, kind/bug, lgtm, size/S

#1065 support k3s artifact
  pkg/binaries/k3s.go
  pkg/binaries/module.go
  pkg/binaries/tasks.go
  pkg/images/images.go
  pkg/pipelines/artifact_export.go
  pkg/pipelines/create_cluster.go
Labels: approved, kind/feature, lgtm, size/L

#1053 add a zh doc introducing the new features of kubekey
  docs/manifest-example.md
  docs/zh/manifest_and_artifact.md
Labels: approved, kind/documentation, lgtm, size/L

#1067 Add features list for KubeKey
  docs/features.md
  docs/registry.md
Labels: approved, kind/documentation, lgtm, size/L

#1068 Add the support of NamespaceOverride for KubeSphere‘s images
  pkg/kubesphere/modules.go
  pkg/kubesphere/tasks.go
  pkg/version/kubesphere/templates/cc_v321.go
Labels: approved, kind/bug, lgtm, size/S

#1074 Fix: CSIStorageCapacity cause the cluster to fail to start normally
  pkg/kubernetes/templates/v1beta2/kubeadm_config.go
Labels: approved, kind/bug, lgtm, size/S

#1070 modify manifest example
  docs/manifest-example.md
Labels: approved, kind/documentation, lgtm, size/M

#1089 update artifact doc
  docs/zh/manifest_and_artifact.md
Labels: approved, kind/documentation, lgtm, size/S

#1092 Fix: a bug that setting up k8s nodes' label doesn't work
  apis/kubekey/v1alpha2/cluster_types.go
  apis/kubekey/v1alpha2/default.go
  docs/manifest-example.md
  pkg/common/kube_runtime.go
  pkg/core/connector/host.go
  pkg/core/connector/interface.go
  pkg/core/task/remote_task.go
  pkg/images/images.go
  pkg/kubernetes/module.go
  pkg/kubernetes/tasks.go
  pkg/pipelines/add_nodes.go
  pkg/pipelines/create_cluster.go
  pkg/pipelines/upgrade_cluster.go
Labels: approved, kind/bug, lgtm, size/L
