Repository kubesphere/kubekey, pull requests merged in 2023-04, with the labels that each got.

#1789 update cni plugin: flannel to v0.21.3
  cmd/kk/apis/kubekey/v1alpha2/default.go
  cmd/kk/pkg/images/tasks.go
  cmd/kk/pkg/plugins/network/modules.go
  cmd/kk/pkg/plugins/network/templates/flannel.go
  pkg/service/operation/file/kubecni.go
Labels: approved, lgtm, size/M

#1791 fix: unable to build centos7 iso
  hack/gen-repository-iso/dockerfile.centos7
Labels: approved, lgtm, size/XS

#1794 update cilium chart to 1.11.7
  cmd/kk/apis/kubekey/v1alpha2/default.go
  cmd/kk/pkg/plugins/network/cilium-1.11.6.tgz
  cmd/kk/pkg/plugins/network/cilium-1.11.7.tgz
  cmd/kk/pkg/plugins/network/tasks.go
Labels: approved, lgtm, size/L

#1779 更新默认Cilium版本以修复一个已知Bug
  cmd/kk/apis/kubekey/v1alpha2/default.go
Labels: approved, kind/bug, lgtm, size/XS

#1808 feat: Add support for building Debian 11 repository iso
  .github/workflows/gen-repository-iso.yaml
  hack/gen-repository-iso/dockerfile.debian11
  hack/gen-repository-iso/packages.yaml
Labels: approved, kind/feature, lgtm, size/M

#1665 fix: remove syncKubeConfigToWorker with strict security concerns
  cmd/kk/pkg/certs/module.go
  cmd/kk/pkg/k3s/module.go
  cmd/kk/pkg/k3s/tasks.go
  cmd/kk/pkg/k8e/module.go
  cmd/kk/pkg/k8e/tasks.go
  cmd/kk/pkg/kubernetes/module.go
  cmd/kk/pkg/kubernetes/tasks.go
Labels: approved, lgtm, size/L
