Repository kubesphere/kubekey, pull requests merged in 2023-10, with the labels that each got.

#2023 feat: move the preInstall step ahead in the add node pipeline
  cmd/kk/pkg/pipelines/add_nodes.go
Labels: approved, kind/feature, lgtm, size/XS

#2026 fix(calico): change default calico arg: IPV4POOL_NAT_OUTGOING to true
  cmd/kk/apis/kubekey/v1alpha2/network_types.go
Labels: approved, kind/bug, lgtm, size/XS

#2032 fix(release): add support v3.4.1 for kubesphere
  cmd/kk/pkg/version/kubesphere/ks_installer.go
  cmd/kk/pkg/version/kubesphere/templates/cc_v341.go
  cmd/kk/pkg/version/kubesphere/version_enum.go
Labels: approved, kind/feature, lgtm, size/L
