Repository kubesphere/kubekey, pull requests merged in 2023-01, with the labels that each got.

#1676 Update manifest_and_artifact.md
  docs/zh/manifest_and_artifact.md
Labels: approved, lgtm, size/XS

#1691 fix: redundant interface names leads to kubeVip pod failure
  cmd/kk/pkg/loadbalancer/tasks.go
Labels: approved, kind/bug, lgtm, size/XS

#1695 docs: instruction on kubeVip module invocation
  cmd/kk/pkg/pipelines/create_cluster.go
Labels: approved, kind/documentation, lgtm, size/XS

#1700 fix: module DeleteVIPModule cause node host interface down
  cmd/kk/pkg/loadbalancer/tasks.go
Labels: approved, lgtm, size/XS

#1703 docs: instruction on avoiding issue 1702
  docs/config-example.md
Labels: approved, kind/documentation, lgtm, size/XS

#1688 feat(kk): allow skipping OS pre-configuration tasks
  cmd/kk/apis/kubekey/v1alpha2/cluster_types.go
  cmd/kk/pkg/bootstrap/os/module.go
  cmd/kk/pkg/phase/os/config.go
  cmd/kk/pkg/pipelines/add_nodes.go
  cmd/kk/pkg/pipelines/create_cluster.go
  cmd/kk/pkg/pipelines/init_registry.go
  docs/config-example.md
Labels: approved, kind/feature, lgtm, size/M

#1704 feat(kk): ks v3.3.1 add support for k8s v1.24
  cmd/kk/pkg/version/kubesphere/ks_installer.go
  cmd/kk/pkg/version/kubesphere/templates/cc_v332.go
  cmd/kk/pkg/version/kubesphere/version_enum.go
Labels: approved, kind/feature, lgtm, size/L
