Repository kubesphere/kubekey, pull requests merged in 2023-03, with the labels that each got.

#1758 fix: compose version error
  version/components.json
Labels: approved, kind/bug, lgtm, size/M

#1759 fix: docker login escape special characters
  cmd/kk/pkg/container/docker.go
Labels: approved, kind/bug, lgtm, size/XS

#1772 chore: rename the task of SyncKubelet
  cmd/kk/pkg/kubernetes/module.go
  cmd/kk/pkg/kubernetes/tasks.go
  cmd/kk/pkg/phase/kubernetes/modules.go
Labels: approved, kind/cleanup, lgtm, size/M

#1782 fix: RefineDockerVersion can not parse zero minor version correctly
  cmd/kk/pkg/bootstrap/confirm/tasks.go
  cmd/kk/pkg/bootstrap/confirm/tasks_test.go
Labels: approved, kind/bug, lgtm, size/M

#1778 add more etcd parameters
  cmd/kk/apis/kubekey/v1alpha2/etcd_types.go
  cmd/kk/pkg/etcd/tasks.go
  cmd/kk/pkg/etcd/templates/etcd_env.go
  docs/config-example.md
Labels: approved, kind/feature, lgtm, size/L
