Repository kubesphere/kubekey, pull requests merged in 2023-05, with the labels that each got.

#1821 chore: fix spelling mistakes of the tasks in coredns module
  cmd/kk/pkg/kubernetes/tasks.go
  cmd/kk/pkg/plugins/dns/module.go
Labels: approved, kind/cleanup, lgtm, size/XS

#1824 fix: local repository is hard-coded as centos7
  .github/workflows/gen-repository-iso.yaml
  cmd/kk/pkg/bootstrap/os/repository/repository_rpm.go
  cmd/kk/pkg/bootstrap/os/tasks.go
  hack/gen-repository-iso/dockerfile.debian9
  hack/gen-repository-iso/packages.yaml
Labels: approved, kind/bug, lgtm, size/M

#1826 fix(cluster): delete cluster confirm skip
  cmd/kk/cmd/delete/delete_cluster.go
  cmd/kk/pkg/bootstrap/confirm/module.go
  cmd/kk/pkg/pipelines/delete_cluster.go
Labels: approved, lgtm, size/XS

#1831 support Configure the default bridge network
  cmd/kk/apis/kubekey/v1alpha2/cluster_types.go
  cmd/kk/pkg/container/module.go
  cmd/kk/pkg/container/templates/docker_config.go
Labels: approved, lgtm, size/M

#1830 feat: supported custom local registry domain
  cmd/kk/pkg/bootstrap/os/templates/init_script.go
  cmd/kk/pkg/bootstrap/registry/certs.go
  cmd/kk/pkg/bootstrap/registry/module.go
  cmd/kk/pkg/bootstrap/registry/tasks.go
  cmd/kk/pkg/k3s/tasks.go
Labels: approved, lgtm, size/M

#1832 fix: Add worker label according to host role
  cmd/kk/pkg/k3s/module.go
  cmd/kk/pkg/k3s/tasks.go
  cmd/kk/pkg/k8e/module.go
  cmd/kk/pkg/k8e/tasks.go
  cmd/kk/pkg/kubernetes/module.go
  cmd/kk/pkg/kubernetes/tasks.go
Labels: approved, kind/bug, lgtm, size/M

#1838 fix: Add multiple etcd nodes failed
  cmd/kk/pkg/etcd/module.go
  cmd/kk/pkg/etcd/tasks.go
Labels: approved, kind/bug, lgtm, size/S

#1840 fix(node): delete node confirm skip
  cmd/kk/cmd/delete/delete_node.go
  cmd/kk/pkg/bootstrap/confirm/module.go
  cmd/kk/pkg/pipelines/delete_node.go
Labels: approved, lgtm, size/S

#1849 add default retry for artifact push image when some image push failed
  cmd/kk/pkg/images/tasks.go
Labels: approved, lgtm, size/S

#1856 support custom argument when start the kubelet
  cmd/kk/pkg/kubernetes/tasks.go
  cmd/kk/pkg/kubernetes/templates/kubelet_env.go
  docs/config-example.md
Labels: approved, kind/feature, lgtm, size/XS

#1852 [#1851] fix hack/version.sh incorrect git version
  hack/version.sh
Labels: approved, kind/bug, lgtm, size/XS

#1850 [doc] Update README to state that Debian 11 Bullseye is supported
  README.md
  README_zh-CN.md
Labels: approved, kind/documentation, lgtm, size/XS

#1857 add clean up the VXLAN interface when delete the cluster
  cmd/kk/pkg/bootstrap/os/tasks.go
Labels: approved, kind/bug, lgtm, size/XS

#1854 [#1853] update the way to get containerd cgroup driver config
  cmd/kk/pkg/kubernetes/templates/v1beta2/kubeadm_config.go
Labels: approved, kind/bug, lgtm, size/XS
