Repository kubesphere/kubekey, pull requests merged in 2023-11, with the labels that each got.

#2037 Add new components version
  version/components.json
Labels: approved, lgtm, size/M

#2036 calculate sha256 file checksum by streaming
  cmd/kk/pkg/files/file.go
Labels: approved, kind/feature, lgtm, size/XS

#2040 fix pull images from harbor pivate registry ImagePullBackOff
  cmd/kk/pkg/container/docker.go
Labels: approved, lgtm, size/XS

#2041 fix: redundant interface for kubevip when add k8s nodes
  cmd/kk/pkg/loadbalancer/tasks.go
Labels: approved, lgtm, size/XS

#2038 fix: backup script doesn't work when set etcd dataDir to another dir except '/var/lib/etcd'
  cmd/kk/pkg/etcd/tasks.go
  cmd/kk/pkg/etcd/templates/backup_script.go
Labels: approved, kind/bug, lgtm, size/XS
