Repository kubesphere/kubekey, pull requests merged in 2023-07, with the labels that each got.

#1896 fix: Modify the imagePullPolicy to make it more practical for offline…
  cmd/kk/pkg/loadbalancer/templates/haproxyManifest.go
  cmd/kk/pkg/loadbalancer/templates/k3sKubevipManifest.go
  cmd/kk/pkg/loadbalancer/templates/kubevipManifest.go
  cmd/kk/pkg/plugins/kata.go
  cmd/kk/pkg/plugins/storage/templates/openebs.go
  cmd/kk/pkg/version/kubesphere/templates/installer.go
Labels: approved, kind/bug, lgtm, size/S

#1898 fix: add secret option to auth-type.
  api/v1beta1/auth_types.go
  api/v1beta1/kkcluster_webhook.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_kkclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_kkclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_kkinstances.yaml
  controllers/kkinstance/kkinstance_controller.go
Labels: approved, kind/bug, lgtm, size/M

#1899 refeact: move autoscaler deployment form template to docs.
  docs/cluster-autoscaler.md
  docs/img/autoscaler-deployment.png
  docs/img/autoscaler-mechanism.png
  docs/machinehealthcheck.md
  templates/cluster-template.yaml
Labels: approved, kind/feature, lgtm, size/L

#1903 fix(typo): containerd
  cmd/kk/apis/kubekey/v1alpha2/default.go
  cmd/kk/cmd/alpha/cri/migrate_cri.go
  cmd/kk/cmd/create/cluster.go
  cmd/kk/cmd/create/phase/images.go
  cmd/kk/pkg/binaries/kubernetes.go
  cmd/kk/pkg/binaries/module.go
  cmd/kk/pkg/common/common.go
  cmd/kk/pkg/config/generate.go
  cmd/kk/pkg/container/containerd.go
  cmd/kk/pkg/container/module.go
  cmd/kk/pkg/kubernetes/templates/v1beta2/kubeadm_config.go
  cmd/kk/pkg/plugins/modules.go
Labels: approved, lgtm, size/M

#1905 docs: add a new example of kk create with specific download cmd
  docs/commands/kk-create-cluster.md
Labels: documentation, approved, lgtm, size/XS

#1902 docs: correct the etcd related number type
  docs/config-example.md
Labels: approved, kind/documentation, lgtm, size/S

#1906 Support custom CALICO_IPV4POOL_NAT_OUTGOING
  cmd/kk/apis/kubekey/v1alpha2/network_types.go
  cmd/kk/pkg/bootstrap/os/templates/init_script.go
  cmd/kk/pkg/kubernetes/kubernetes_status.go
  cmd/kk/pkg/plugins/network/modules.go
  cmd/kk/pkg/plugins/network/templates/calico_v1.16+.go
Labels: approved, kind/feature, lgtm, size/M

#1913 add calicoctl to artifact
  cmd/kk/apis/kubekey/v1alpha2/manifest_types.go
  cmd/kk/pkg/artifact/manifest.go
  cmd/kk/pkg/binaries/kubernetes.go
  docs/manifest-example.md
Labels: approved, kind/cleanup, lgtm, size/S

#1911 fix: fix ubuntu version get
  cmd/kk/pkg/artifact/manifest.go
Labels: approved, kind/bug, lgtm, size/XS

#1907 fix: imagefullName support more than two slash-separated
  cmd/kk/pkg/images/tasks.go
  cmd/kk/pkg/images/utils.go
Labels: approved, kind/bug, lgtm, size/S

#1914 fix: Modify incorrect parameters
  pkg/service/containermanager/templates/config.toml
Labels: approved, kind/bug, lgtm, size/XS

#1917 support to use external dns to resolve control-plane domain
  cmd/kk/apis/kubekey/v1alpha2/cluster_types.go
  cmd/kk/apis/kubekey/v1alpha2/default.go
  docs/config-example.md
Labels: approved, kind/feature, lgtm, size/S

#1916 update default etcd version to v3.5.6
  cmd/kk/apis/kubekey/v1alpha2/default.go
Labels: approved, kind/feature, lgtm, size/XS

#1878 support kk add and delete node with master role
  cmd/kk/pkg/kubernetes/module.go
  cmd/kk/pkg/kubernetes/tasks.go
  cmd/kk/pkg/pipelines/add_nodes.go
Labels: approved, lgtm, size/M

#1901 feat: add an initial stage at the very start cluster creating phase
  cmd/kk/pkg/pipelines/create_cluster.go
  docs/config-example.md
Labels: approved, kind/feature, lgtm, size/XS

#1920 filter etcd node for k8s cluster delete node
  cmd/kk/pkg/kubernetes/tasks.go
Labels: approved, lgtm, size/S

#1928 sync kubesphere v3.4.0 manifests
  cmd/kk/pkg/version/kubesphere/templates/cc_v340.go
  cmd/kk/pkg/version/kubesphere/templates/installer.go
Labels: approved, kind/cleanup, lgtm, size/S

#1934 fix: version check error
  cmd/kk/pkg/bootstrap/os/tasks.go
  cmd/kk/pkg/bootstrap/precheck/tasks.go
  cmd/kk/pkg/kubernetes/kubernetes_status.go
  cmd/kk/pkg/kubernetes/module.go
  cmd/kk/pkg/kubernetes/tasks.go
  cmd/kk/pkg/version/kubernetes/version_enum.go
  cmd/kk/pkg/version/kubesphere/ks_installer.go
Labels: approved, kind/bug, lgtm, size/M
