Repository kubesphere/kubekey, pull requests merged in 2023-09, with the labels that each got.

#1977 update docker version to 24.0.6
  cmd/kk/apis/kubekey/v1alpha2/default.go
  version/components.json
Labels: approved, kind/feature, lgtm, size/S

#1989 feat: add the wait option for the helm addon config
  cmd/kk/apis/kubekey/v1alpha2/addons_types.go
  cmd/kk/pkg/addons/charts.go
Labels: approved, kind/feature, lgtm, size/XS

#1992 support harbor docker-compose ha design and come true
  cmd/kk/apis/kubekey/v1alpha2/cluster_types.go
  cmd/kk/pkg/bootstrap/registry/certs.go
  cmd/kk/pkg/bootstrap/registry/module.go
  cmd/kk/pkg/bootstrap/registry/tasks.go
  cmd/kk/pkg/bootstrap/registry/templates/harbor.go
  docs/harbor-ha.md
  docs/img/harbor_ha01.png
  docs/img/harbor_ha02.png
  docs/img/harbor_keepalived.png
  scripts/harborCreateRegistriesAndReplications.sh
  scripts/harbor_keepalived/check_harbor.sh
  scripts/harbor_keepalived/docker-compose-keepalived-backup.yaml
  scripts/harbor_keepalived/docker-compose-keepalived-master.yaml
  scripts/harbor_keepalived/keepalived-backup.conf
  scripts/harbor_keepalived/keepalived-master.conf
Labels: approved, kind/feature, lgtm, size/L

#2000 Support v1beta3 of kubeadm config
  cmd/kk/apis/kubekey/v1alpha2/cluster_types.go
  cmd/kk/pkg/etcd/templates/etcd_env.go
  cmd/kk/pkg/kubernetes/tasks.go
  cmd/kk/pkg/kubernetes/templates/kubeadm_config.go
  cmd/kk/pkg/pipelines/init_registry.go
  cmd/kk/pkg/version/kubernetes/version_enum.go
Labels: approved, lgtm, size/M

#2001 Support enable calico typha in configuration
  cmd/kk/apis/kubekey/v1alpha2/network_types.go
  cmd/kk/pkg/plugins/network/modules.go
Labels: approved, kind/feature, lgtm, size/S
