Repository kubesphere/kubekey, pull requests merged in 2023-06, with the labels that each got.

#1861 fix: change default kernel paramter.
  cmd/kk/pkg/bootstrap/os/templates/init_script.go
Labels: approved, kind/bug, lgtm, size/M

#1862 perf(image): pull image specify arch
  cmd/kk/pkg/images/images.go
Labels: approved, lgtm, size/XS

#1863 fix(kubeadm): certSANs use quotes, avoid to be parsed as int
  cmd/kk/pkg/kubernetes/templates/v1beta2/kubeadm_config.go
Labels: approved, lgtm, size/XS

#1870 Add capkk documents
  docs/CAPKK-Developer-Guide.md
  docs/zh/CAPKK开发文档.md
Labels: approved, kind/cleanup, lgtm, size/L

#1874 use os or io package to replace ioutil package
  cmd/kk/cmd/plugin/list.go
  cmd/kk/pkg/artifact/manifest.go
  cmd/kk/pkg/artifact/tasks.go
  cmd/kk/pkg/bootstrap/customscripts/tasks.go
  cmd/kk/pkg/client/kubernetes/client.go
  cmd/kk/pkg/common/artifact_runtime.go
  cmd/kk/pkg/core/connector/ssh.go
  cmd/kk/pkg/core/util/file.go
  cmd/kk/pkg/etcd/certs.go
  cmd/kk/pkg/files/file.go
  cmd/kk/pkg/images/tasks.go
  cmd/kk/pkg/k3s/k3s_status.go
  cmd/kk/pkg/k8e/k8e_status.go
  cmd/kk/pkg/kubernetes/kubernetes_status.go
Labels: approved, kind/cleanup, lgtm, size/M

#1877 stop kubelet service first when remove worker node.
  cmd/kk/pkg/bootstrap/os/module.go
  cmd/kk/pkg/bootstrap/os/tasks.go
Labels: approved, kind/bug, lgtm, size/S

#1881 Support for installing calicoctl
  cmd/kk/pkg/binaries/k3s.go
  cmd/kk/pkg/binaries/kubernetes.go
  cmd/kk/pkg/files/file.go
  cmd/kk/pkg/k3s/tasks.go
  cmd/kk/pkg/kubernetes/tasks.go
  hack/sync-components.sh
  version/components.json
Labels: approved, kind/feature, lgtm, size/M

#1882 chore: remove refs to deprecated io/ioutil
  cmd/kk/pkg/registry/docker_registry_config.go
Labels: approved, kind/cleanup, lgtm, size/S

#1886 chore: remove the duplicated switch statements
  cmd/kk/pkg/pipelines/add_nodes.go
  cmd/kk/pkg/pipelines/artifact_export.go
  cmd/kk/pkg/pipelines/create_cluster.go
  cmd/kk/pkg/pipelines/delete_cluster.go
Labels: approved, kind/feature, lgtm, size/S

#1892 feat: Support for enabling kube-apiserver auditing
  cmd/kk/apis/kubekey/v1alpha2/cluster_types.go
  cmd/kk/apis/kubekey/v1alpha2/default.go
  cmd/kk/apis/kubekey/v1alpha2/kubernetes_types.go
  cmd/kk/pkg/bootstrap/os/templates/init_script.go
  cmd/kk/pkg/common/kube_prepare.go
  cmd/kk/pkg/common/loader.go
  cmd/kk/pkg/kubernetes/module.go
  cmd/kk/pkg/kubernetes/tasks.go
  cmd/kk/pkg/kubernetes/templates/audit.go
  cmd/kk/pkg/kubernetes/templates/v1beta2/kubeadm_config.go
  hack/sync-components.sh
Labels: approved, kind/feature, lgtm, size/L

#1872 add finalizer be more robust
  controllers/kkcluster/kkcluster_controller.go
  controllers/kkinstance/kkinstance_controller.go
  controllers/kkmachine/kkmachine_controller.go
Labels: approved, kind/bug, lgtm, size/M

#1894 feat: add autoscaler and machinehealthycheck
  templates/cluster-template.yaml
Labels: approved, kind/feature, lgtm, size/L

#1895 update version to v3.1.0-rc.0
  cmd/kk/pkg/version/kubesphere/ks_installer.go
  cmd/kk/pkg/version/kubesphere/templates/cc_v340.go
  cmd/kk/pkg/version/kubesphere/version_enum.go
Labels: approved, kind/feature, lgtm, size/L
