Repository kubesphere/kubekey, pull requests merged in 2023-08, with the labels that each got.

#1936 calico use node ip for felix route rule source ip
  cmd/kk/pkg/plugins/network/templates/calico_v1.16+.go
  cmd/kk/pkg/plugins/network/templates/calico_v1.16-.go
Labels: approved, lgtm, size/S

#1944 fix: scp permission denied
  cmd/kk/pkg/core/connector/ssh.go
Labels: approved, lgtm, size/XS

#1947 fix bug: when k8s version > v1.25.0 ,use flannel error
  cmd/kk/pkg/plugins/network/modules.go
  cmd/kk/pkg/plugins/network/templates/flannel.go
Labels: approved, lgtm, size/L

#1953 update binary-check message
  cmd/kk/pkg/binaries/kubernetes.go
Labels: approved, lgtm, size/XS

#1959 cmd: fix a few function names on comments
  cmd/kk/pkg/bootstrap/registry/certs.go
Labels: approved, kind/documentation, lgtm, size/XS

#1955 fix: slice overflow panic sometimes during node info parsing
  cmd/kk/pkg/k8e/k8e_status.go
Labels: approved, lgtm, size/S

#1961 Update calico to v3.26.1
  cmd/kk/apis/kubekey/v1alpha2/default.go
  cmd/kk/apis/kubekey/v1alpha2/network_types.go
  cmd/kk/pkg/plugins/network/modules.go
  cmd/kk/pkg/plugins/network/templates/calico_v1.16+.go
  hack/sync-components.sh
  version/components.json
Labels: approved, kind/feature, lgtm, size/XL

#1962 Added new network plugin Hybridnet
  cmd/kk/apis/kubekey/v1alpha2/default.go
  cmd/kk/apis/kubekey/v1alpha2/network_types.go
  cmd/kk/pkg/common/common.go
  cmd/kk/pkg/images/images.go
  cmd/kk/pkg/images/tasks.go
  cmd/kk/pkg/plugins/network/hybridnet-0.6.6.tgz
  cmd/kk/pkg/plugins/network/modules.go
  cmd/kk/pkg/plugins/network/tasks.go
  cmd/kk/pkg/plugins/network/templates/hybridnet.go
  docs/config-example.md
Labels: approved, kind/feature, lgtm, size/L

#1966 Fix hybridnet configuration bug
  cmd/kk/apis/kubekey/v1alpha2/network_types.go
  cmd/kk/pkg/plugins/network/tasks.go
  cmd/kk/pkg/plugins/network/templates/hybridnet.go
Labels: approved, kind/bug, lgtm, size/XS
