Repository kubesphere/kubekey, pull requests merged in 2023-02, with the labels that each got.

#1715 Feat: add cni virtual device deletion
  cmd/kk/pkg/bootstrap/os/tasks.go
  cmd/kk/pkg/k3s/templates/killall_script.go
  docs/commands/kk-delete-cluster.md
  docs/commands/kk-delete-node.md
  docs/network-configurations.md
  pkg/service/bootstrap/bootstrap.go
Labels: approved, kind/feature, lgtm, size/M

#1725 Fix typo and tune description in registry bootstrap module
  cmd/kk/pkg/bootstrap/registry/module.go
Labels: approved, kind/cleanup, lgtm, size/XS

#1732 chore: rename the file of action results for uniform naming
  cmd/kk/pkg/core/ending/action_result.go
Labels: approved, kind/cleanup, lgtm, size/XS

#1740 feat: add v1.25.5 to k8e binary
  cmd/kk/pkg/k8e/tasks.go
  docs/k8e-versions.md
  version/components.json
Labels: approved, kind/feature, lgtm, size/S

#1750 Update components version for export manifest
  version/components.json
Labels: approved, lgtm, size/L
