Repository kubesphere/kubekey, pull requests merged in 2024-10, with the labels that each got.

#2409 feat: add capkk CRDs
  config/capkk/crds/infrastructure.cluster.x-k8s.io_kkclusters.yaml
  config/capkk/crds/infrastructure.cluster.x-k8s.io_kkmachines.yaml
  config/capkk/crds/infrastructure.cluster.x-k8s.io_kkmachinetemplates.yaml
  pkg/apis/capkk/v1beta1/kkcluster_types.go
  pkg/apis/capkk/v1beta1/kkmachine_types.go
  pkg/apis/capkk/v1beta1/kkmachinetemplate_types.go
  pkg/apis/capkk/v1beta1/register.go
  pkg/apis/capkk/v1beta1/zz_generated.deepcopy.go
Labels: approved, kind/design, kind/feature, lgtm, size/XXL, release-note

#2425 Update kkcore crds
  Makefile
  config/kubekey/crds/kubekey.kubesphere.io_pipelinetemplates.yaml
  pkg/apis/core/v1/pipelinetemplate_types.go
  pkg/apis/core/v1/zz_generated.deepcopy.go
Labels: approved, kind/design, lgtm, size/XXL, release-note

#2426 Update capkk crds
  config/capkk/crds/infrastructure.cluster.x-k8s.io_kkclusters.yaml
  pkg/apis/capkk/v1beta1/kkcluster_types.go
  pkg/apis/capkk/v1beta1/zz_generated.deepcopy.go
Labels: approved, kind/design, lgtm, size/XXL, release-note

#2427 fix some bug when using playbook
  pkg/converter/tmpl/template.go
  pkg/executor/pipeline_executor.go
Labels: approved, kind/bug, lgtm, size/XS, release-note

#2436 support use aliyuncs for manifest
  cmd/kk/pkg/artifact/manifest.go
  cmd/kk/pkg/images/images.go
Labels: approved, kind/feature, lgtm, size/S, release-note

#2437 update k8s base url to https://dl.k8s.io
  cmd/kk/pkg/artifact/templates/manifest.go
  cmd/kk/pkg/files/file.go
  feature/builtin/roles/init/init-artifact/defaults/main.yaml
  feature/hack/auto-update-version.py
  feature/hack/fetch-kubernetes-hash.sh
  feature/hack/sync-components.sh
  hack/auto-update-version.py
  hack/fetch-kubernetes-hash.sh
  hack/sync-components.sh
Labels: approved, kind/cleanup, lgtm, size/M, release-note

#2419 Feature capkk controller
  build/kk/Dockerfile
  go.mod
  go.sum
  pkg/apis/capkk/v1beta1/kkcluster_types.go
  pkg/const/scheme.go
  pkg/controllers/kkcluster_controller.go
  pkg/controllers/kkmachine_controller.go
  pkg/controllers/pipeline_controller.go
  pkg/manager/controller_manager.go
  pkg/scope/cluster.go
  pkg/scope/machine.go
Labels: approved, kind/design, kind/feature, lgtm, size/XXL, release-note

#2418 feat: add and update playbooks
  builtin/playbooks/artifact_export.yaml
  builtin/playbooks/artifact_images.yaml
  builtin/playbooks/capkk_binary_install.yaml
  builtin/playbooks/capkk_bootstrap_ready.yaml
  builtin/playbooks/capkk_check_connect.yaml
  builtin/playbooks/capkk_delete_cluster.yaml
  builtin/playbooks/capkk_etcd_binary_install.yaml
  builtin/playbooks/capkk_preparation.yaml
  builtin/playbooks/certs_renew.yaml
  builtin/playbooks/create_cluster.yaml
  builtin/playbooks/hook/post_install.yaml
  builtin/playbooks/hook/pre_install.yaml
  builtin/playbooks/init_os.yaml
  builtin/playbooks/init_registry.yaml
  builtin/playbooks/vars/cluster_requirements.yaml
  builtin/playbooks/vars/init_artifact.yaml
  builtin/roles/capkk/delete/docker/tasks/main.yaml
  builtin/roles/capkk/delete/etcd/tasks/main.yaml
  builtin/roles/capkk/delete/kubernetes/tasks/main.yaml
  builtin/roles/capkk/delete/network/tasks/main.yaml
  builtin/roles/capkk/download/curl/calicoctl/tasks/main.yaml
  builtin/roles/capkk/download/curl/cni/tasks/main.yaml
  builtin/roles/capkk/download/curl/containerd/tasks/main.yaml
  builtin/roles/capkk/download/curl/crictl/tasks/main.yaml
  builtin/roles/capkk/download/curl/cridockerd/tasks/main.yaml
  builtin/roles/capkk/download/curl/docker-compose/tasks/main.yaml
  builtin/roles/capkk/download/curl/docker/tasks/main.yaml
  builtin/roles/capkk/download/curl/etcd/tasks/main.yaml
  builtin/roles/capkk/download/curl/harbor/tasks/main.yaml
  builtin/roles/capkk/download/curl/helm/tasks/main.yaml
  builtin/roles/capkk/download/curl/keepalived/tasks/main.yaml
  builtin/roles/capkk/download/curl/kube/tasks/main.yaml
  builtin/roles/capkk/download/curl/registry/tasks/main.yaml
  builtin/roles/capkk/download/curl/runc/tasks/main.yaml
  builtin/roles/capkk/download/helm/cilium/tasks/main.yaml
  builtin/roles/capkk/download/helm/hybridnet/tasks/main.yaml
  builtin/roles/capkk/download/helm/kubeovn/tasks/main.yaml
  builtin/roles/capkk/download/helm/nfs-provisioner/tasks/main.yaml
  builtin/roles/capkk/install/etcd/defaults/main.yaml
  builtin/roles/capkk/install/etcd/files/backup.service
  builtin/roles/capkk/install/etcd/files/etcd.service
  builtin/roles/capkk/install/etcd/tasks/backup_etcd.yaml
  builtin/roles/capkk/install/etcd/tasks/install_etcd.yaml
  builtin/roles/capkk/install/etcd/tasks/main.yaml
  builtin/roles/capkk/install/etcd/templates/backup.sh
  builtin/roles/capkk/install/etcd/templates/backup.timer
  builtin/roles/capkk/install/etcd/templates/etcd.env
  builtin/roles/init/init-artifact/defaults/main.yaml
  builtin/roles/init/init-artifact/tasks/download_by_curl.yaml
  builtin/roles/init/init-artifact/tasks/download_by_helm.yaml
  builtin/roles/init/init-artifact/tasks/main.yaml
  builtin/roles/init/init-cert/defaults/main.yaml
  builtin/roles/init/init-cert/tasks/main.yaml
  builtin/roles/install/kubernetes/defaults/main.yaml
  builtin/roles/install/kubernetes/templates/kubeadm/kubeadm-init.v1beta2
  builtin/roles/install/kubernetes/templates/kubeadm/kubeadm-init.v1beta3
Labels: approved, kind/design, kind/feature, lgtm, size/XXL, release-note

#2438 disable namespaceOverride on images push
  .github/workflows/kubernetes-auto-support.yaml
  cmd/kk/pkg/images/tasks.go
  hack/sync-components.sh
Labels: approved, kind/cleanup, lgtm, size/XS, release-note
