Repository kubesphere/kubekey, pull requests merged in 2024-08, with the labels that each got.

#2337 support custome etcd args
  cmd/kk/apis/kubekey/v1alpha2/etcd_types.go
  cmd/kk/pkg/etcd/tasks.go
  cmd/kk/pkg/etcd/templates/etcd_env.go
Labels: approved, kind/feature, lgtm, size/XS

#2341 fix: KKZONE=cn is invalid for kubesphere v3.4.1
  cmd/kk/pkg/version/kubesphere/templates/cc_v341.go
Labels: approved, kind/bug, lgtm, size/XS

#2344 fix: inventory_name is localhost, install failed
  builtin/roles/addons/cni/defaults/main.yaml
  builtin/roles/addons/cni/tasks/cilium.yaml
  builtin/roles/addons/cni/tasks/hybridnet.yaml
  builtin/roles/addons/cni/tasks/kubeovn.yaml
  builtin/roles/addons/cni/templates/calico/v3.27.yaml
  builtin/roles/addons/sc/defaults/main.yaml
  builtin/roles/certs/renew-kubernetes/tasks/kube.yaml
  builtin/roles/certs/renew-kubernetes/tasks/main.yaml
  builtin/roles/init/init-artifact/defaults/main.yaml
  builtin/roles/init/init-artifact/tasks/pki.yaml
  builtin/roles/init/init-os/tasks/init_ntpserver.yaml
  builtin/roles/init/init-os/tasks/main.yaml
  builtin/roles/init/init-os/templates/init-os.sh
  builtin/roles/install/certs/defaults/main.yaml
  builtin/roles/install/cri/defaults/main.yaml
  builtin/roles/install/etcd/templates/etcd.env
  builtin/roles/install/image-registry/defaults/main.yaml
  builtin/roles/install/image-registry/tasks/install_registry.yaml
  builtin/roles/install/image-registry/tasks/load_images.yaml
  builtin/roles/install/kubernetes/tasks/init_kubernetes.yaml
  builtin/roles/install/kubernetes/tasks/join_kubernetes.yaml
  builtin/roles/install/kubernetes/tasks/main.yaml
  builtin/roles/install/kubernetes/templates/dns/coredns.deployment
  builtin/roles/install/kubernetes/templates/dns/nodelocaldns.daemonset
  builtin/roles/install/kubernetes/templates/haproxy/haproxy.cfg
  builtin/roles/install/kubernetes/templates/kubeadm/kubeadm-init.v1beta2
  builtin/roles/install/kubernetes/templates/kubeadm/kubeadm-init.v1beta3
  builtin/roles/install/kubernetes/templates/kubeadm/kubelet.env
  builtin/roles/install/kubernetes/templates/kubevip/kubevip.BGP
  builtin/roles/precheck/env_check/tasks/main.yaml
  builtin/roles/precheck/env_check/tasks/os.yaml
  pkg/const/common.go
  pkg/executor/executor.go
  pkg/manager/command_manager.go
  pkg/variable/helper.go
  pkg/variable/helper_test.go
  pkg/variable/internal.go
  pkg/variable/internal_test.go
Labels: approved, kind/bug, lgtm, size/XL

#2345 feat: delete unuse function.
  config/helm/values.yaml
  pkg/converter/internal/functions.go
Labels: approved, kind/cleanup, lgtm, size/M

#2346 feat: modify addons/* setup hosts
  builtin/playbooks/create_cluster.yaml
Labels: approved, lgtm, size/XS

#2349 fix: etc/hosts is incorrect when localhost is not belong cluster.
  builtin/roles/addons/cni/templates/calico/v3.27.yaml
  builtin/roles/init/init-os/templates/init-os.sh
Labels: approved, kind/bug, lgtm, size/M

#2350 fix: does not upgrade Kubernetes to v1.30
  cmd/kk/pkg/version/kubernetes/version_enum.go
Labels: approved, kind/bug, lgtm, size/XS

#2352 fix: does not push image to registry
  cmd/kk/pkg/images/tasks.go
Labels: approved, kind/bug, lgtm, size/XS

#2351 feat: --set contains multi string "=".
  cmd/kk/app/options/option.go
  pkg/apis/kubekey/v1/config_types.go
  pkg/apis/kubekey/v1/config_types_test.go
Labels: approved, kind/feature, lgtm, size/L

#2354 fix: set default work_dir is "./kubekey".
  cmd/kk/app/options/option.go
  pkg/connector/kubernetes_ connector.go
  pkg/const/workdir.go
Labels: approved, kind/feature, lgtm, size/S

#2362 fix: push manifest failed if private registry contian multi-path
  cmd/kk/pkg/images/tasks.go
Labels: approved, kind/bug, lgtm, size/XS

#2368 Fix k8s cni binary template bug
  builtin/roles/addons/cni/defaults/main.yaml
  builtin/roles/addons/cni/tasks/cilium.yaml
Labels: approved, lgtm, size/XS

#2369 feat: support run without vendor.
  .github/workflows/golangci-lint.yml
Labels: approved, lgtm, size/XS

#2372 feat: sync vendor when go.mod changed.
  .github/workflows/sync-vendor.yml
Labels: approved, kind/feature, lgtm, size/M

#2371 Create sync-featrue-code.yaml
  .github/workflows/sync-feature-code.yaml
Labels: approved, kind/feature, lgtm, size/M
