Repository kubesphere/kubekey, pull requests merged in 2024-01, with the labels that each got.

#2070 Replace "which" with "command -v"
  cmd/kk/pkg/container/prepares.go
Labels: approved, lgtm, size/XS

#2013 make docker and containerd no parent-child process relationship
  cmd/kk/pkg/container/docker.go
  cmd/kk/pkg/container/module.go
  cmd/kk/pkg/container/templates/docker_service.go
Labels: approved, lgtm, size/M

#2053 add KKLOCALIP env to specify local ip address for allinone cluster
  cmd/kk/pkg/core/util/ip.go
Labels: approved, lgtm, size/S

#2090 feat: Change the klog print format. Remove custom-defined cache insta…
  config/helm/templates/_helpers.tpl
  go.mod
  go.sum
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/connector/local_connector.go
  pkg/connector/ssh_connector.go
  pkg/const/helper.go
  pkg/controllers/pipeline_controller.go
  pkg/controllers/task_controller.go
  pkg/converter/converter.go
  pkg/converter/tmpl/template.go
  pkg/manager/command_manager.go
  pkg/manager/controller_manager.go
  pkg/manager/manager.go
  pkg/modules/assert.go
  pkg/modules/command.go
  pkg/modules/copy.go
  pkg/modules/debug.go
  pkg/modules/helper.go
  pkg/modules/module.go
  pkg/modules/module_test.go
  pkg/modules/set_fact.go
  pkg/modules/template.go
  pkg/project/project_git.go
  pkg/proxy/runtime_client.go
  pkg/task/controller.go
  pkg/task/helper.go
  pkg/task/internal.go
  pkg/variable/helper.go
  pkg/variable/internal.go
  pkg/variable/source/file.go
  pkg/variable/source/source.go
  pkg/variable/variable.go
Labels: approved, lgtm, size/XL

#2102 update dependency binaries
  cmd/kk/apis/kubekey/v1alpha2/default.go
  cmd/kk/pkg/artifact/templates/manifest.go
  cmd/kk/pkg/images/tasks.go
  hack/sync-components.sh
  version/components.json
Labels: approved, lgtm, size/M

#2105 refine installition of registry logic
  cmd/kk/pkg/bootstrap/registry/certs.go
  cmd/kk/pkg/bootstrap/registry/tasks.go
Labels: approved, kind/cleanup, lgtm, size/S

#2103 Chores: fix typo
  cmd/kk/pkg/etcd/templates/etcd_env.go
  cmd/kk/pkg/kubernetes/tasks.go
Labels: approved, kind/cleanup, lgtm, size/S

#2104 Fix: kubeadm v1beta3 dns config
  cmd/kk/pkg/kubernetes/templates/kubeadm_config.go
Labels: approved, kind/cleanup, lgtm, size/XS
