Repository kubesphere/kubekey, pull requests merged in 2024-02, with the labels that each got.

#2121 feat: add proxy client to transport resource to local.
  cmd/kk/app/options/precheck.go
  cmd/kk/app/options/run.go
  cmd/kk/app/run.go
  go.mod
  go.sum
  hack/update-goimports.sh
  hack/verify-goimports.sh
  pkg/apis/kubekey/v1alpha1/conversion.go
  pkg/apis/kubekey/v1alpha1/task_types.go
  pkg/connector/local_connector.go
  pkg/connector/ssh_connector.go
  pkg/const/context.go
  pkg/const/helper.go
  pkg/const/helper_test.go
  pkg/const/scheme.go
  pkg/const/workdir.go
  pkg/controllers/pipeline_controller.go
  pkg/controllers/task_controller.go
  pkg/converter/converter.go
  pkg/converter/tmpl/template.go
  pkg/manager/command_manager.go
  pkg/manager/controller_manager.go
  pkg/manager/manager.go
  pkg/modules/command.go
  pkg/modules/copy.go
  pkg/modules/debug.go
  pkg/modules/set_fact.go
  pkg/modules/template.go
  pkg/project/project_git.go
  pkg/proxy/admit.go
  pkg/proxy/api_resources.go
  pkg/proxy/internal/file_storage.go
  pkg/proxy/internal/rest_option.go
  pkg/proxy/internal/watcher.go
  pkg/proxy/path_expression.go
  pkg/proxy/resources/config/storage.go
  pkg/proxy/resources/config/strategy.go
  pkg/proxy/resources/inventory/storage.go
  pkg/proxy/resources/inventory/strategy.go
  pkg/proxy/resources/pipeline/storage.go
  pkg/proxy/resources/pipeline/strategy.go
  pkg/proxy/resources/task/storage.go
  pkg/proxy/resources/task/strategy.go
  pkg/proxy/router.go
  pkg/proxy/runtime_client.go
  pkg/proxy/transport.go
  pkg/proxy/transport_test.go
  pkg/task/controller.go
  pkg/task/helper.go
  pkg/task/internal.go
  pkg/variable/helper.go
  pkg/variable/internal.go
  pkg/variable/source/file.go
  pkg/variable/source/source.go
  pkg/variable/variable.go
Labels: approved, kind/feature, lgtm, size/XXL

#2120 support 'cluster-info dump' command
  cmd/kk/apis/kubekey/v1alpha2/multicluster_types.go
  cmd/kk/cmd/clusterinfo/clusterinfo.go
  cmd/kk/cmd/clusterinfo/clusterinfo_dump.go
  cmd/kk/cmd/root.go
  cmd/kk/pkg/clusterinfo/clusterinfo_dump.go
  cmd/kk/pkg/clusterinfo/dump_file.go
  cmd/kk/pkg/clusterinfo/dump_resources.go
  cmd/kk/pkg/clusterinfo/dump_tar.go
  cmd/kk/pkg/utils/client.go
  go.mod
  go.sum
Labels: approved, lgtm, size/XL

#2122 add artifact precheck
  cmd/kk/app/options/run.go
  cmd/kk/app/server.go
  example/pipeline.yaml
  pipeline/Makefile
  pipeline/inventory/config.yaml
  pipeline/inventory/inventory.yaml
  pipeline/playbooks/precheck.yaml
  pipeline/roles/precheck/artifact_check/tasks/main.yaml
  pipeline/roles/precheck/env_check/tasks/main.yaml
  pkg/connector/connector.go
  pkg/const/context.go
  pkg/const/workdir.go
  pkg/converter/tmpl/template.go
  pkg/proxy/internal/file_storage.go
  pkg/proxy/internal/watcher.go
  pkg/task/internal.go
  pkg/variable/helper.go
  pkg/variable/variable.go
Labels: approved, kind/feature, lgtm, size/L

#2119 add flag skip-dependency-check when upgrade cluster
  cmd/kk/cmd/upgrade/upgrade.go
  cmd/kk/pkg/bootstrap/precheck/module.go
  cmd/kk/pkg/common/kube_runtime.go
  cmd/kk/pkg/pipelines/upgrade_cluster.go
Labels: approved, lgtm, size/M

#2111 Support use docker for version >= v1.24.0
  cmd/kk/apis/kubekey/v1alpha2/default.go
  cmd/kk/pkg/binaries/kubernetes.go
  cmd/kk/pkg/bootstrap/confirm/tasks.go
  cmd/kk/pkg/common/common.go
  cmd/kk/pkg/container/docker.go
  cmd/kk/pkg/container/module.go
  cmd/kk/pkg/container/prepares.go
  cmd/kk/pkg/container/templates/cri_dockerd_service.go
  cmd/kk/pkg/files/file.go
  cmd/kk/pkg/kubernetes/tasks.go
  cmd/kk/pkg/version/kubernetes/version_enum.go
  version/components.json
Labels: approved, kind/feature, lgtm, size/L

#2108 keep chrony config file clean and consistency when install and uninstall cluster in the same nodes
  cmd/kk/pkg/bootstrap/os/tasks.go
Labels: approved, lgtm, size/S

#2113 fix : redeployment failure when internal ip is modified
  cmd/kk/pkg/bootstrap/os/tasks.go
Labels: approved, kind/bug, lgtm, size/XS

#2130 Improving code readability
  pkg/apis/kubekey/v1alpha1/conversion.go
  pkg/controllers/pipeline_controller.go
  pkg/controllers/task_controller.go
  pkg/manager/command_manager.go
  pkg/manager/controller_manager.go
  pkg/proxy/resources/task/storage.go
  pkg/proxy/resources/task/strategy.go
  pkg/proxy/transport_test.go
  pkg/task/controller.go
  pkg/task/internal.go
  pkg/variable/variable.go
Labels: approved, kind/design, lgtm, size/XL

#2137 update default docker version to 24.0.9
  cmd/kk/apis/kubekey/v1alpha2/default.go
  version/components.json
Labels: approved, kind/cleanup, lgtm, size/M

#2138 change pause image to 3.9 when kubernetes version >=v1.26
  cmd/kk/pkg/images/tasks.go
Labels: approved, lgtm, size/XS

#2142 add ipv6 support in k8s and calico config,it compatible only ipv4 provide
  cmd/kk/apis/kubekey/v1alpha2/cluster_types.go
  cmd/kk/apis/kubekey/v1alpha2/default.go
  cmd/kk/pkg/bootstrap/os/tasks.go
  cmd/kk/pkg/bootstrap/os/templates/init_script.go
  cmd/kk/pkg/bootstrap/registry/certs.go
  cmd/kk/pkg/core/connector/host.go
  cmd/kk/pkg/core/connector/interface.go
  cmd/kk/pkg/etcd/certs.go
  cmd/kk/pkg/etcd/prepares.go
  cmd/kk/pkg/etcd/tasks.go
  cmd/kk/pkg/k3s/tasks.go
  cmd/kk/pkg/k8e/tasks.go
  cmd/kk/pkg/kubernetes/tasks.go
  cmd/kk/pkg/kubernetes/templates/kubeadm_config.go
  cmd/kk/pkg/kubesphere/tasks.go
  cmd/kk/pkg/plugins/network/modules.go
  cmd/kk/pkg/plugins/network/templates/calico_v1.16+.go
  docs/config-example.md
  pkg/service/bootstrap/bootstrap.go
Labels: approved, kind/feature, lgtm, size/L

#2144 fix #2143: My bin directory was deleted by installContainerdMoudle
  cmd/kk/pkg/container/containerd.go
Labels: approved, kind/bug, lgtm, size/XS

#2148 Support upgrade kubernetes to v1.24+ with Docker runtime
  cmd/kk/apis/kubekey/v1alpha2/default.go
  cmd/kk/apis/kubekey/v1alpha2/kubernetes_types.go
  cmd/kk/pkg/binaries/kubernetes.go
  cmd/kk/pkg/bootstrap/confirm/tasks.go
  cmd/kk/pkg/bootstrap/os/templates/init_script.go
  cmd/kk/pkg/bootstrap/precheck/tasks.go
  cmd/kk/pkg/common/common.go
  cmd/kk/pkg/common/kube_prepare.go
  cmd/kk/pkg/container/docker.go
  cmd/kk/pkg/container/module.go
  cmd/kk/pkg/container/templates/cri_dockerd_service.go
  cmd/kk/pkg/files/file.go
  cmd/kk/pkg/kubernetes/module.go
  cmd/kk/pkg/kubernetes/tasks.go
  cmd/kk/pkg/pipelines/add_nodes.go
  cmd/kk/pkg/pipelines/create_cluster.go
  cmd/kk/pkg/pipelines/upgrade_cluster.go
  cmd/kk/pkg/version/kubernetes/version_enum.go
  hack/sync-components.sh
  version/components.json
Labels: approved, kind/feature, lgtm, size/L
