Repository kubesphere/kubekey, pull requests merged in 2024-04, with the labels that each got.

#2193 Fixes an issue where the DisableDocker action will remove docker-related files, including /usr/bin/containerd, when deleting clusters with the -A flag, which will cause containerd to fail to start when subsequent DaemonReload action are executed.
  cmd/kk/pkg/container/docker.go
Labels: approved, kind/cleanup, lgtm, size/XS

#2194 Fix the issue that the cri-dockerd.sock file is not automatically deleted when stopping the cri-docker service.
  cmd/kk/pkg/container/docker.go
Labels: approved, kind/bug, lgtm, size/XS

#2197 add replicas and nodeselector fields for calico
  cmd/kk/apis/kubekey/v1alpha2/network_types.go
  cmd/kk/pkg/plugins/network/tasks.go
  cmd/kk/pkg/plugins/network/templates/calico.tmpl
Labels: approved, kind/cleanup, lgtm, size/M

#2200 optimize etcd manager logic
  cmd/kk/apis/kubekey/v1alpha2/default.go
  cmd/kk/cmd/upgrade/upgrade.go
  cmd/kk/pkg/common/kube_runtime.go
  cmd/kk/pkg/etcd/module.go
  cmd/kk/pkg/etcd/prepares.go
  cmd/kk/pkg/etcd/tasks.go
  cmd/kk/pkg/pipelines/upgrade_cluster.go
  hack/sync-components.sh
  version/components.json
Labels: approved, kind/cleanup, lgtm, size/L

#2201 update some components version
  cmd/kk/apis/kubekey/v1alpha2/default.go
  cmd/kk/pkg/bootstrap/registry/tasks.go
  cmd/kk/pkg/bootstrap/registry/templates/harbor.go
  cmd/kk/pkg/bootstrap/registry/templates/harbor.yml.tmpl
  cmd/kk/pkg/etcd/module.go
  cmd/kk/pkg/etcd/tasks.go
  cmd/kk/pkg/images/tasks.go
  cmd/kk/pkg/plugins/network/cilium-1.11.7.tgz
  cmd/kk/pkg/plugins/network/cilium-1.15.3.tgz
  cmd/kk/pkg/plugins/network/tasks.go
  hack/sync-components.sh
  version/components.json
Labels: approved, kind/cleanup, lgtm, size/XL

#2204 Support specifying Kubernetes when creating a manifest
  cmd/kk/cmd/create/manifest.go
  cmd/kk/pkg/artifact/manifest.go
  cmd/kk/pkg/artifact/templates/manifest.go
Labels: approved, lgtm, size/L

#2205 Add Flag --skip-remove-artifact to remain kubekey/artifact dir after exporting an artifact
  cmd/kk/cmd/artifact/export.go
  cmd/kk/pkg/artifact/tasks.go
  cmd/kk/pkg/common/artifact_runtime.go
Labels: approved, kind/feature, lgtm, size/M

#2207 update kube-vip version to v0.7.2
  cmd/kk/pkg/binaries/kubernetes.go
  cmd/kk/pkg/images/tasks.go
  cmd/kk/pkg/version/kubernetes/version_enum.go
Labels: approved, kind/cleanup, lgtm, size/S

#2209 fixs error in verifying installation system dependencies when adding …
  cmd/kk/pkg/bootstrap/confirm/tasks.go
Labels: approved, lgtm, size/XS

#2210 update calico version to v3.27.3
  cmd/kk/apis/kubekey/v1alpha2/default.go
  version/components.json
Labels: approved, kind/cleanup, lgtm, size/XS
