Repository kubesphere/kubekey, pull requests merged in 2024-06, with the labels that each got.

#2266 Feature/support image start index when export images
  cmd/kk/cmd/artifact/export.go
  cmd/kk/pkg/common/artifact_runtime.go
  cmd/kk/pkg/images/module.go
  cmd/kk/pkg/images/tasks.go
  cmd/kk/pkg/pipelines/artifact_export.go
Labels: approved, kind/feature, lgtm, size/S

#2267 Feature/cluster addons enhancement
  cmd/kk/apis/kubekey/v1alpha2/addons_types.go
  cmd/kk/cmd/create/cluster.go
  cmd/kk/cmd/create/phase/addons.go
  cmd/kk/cmd/create/phase/phase.go
  cmd/kk/pkg/addons/module.go
  cmd/kk/pkg/addons/tasks.go
  cmd/kk/pkg/common/kube_runtime.go
  cmd/kk/pkg/core/pipeline/pipeline.go
  cmd/kk/pkg/phase/addons/addons.go
  cmd/kk/pkg/pipelines/create_cluster.go
Labels: approved, lgtm, size/L

#2270 feat: add cronJob for pipeline.
  cmd/kk/app/run.go
  config/helm/crds/kubekey.kubesphere.io_pipelines.yaml
  config/helm/templates/role.yaml
  pkg/apis/kubekey/v1/pipeline_types.go
  pkg/apis/kubekey/v1/zz_generated.deepcopy.go
  pkg/controllers/pipeline_controller.go
  pkg/executor/executor.go
  pkg/manager/command_manager.go
Labels: approved, kind/feature, lgtm, size/XXL

#2275 feat: add sonobuoy plugin.
  builtin/fs.go
  builtin/inventory/config.yaml
  builtin/inventory/inventory.yaml
  builtin/roles/install/cri/tasks/install_containerd.yaml
  cmd/kk/app/options/builtin.go
  cmd/kk/app/options/option.go
  example/Makefile
  pkg/apis/kubekey/v1/config_types.go
  pkg/connector/connector.go
  pkg/connector/local_connector.go
  pkg/connector/ssh_connector.go
  pkg/controllers/pipeline_controller.go
  pkg/modules/command.go
  pkg/modules/command_test.go
  pkg/modules/copy.go
  pkg/modules/module.go
  pkg/modules/module_test.go
  pkg/modules/template.go
  pkg/project/builtin.go
  pkg/project/git.go
  pkg/project/local.go
  pkg/project/project.go
  plugins/playbooks/sonobuoy.yaml
  plugins/roles/etcd/backup/defaults/main.yaml
  plugins/roles/etcd/restore/defaults/main.yaml
  plugins/roles/sonobuoy/defaults/main.yaml
  plugins/roles/sonobuoy/tasks/main.yaml
  plugins/roles/sonobuoy/templates/plugins/e2e-ks.yaml
  plugins/roles/sonobuoy/templates/plugins/kube-bench-master.yaml
  plugins/roles/sonobuoy/templates/plugins/kube-bench.yaml
Labels: approved, kind/feature, lgtm, size/XL

#2276 feat: add sonobuoy plugin.
  plugins/roles/sonobuoy/tasks/main.yaml
Labels: approved, kind/bug, lgtm, size/XS

#2277 feat: add kubernetes connector
  pkg/connector/connector.go
  pkg/connector/kubernetes_ connector.go
  pkg/connector/local_connector.go
  pkg/connector/ssh_connector.go
  plugins/playbooks/sonobuoy.yaml
  plugins/roles/sonobuoy/defaults/main.yaml
  plugins/roles/sonobuoy/tasks/main.yaml
  plugins/roles/sonobuoy/templates/plugins/e2e-ks.yaml
  plugins/roles/sonobuoy/templates/plugins/kube-bench-master.yaml
  plugins/roles/sonobuoy/templates/plugins/kube-bench.yaml
Labels: approved, kind/feature, lgtm, size/L

#2278 feat: add pretty log
  cmd/kk/app/options/option.go
  go.mod
  go.sum
  pkg/executor/executor.go
Labels: approved, kind/feature, lgtm, size/M

#2279 feat: change some description in command line.
  cmd/kk/app/options/common.go
Labels: approved, kind/documentation, lgtm, size/XS

#2283 feat: add init command.
  builtin/playbooks/create_cluster.yaml
  builtin/playbooks/hook/post_install.yaml
  builtin/playbooks/hook/pre_install.yaml
  builtin/playbooks/init_os.yaml
  builtin/playbooks/init_registry.yaml
  builtin/playbooks/install.yaml
  cmd/kk/app/init.go
  cmd/kk/app/options/create.go
  cmd/kk/app/options/init.go
  cmd/kk/app/options/pipeline.go
  pkg/project/helper.go
Labels: approved, kind/feature, lgtm, size/L

#2285 feat: add etcd io precheck.
  builtin/roles/install/etcd/defaults/main.yaml
  builtin/roles/install/etcd/files/etcd.service
  builtin/roles/install/etcd/tasks/install_etcd.yaml
  builtin/roles/precheck/env_check/tasks/cri.yaml
  builtin/roles/precheck/env_check/tasks/etcd.yaml
  builtin/roles/precheck/env_check/tasks/main.yaml
  builtin/roles/precheck/env_check/tasks/network.yaml
  builtin/roles/precheck/env_check/tasks/nfs.yaml
  builtin/roles/precheck/env_check/tasks/os.yaml
  pkg/converter/tmpl/filter_extension.go
  pkg/converter/tmpl/filter_extension_test.go
  pkg/converter/tmpl/template_test.go
  pkg/executor/executor.go
Labels: approved, kind/feature, lgtm, size/L

#2287 feat: change etcd_disk_wal_fysnc_duration_seconds to variable.
  builtin/roles/precheck/env_check/defaults/main.yaml
  builtin/roles/precheck/env_check/tasks/etcd.yaml
Labels: approved, kind/feature, lgtm, size/XS

#2288 feat: add cert renew commmand.
  builtin/playbooks/certs_renew.yaml
  builtin/playbooks/create_cluster.yaml
  builtin/roles/certs/renew-etcd/tasks/main.yaml
  builtin/roles/certs/renew-kubernetes/tasks/etcd.yaml
  builtin/roles/certs/renew-kubernetes/tasks/kube.yaml
  builtin/roles/certs/renew-kubernetes/tasks/main.yaml
  builtin/roles/certs/renew-registry/tasks/harbor.yaml
  builtin/roles/certs/renew-registry/tasks/main.yaml
  builtin/roles/certs/renew-registry/tasks/registry.yaml
  builtin/roles/init/init-artifact/tasks/download_by_oras.yaml
  builtin/roles/init/init-artifact/tasks/main.yaml
  builtin/roles/init/init-artifact/tasks/pki.yaml
  builtin/roles/install/image-registry/tasks/install_harbor.yaml
  builtin/roles/install/image-registry/tasks/install_registry.yaml
  builtin/roles/install/image-registry/tasks/main.yaml
  builtin/roles/install/kubernetes/tasks/init_kubernetes.yaml
  builtin/roles/install/kubernetes/tasks/join_kubernetes.yaml
  cmd/kk/app/certs.go
  cmd/kk/app/options/certs.go
Labels: approved, kind/feature, lgtm, size/L

#2289 feat: save default variable to defaults directory
  builtin/roles/certs/renew-kubernetes/defaults/main.yaml
  builtin/roles/certs/renew-kubernetes/tasks/kube.yaml
  builtin/roles/certs/renew-kubernetes/tasks/main.yaml
Labels: approved, kind/feature, lgtm, size/S

#2291 fix: format code.
  Makefile
  builtin/playbooks/certs_renew.yaml
  builtin/playbooks/create_cluster.yaml
  builtin/playbooks/vars/certs_renew.yaml
  builtin/playbooks/vars/create_cluster_kubernetes.yaml
  builtin/roles/addons/cni/defaults/main.yaml
  builtin/roles/addons/cni/tasks/cilium.yaml
  builtin/roles/addons/cni/tasks/hybridnet.yaml
  builtin/roles/addons/cni/tasks/kubeovn.yaml
  builtin/roles/addons/cni/templates/calico/pdg.yaml
  builtin/roles/addons/cni/templates/calico/v3.27.yaml
  builtin/roles/addons/cni/templates/flannel/flannel.yaml
  builtin/roles/addons/cni/templates/multus.deployment
  builtin/roles/certs/renew-kubernetes/defaults/main.yaml
  builtin/roles/certs/renew-kubernetes/tasks/kube.yaml
  builtin/roles/certs/renew-kubernetes/tasks/main.yaml
  builtin/roles/install/certs/templates/renew_script.sh
  builtin/roles/install/cri/defaults/main.yaml
  builtin/roles/install/cri/tasks/install_containerd.yaml
  builtin/roles/install/cri/tasks/install_docker.yaml
  builtin/roles/install/cri/templates/containerd.config
  builtin/roles/install/cri/templates/crictl.config
  builtin/roles/install/cri/templates/docker.config
  builtin/roles/install/kubernetes/defaults/main.yaml
  builtin/roles/install/kubernetes/templates/kubeadm/kubeadm-init.v1beta2
  builtin/roles/install/kubernetes/templates/kubeadm/kubeadm-init.v1beta3
  builtin/roles/install/security/defaults/main.yaml
  go.mod
  pkg/apis/core/v1/base.go
  pkg/apis/core/v1/play.go
  pkg/apis/kubekey/v1/config_types_test.go
  pkg/executor/executor.go
  pkg/project/helper.go
  pkg/project/helper_test.go
  pkg/variable/helper.go
  pkg/variable/helper_test.go
  pkg/variable/variable.go
Labels: approved, kind/feature, lgtm, size/XL

#2292 feat: add check item for kk precheck command
  builtin/playbooks/precheck.yaml
  builtin/roles/init/init-os/tasks/init_repository.yaml
  builtin/roles/precheck/env_check/defaults/main.yaml
  builtin/roles/precheck/env_check/tasks/cri.yaml
  builtin/roles/precheck/env_check/tasks/etcd.yaml
  builtin/roles/precheck/env_check/tasks/main.yaml
  builtin/roles/precheck/env_check/tasks/network.yaml
  builtin/roles/precheck/env_check/tasks/nfs.yaml
  builtin/roles/precheck/env_check/tasks/os.yaml
  cmd/kk/app/options/precheck.go
  cmd/kk/app/pipeline.go
  cmd/kk/app/precheck.go
  cmd/kk/app/run.go
  pkg/manager/controller_manager.go
  pkg/proxy/transport.go
Labels: approved, kind/feature, lgtm, size/M

#2293 fix: add gather_facts interface to connector
  cmd/kk/app/options/run.go
  pkg/connector/connector.go
  pkg/connector/helper.go
  pkg/connector/helper_test.go
  pkg/connector/kubernetes_ connector.go
  pkg/connector/local_connector.go
  pkg/connector/ssh_connector.go
  pkg/const/workdir.go
  pkg/executor/executor.go
  pkg/executor/helper.go
Labels: approved, kind/feature, lgtm, size/L

#2294 fix: add ignore_errors to playbook, role and block
  pkg/apis/core/v1/base.go
  pkg/apis/kubekey/v1alpha1/task_types.go
  pkg/executor/executor.go
Labels: approved, kind/feature, lgtm, size/M

#2295 doc: add docs
  README.md
  builtin/roles/precheck/env_check/tasks/network.yaml
  docs/zh/001-project.md
  docs/zh/002-playbook.md
  docs/zh/003-role.md
  docs/zh/004-task.md
  docs/zh/005-module.md
  docs/zh/101-syntax.md
  docs/zh/201-variable.md
  pkg/apis/core/v1/role.go
Labels: approved, kind/documentation, lgtm, size/L
