Repository kubesphere/kubekey, pull requests merged in 2024-11, with the labels that each got.

#2442 fix: failed to install without image_registry
  builtin/roles/install/cri/defaults/main.yaml
  builtin/roles/install/image-registry/defaults/main.yaml
  go.mod
Labels: approved, kind/bug, size/XS, release-note-none

#2443 Revert "fix: failed to install without image_registry"
  builtin/roles/install/cri/defaults/main.yaml
  builtin/roles/install/image-registry/defaults/main.yaml
  go.mod
Labels: approved, do-not-merge/release-note-label-needed

#2444 fix: failed to install without image_registry
  .github/workflows/sync-vendor.yml
  builtin/roles/install/cri/defaults/main.yaml
  builtin/roles/install/image-registry/defaults/main.yaml
  go.mod
Labels: approved, kind/bug, size/XS, release-note-none

#2445 Revert "fix: failed to install without image_registry"
  .github/workflows/sync-vendor.yml
  builtin/roles/install/cri/defaults/main.yaml
  builtin/roles/install/image-registry/defaults/main.yaml
  go.mod
Labels: approved, do-not-merge/release-note-label-needed

#2446 fix: failed to install without image_registry
  .github/workflows/sync-vendor.yml
  builtin/roles/install/cri/defaults/main.yaml
  builtin/roles/install/image-registry/defaults/main.yaml
  go.mod
Labels: approved, kind/bug, size/S, release-note-none

#2455 refactor: move env to _const.
  pkg/connector/connector.go
  pkg/const/common.go
  pkg/controllers/pipeline_controller.go
Labels: approved, kind/design, lgtm, size/S, release-note

#2457 fix: test kk push image to harbor.
  builtin/playbooks/artifact_images.yaml
  builtin/roles/install/image-registry/defaults/main.yaml
  builtin/roles/install/image-registry/tasks/load_images.yaml
  cmd/controller-manager/app/options/controller_manager.go
  cmd/kk/app/options/option.go
  cmd/kk/app/options/pipeline.go
  pkg/executor/pipeline_executor.go
Labels: approved, lgtm, size/M, release-note-none

#2458 Update config-example.md
  docs/config-example.md
Labels: approved, kind/documentation, lgtm, size/XS, release-note-none

#2407 support changing root dir
  pkg/service/containermanager/templates/config.toml
Labels: approved, lgtm, size/XS, release-note-none
