Repository kubesphere/kubekey, pull requests merged in 2024-09, with the labels that each got.

#2383 update calico to v3.27.4
  cmd/kk/apis/kubekey/v1alpha2/default.go
  hack/sync-components.sh
  version/components.json
Labels: approved, kind/cleanup, lgtm, size/M, release-note

#2385 release 3.1.6
  .github/workflows/sync-feature-code.yaml
  cmd/kk/apis/kubekey/v1alpha2/default.go
  docs/kubernetes-versions.md
  hack/sync-components.sh
  version/components.json
Labels: approved, lgtm, size/L, release-note

#2388 fix: error local router.
  OWNERS
  pkg/proxy/api_resources.go
  pkg/proxy/transport.go
Labels: kind/bug, lgtm, size/M, release-note-none

#2392 fix: Change offline package directory.
  builtin/playbooks/artifact_export.yaml
  builtin/roles/init/init-artifact/tasks/download_by_curl.yaml
  builtin/roles/init/init-artifact/tasks/main.yaml
  builtin/roles/install/kubernetes/tasks/install_binaries.yaml
Labels: approved, kind/bug, lgtm, size/M, do-not-merge/release-note-label-needed

#2393 fix: graceful delete runtime dir.
  pkg/manager/command_manager.go
Labels: approved, kind/bug, lgtm, size/S, release-note-none

#2394 fix: image pull failed
  builtin/playbooks/artifact_export.yaml
  builtin/roles/init/init-artifact/tasks/main.yaml
  pkg/modules/image.go
Labels: approved, lgtm, size/M, release-note-none

#2396 fix: artifact package exclude `certs`
  cmd/kk/app/artifact.go
Labels: approved, kind/bug, lgtm, size/XS, release-note

#2397 remove centos and docker from dependencies repository
  .github/workflows/gen-repository-iso.yaml
  hack/gen-repository-iso/dockerfile.almalinux90
  hack/gen-repository-iso/dockerfile.centos7
  hack/gen-repository-iso/dockerfile.debian10
  hack/gen-repository-iso/dockerfile.debian11
  hack/gen-repository-iso/dockerfile.ubuntu1804
  hack/gen-repository-iso/dockerfile.ubuntu2004
  hack/gen-repository-iso/dockerfile.ubuntu2204
  hack/gen-repository-iso/packages.yaml
Labels: approved, kind/cleanup, lgtm, size/M, release-note

#2398 add `sudo` and SHELL in connector
  pkg/connector/connector.go
  pkg/connector/kubernetes_connector.go
  pkg/connector/local_connector.go
  pkg/connector/local_connector_test.go
  pkg/connector/ssh_connector.go
  pkg/const/common.go
Labels: approved, kind/feature, lgtm, size/L, do-not-merge/release-note-label-needed

#2402 add `sudo_password` to use sudo mod.
  pkg/connector/connector.go
  pkg/connector/kubernetes_connector.go
  pkg/connector/local_connector.go
  pkg/connector/ssh_connector.go
  pkg/const/common.go
  pkg/executor/pipeline_executor.go
Labels: approved, kind/bug, lgtm, size/L, release-note

#2405 only use sudo mode to execute command
  pkg/connector/local_connector.go
  pkg/connector/local_connector_test.go
  pkg/connector/ssh_connector.go
  pkg/const/common.go
Labels: approved, kind/bug, lgtm, size/L, release-note

#2406 fix: ssh formatting exception bug when executing commands
  builtin/roles/init/init-os/tasks/init_repository.yaml
  pkg/connector/local_connector.go
  pkg/connector/ssh_connector.go
Labels: approved, kind/bug, lgtm, size/S, release-note

#2411 fix: symbolic bug in GatherFacts function
  pkg/connector/local_connector.go
  pkg/connector/ssh_connector.go
  pkg/converter/internal/functions.go
  pkg/converter/tmpl/template.go
  pkg/modules/command.go
Labels: approved, kind/bug, lgtm, size/S, release-note

#2414 Modify execute command way, fix bug and optimize execution logic for playbook
  builtin/roles/init/init-artifact/tasks/main.yaml
  pkg/connector/local_connector.go
  pkg/connector/ssh_connector.go
  pkg/project/helper.go
Labels: approved, kind/bug, lgtm, size/S, release-note
