Repository kubesphere/kubekey, pull requests merged in 2024-07, with the labels that each got.

#2300 add action for lint, verify, test
  .github/workflows/golangci-lint.yml
  .golangci.yaml
  Makefile
  cmd/controller-manager/app/options/common.go
  cmd/kk/app/options/common.go
  cmd/kk/app/options/option.go
  cmd/kk/app/pipeline.go
  hack/update-goimports.sh
  hack/verify-dockerfiles.sh
  hack/verify-goimports.sh
  pkg/apis/core/v1/play.go
  pkg/apis/core/v1/playbook.go
  pkg/apis/kubekey/v1alpha1/task_types.go
  pkg/apis/kubekey/v1alpha1/zz_generated.deepcopy.go
  pkg/connector/helper.go
  pkg/const/scheme.go
  pkg/controllers/pipeline_controller.go
  pkg/converter/converter.go
  pkg/converter/tmpl/filter_extension.go
  pkg/converter/tmpl/helper.go
  pkg/executor/executor.go
  pkg/manager/command_manager.go
  pkg/modules/assert.go
  pkg/modules/assert_test.go
  pkg/modules/command.go
  pkg/modules/command_test.go
  pkg/modules/copy.go
  pkg/modules/copy_test.go
  pkg/modules/debug.go
  pkg/modules/debug_test.go
  pkg/modules/fetch.go
  pkg/modules/fetch_test.go
  pkg/modules/gen_cert.go
  pkg/modules/gen_cert_test.go
  pkg/modules/image.go
  pkg/modules/module.go
  pkg/modules/module_test.go
  pkg/modules/set_fact.go
  pkg/modules/template.go
  pkg/modules/template_test.go
  pkg/project/builtin.go
  pkg/project/git.go
  pkg/project/helper.go
  pkg/project/helper_test.go
  pkg/project/project.go
  pkg/proxy/api_resources.go
  pkg/proxy/internal/file_storage.go
  pkg/proxy/internal/rest_option.go
  pkg/proxy/path_expression.go
  pkg/proxy/resources/task/strategy.go
  pkg/proxy/router.go
  pkg/proxy/transport.go
  pkg/variable/helper.go
  pkg/variable/internal.go
Labels: approved, kind/feature, lgtm, size/XXL

#2301 fix: release action error
  .github/workflows/build-multiarch.yaml
  .github/workflows/goreleaser.yml
Labels: approved, kind/feature, size/S

#2302 fix: golangci-lint
  .github/workflows/goreleaser.yml
Labels: approved, size/S

#2303 fix: golangci-lint
  .goreleaser.yml
Labels: approved, kind/bug, size/XS

#2304 add goreleaser
  .github/workflows/golangci-lint.yml
  .gitignore
  .goreleaser.yml
  Makefile
  example/Makefile
  hack/go_install.sh
Labels: approved, kind/feature, lgtm, size/M

#2305 fix: add goreleaser
  .goreleaser.yml
Labels: approved, size/XS

#2306 fix: change image name
  Makefile
  config/helm/values.yaml
Labels: approved, kind/feature, lgtm, size/S

#2307 fix: tag can be inherited
  builtin/roles/init/init-artifact/tasks/pki.yaml
  builtin/roles/precheck/env_check/tasks/cri.yaml
  builtin/roles/precheck/env_check/tasks/etcd.yaml
  builtin/roles/precheck/env_check/tasks/network.yaml
  builtin/roles/precheck/env_check/tasks/nfs.yaml
  builtin/roles/precheck/env_check/tasks/os.yaml
  pkg/apis/core/v1/taggable.go
  pkg/executor/executor.go
Labels: approved, kind/feature, lgtm, size/M

#2308 fix: tag can be inherited
  pkg/apis/core/v1/taggable.go
  pkg/executor/executor.go
Labels: approved, lgtm, size/S

#2298 feature/ support add nodeEtcHosts entry
  cmd/kk/apis/kubekey/v1alpha2/dns_types.go
  cmd/kk/pkg/bootstrap/os/templates/init_script.go
Labels: approved, kind/feature, lgtm, size/S

#2314 refine tasks logic
  cmd/kk/pkg/bootstrap/os/templates/init_script.go
  cmd/kk/pkg/bootstrap/precheck/tasks.go
  cmd/kk/pkg/kubernetes/kubernetes_status.go
Labels: approved, kind/cleanup, lgtm, size/S

#2317 feat: add localhost cluster. it will use default kubeconfig(.kube/con…
  .golangci.yaml
  pkg/connector/connector.go
  pkg/connector/kubernetes_ connector.go
  pkg/converter/tmpl/filter_extension.go
Labels: approved, kind/feature, lgtm, size/S

#2318 feat: set base default dir for kubernetes connector.
  cmd/controller-manager/app/server.go
  cmd/kk/app/artifact.go
  cmd/kk/app/certs.go
  cmd/kk/app/create.go
  cmd/kk/app/init.go
  cmd/kk/app/precheck.go
  cmd/kk/app/run.go
  pkg/connector/kubernetes_ connector.go
  pkg/modules/fetch.go
  pkg/modules/gen_cert_test.go
  pkg/modules/image.go
  pkg/proxy/internal/file_storage.go
  pkg/variable/source/source.go
  plugins/roles/sonobuoy/tasks/main.yaml
Labels: approved, kind/feature, lgtm, size/M

#2319 bug: defaultConfig is not render.
  .goreleaser.yml
  builtin/inventory/config.yaml
  cmd/kk/app/options/builtin.go
Labels: approved, kind/bug, lgtm, size/XS

#2320 fix: var_files defined error
  builtin/playbooks/certs_renew.yaml
  builtin/playbooks/create_cluster.yaml
  pkg/project/helper.go
Labels: approved, kind/bug, lgtm, size/L

#2321 fix: join control-plane error
  builtin/roles/install/kubernetes/defaults/main.yaml
  builtin/roles/install/kubernetes/tasks/init_kubernetes.yaml
  builtin/roles/install/kubernetes/tasks/join_kubernetes.yaml
  builtin/roles/install/kubernetes/tasks/main.yaml
  builtin/roles/install/kubernetes/templates/kubeadm/kubeadm-join.v1beta2
  builtin/roles/install/kubernetes/templates/kubeadm/kubeadm-join.v1beta3
  pkg/apis/kubekey/v1alpha1/task_types.go
  pkg/apis/kubekey/v1alpha1/zz_generated.deepcopy.go
  pkg/executor/executor.go
  pkg/project/helper.go
Labels: approved, kind/bug, lgtm, size/L

#2322 add ssh private key connector method
  pkg/connector/connector.go
  pkg/connector/ssh_connector.go
  pkg/modules/command_test.go
Labels: approved, kind/feature, lgtm, size/L

#2323 fix: coredns configmap is not correct.
  builtin/roles/install/kubernetes/tasks/deploy_cluster_dns.yaml
  builtin/roles/install/kubernetes/templates/dns/coredns.deployment
Labels: approved, lgtm, size/M

#2325 feat: add param to ip_range.
  builtin/roles/install/kubernetes/defaults/main.yaml
  builtin/roles/install/kubernetes/tasks/deploy_cluster_dns.yaml
  builtin/roles/install/kubernetes/templates/dns/nodelocaldns.daemonset
  builtin/roles/install/kubernetes/templates/kubeadm/kubeadm-init.v1beta2
  builtin/roles/install/kubernetes/templates/kubeadm/kubeadm-init.v1beta3
  docs/zh/101-syntax.md
  pkg/converter/tmpl/filter_extension.go
  pkg/converter/tmpl/filter_extension_test.go
Labels: approved, kind/feature, lgtm, size/L

#2327 fix: unescape --set string.
  cmd/kk/app/options/option.go
Labels: approved, kind/bug, lgtm, size/S

#2334 fix: misspelling
  builtin/roles/install/kubernetes/templates/dns/coredns.deployment
Labels: approved, kind/bug, lgtm, size/XS

#2336 support custome etcd port
  cmd/kk/apis/kubekey/v1alpha2/etcd_types.go
  cmd/kk/pkg/etcd/tasks.go
  cmd/kk/pkg/etcd/templates/etcd_env.go
  cmd/kk/pkg/k3s/tasks.go
  cmd/kk/pkg/k8e/tasks.go
  cmd/kk/pkg/kubernetes/tasks.go
Labels: approved, kind/feature, lgtm, size/M
