Repository kubesphere/kubekey, pull requests merged in 2024-05, with the labels that each got.

#2236 fix: close file
  pkg/service/operation/file/template.go
Labels: approved, lgtm, size/XS

#2228 add a flag --with-buildx to install buildx when container runtime is docker
  cmd/kk/apis/kubekey/v1alpha2/default.go
  cmd/kk/cmd/create/cluster.go
  cmd/kk/pkg/binaries/kubernetes.go
  cmd/kk/pkg/common/common.go
  cmd/kk/pkg/common/kube_runtime.go
  cmd/kk/pkg/container/docker.go
  cmd/kk/pkg/container/module.go
  cmd/kk/pkg/container/prepares.go
  cmd/kk/pkg/files/file.go
  version/components.json
Labels: approved, kind/feature, lgtm, size/M

#2220 feat: add CustomScripts.Role property
  cmd/kk/apis/kubekey/v1alpha2/cluster_types.go
  cmd/kk/pkg/bootstrap/customscripts/module.go
Labels: approved, kind/feature, lgtm, size/S

#2227 chore: fix function name in comment
  cmd/kk/cmd/create/phase/init.go
  cmd/kk/cmd/upgrade/phase/images.go
  cmd/kk/cmd/upgrade/phase/nodes.go
Labels: approved, kind/documentation, lgtm, size/XS

#2252 fix: Modify comments
  cmd/kk/app/server.go
  go.mod
  pkg/project/project.go
Labels: approved, lgtm, size/XS

#2257 feat: set CustomScriptTask workdir to remoteTaskHome
  cmd/kk/pkg/bootstrap/customscripts/tasks.go
Labels: approved, kind/bug, lgtm, size/XS

#2256 feat: add phase PostClusterInstall
  cmd/kk/apis/kubekey/v1alpha2/cluster_types.go
  cmd/kk/pkg/pipelines/create_cluster.go
Labels: approved, kind/feature, lgtm, size/S

#2255 feature/support image transport argument to allow export images from and to docker daemon
  cmd/kk/cmd/artifact/export.go
  cmd/kk/cmd/artifact/images/push.go
  cmd/kk/pkg/common/artifact_runtime.go
  cmd/kk/pkg/common/common.go
  cmd/kk/pkg/common/kube_runtime.go
  cmd/kk/pkg/images/module.go
  cmd/kk/pkg/images/prepares.go
  cmd/kk/pkg/images/tasks.go
  cmd/kk/pkg/images/utils.go
  cmd/kk/pkg/pipelines/artifact_export.go
Labels: approved, kind/feature, lgtm, size/L

#2261 feat: add operator
  .dockerignore
  .gitignore
  Dockerfile
  Makefile
  README.md
  build/controller-manager/Dockerfile
  build/kk/Dockerfile
  builtin/roles/init/init-artifact/defaults/main.yaml
  cmd/controller-manager/app/options/common.go
  cmd/controller-manager/app/options/controller_manager.go
  cmd/controller-manager/app/server.go
  cmd/controller-manager/app/version.go
  cmd/kk/app/create.go
  cmd/kk/app/gops.go
  cmd/kk/app/options/common.go
  cmd/kk/app/options/create.go
  cmd/kk/app/options/option.go
  cmd/kk/app/options/pipeline.go
  cmd/kk/app/options/precheck.go
  cmd/kk/app/options/run.go
  cmd/kk/app/pipeline.go
  cmd/kk/app/precheck.go
  cmd/kk/app/root.go
  cmd/kk/app/run.go
  cmd/kk/kubekey.go
  config/helm/Chart.yaml
  config/helm/crds/kubekey.kubesphere.io_configs.yaml
  config/helm/crds/kubekey.kubesphere.io_inventories.yaml
  config/helm/crds/kubekey.kubesphere.io_pipelines.yaml
  config/helm/templates/_helpers.tpl
  config/helm/templates/deployment.yaml
  config/helm/templates/role.yaml
  config/helm/templates/serviceaccount.yaml
  config/helm/values.yaml
  go.mod
  pkg/apis/kubekey/v1/config_types.go
  pkg/apis/kubekey/v1/config_types_test.go
  pkg/apis/kubekey/v1/pipeline_types.go
  pkg/const/helper.go
  pkg/const/scheme.go
  pkg/controllers/pipeline_controller.go
  pkg/converter/converter.go
  pkg/converter/tmpl/filter_extension.go
  pkg/executor/executor.go
  pkg/manager/command_manager.go
  pkg/manager/controller_manager.go
  pkg/manager/manager.go
  pkg/modules/copy.go
  pkg/modules/copy_test.go
  pkg/modules/module.go
  pkg/modules/template.go
  pkg/project/git.go
  pkg/proxy/internal/file_storage.go
  pkg/proxy/transport.go
  pkg/variable/helper.go
  pkg/variable/variable.go
Labels: approved, kind/feature, lgtm, size/XXL

#2254 feature/support checksum of downloaded repository iso file
  cmd/kk/apis/kubekey/v1alpha2/manifest_types.go
  cmd/kk/pkg/artifact/tasks.go
  cmd/kk/pkg/files/file.go
Labels: approved, kind/feature, lgtm, size/M

#2263 feature: add work-dir volume for job pod.
  config/helm/crds/kubekey.kubesphere.io_pipelines.yaml
  pkg/apis/kubekey/v1/pipeline_types.go
  pkg/apis/kubekey/v1/zz_generated.deepcopy.go
  pkg/controllers/pipeline_controller.go
Labels: approved, kind/feature, lgtm, size/XXL

#2259 add check support k8s version
  cmd/kk/pkg/bootstrap/confirm/tasks.go
Labels: approved, kind/feature, kind/flake, lgtm, size/S

#2264 feat: add plugin: backup and restore etcd.
  builtin/roles/init/init-os/tasks/init_repository.yaml
  builtin/roles/install/etcd/defaults/main.yaml
  builtin/roles/install/etcd/templates/etcd.env
  pkg/project/local.go
  plugins/playbooks/backup.yaml
  plugins/playbooks/restore.yaml
  plugins/roles/etcd/backup/defaults/main.yaml
  plugins/roles/etcd/backup/tasks/main.yaml
  plugins/roles/etcd/restore/defaults/main.yaml
  plugins/roles/etcd/restore/tasks/main.yaml
  plugins/roles/kubernetes/start/defaults/main.yaml
  plugins/roles/kubernetes/start/tasks/main.yaml
  plugins/roles/kubernetes/stop/defaults/main.yaml
  plugins/roles/kubernetes/stop/tasks/main.yaml
Labels: approved, kind/feature, lgtm, size/L
