Repository kubesphere/kubekey, pull requests merged in 2024-03, with the labels that each got.

#2158 fix: Optimize logic.
  cmd/kk/app/gops.go
  cmd/kk/app/options/common.go
  cmd/kk/app/options/precheck.go
  cmd/kk/app/options/run.go
  cmd/kk/app/precheck.go
  cmd/kk/app/run.go
  cmd/kk/app/server.go
  pipeline/inventory/inventory.yaml
  pkg/apis/core/v1/block.go
  pkg/apis/core/v1/playbook.go
  pkg/apis/kubekey/v1/config_types.go
  pkg/connector/local_connector.go
  pkg/connector/ssh_connector.go
  pkg/const/context.go
  pkg/controllers/task_controller.go
  pkg/converter/converter.go
  pkg/converter/tmpl/filter_extension.go
  pkg/converter/tmpl/filter_extension_test.go
  pkg/project/project_local.go
  pkg/proxy/internal/watcher.go
  pkg/proxy/transport.go
  pkg/task/internal.go
  pkg/variable/helper.go
  pkg/variable/variable.go
  project/Makefile
  project/fs.go
  project/inventory/config.yaml
  project/inventory/inventory.yaml
  project/playbooks/precheck.yaml
  project/roles/precheck/artifact_check/tasks/main.yaml
  project/roles/precheck/env_check/tasks/main.yaml
Labels: approved, kind/bug, lgtm, size/XXL

#2159 support multi-level image warehouse path push
  cmd/kk/apis/kubekey/v1alpha2/cluster_types.go
  cmd/kk/pkg/bootstrap/os/templates/init_script.go
  cmd/kk/pkg/bootstrap/registry/certs.go
  cmd/kk/pkg/bootstrap/registry/module.go
  cmd/kk/pkg/bootstrap/registry/tasks.go
  cmd/kk/pkg/images/tasks.go
Labels: approved, lgtm, size/M

#2161 Relax artifact strategy
  cmd/kk/pkg/binaries/kubernetes.go
  cmd/kk/pkg/binaries/tasks.go
  cmd/kk/pkg/pipelines/artifact_export.go
Labels: approved, kind/feature, lgtm, size/M

#2164 fix: Adjust the location structure of the playbook to facilitate sequ…
  pkg/const/common.go
  pkg/controllers/task_controller.go
  pkg/converter/converter.go
  pkg/task/internal.go
  pkg/variable/helper.go
  pkg/variable/internal.go
  pkg/variable/variable.go
Labels: approved, kind/bug, lgtm, size/XL

#2169 upgrade sha256 for cri-docker
  version/components.json
Labels: approved, kind/cleanup, lgtm, size/XS

#2172 fix bug: add missing Skip for InstallCriDockerdModule
  cmd/kk/pkg/container/module.go
Labels: approved, lgtm, size/XS

#2157 fix start docker error when init harbor
  cmd/kk/pkg/bootstrap/registry/module.go
Labels: approved, lgtm, size/M

#2166 Add ubuntu2204 cuda for iso repo
  hack/gen-repository-iso/dockerfile.ubuntu2204
  hack/gen-repository-iso/packages.yaml
Labels: approved, lgtm, size/S

#2176 fix bug: not generate crictl config
  cmd/kk/pkg/container/module.go
Labels: approved, lgtm, size/XS

#2179 fix: Relax artifact strategy. add containerManager
  cmd/kk/pkg/binaries/kubernetes.go
Labels: approved, kind/bug, lgtm, size/XS

#2182 add kubekey-system to system workspace
  cmd/kk/pkg/kubernetes/tasks.go
Labels: approved, kind/cleanup, lgtm, size/XS

#2184 Debugged calico.tmpl to support IPv6
  cmd/kk/pkg/plugins/network/templates/calico.tmpl
Labels: approved, kind/bug, lgtm, size/S

#2188 fix config and start containerd on no registry node
  cmd/kk/pkg/bootstrap/registry/module.go
Labels: approved, lgtm, size/XS

#2181 fix bug: upgrade k8s , kubeadm return coredns start version unsupported
  cmd/kk/pkg/kubernetes/module.go
Labels: approved, kind/bug, lgtm, size/XS

#2191 system performance optimization
  cmd/kk/pkg/bootstrap/os/templates/init_script.go
  cmd/kk/pkg/etcd/templates/etcd_service.go
  cmd/kk/pkg/plugins/network/templates/calico.tmpl
Labels: approved, kind/cleanup, lgtm, size/M
