Repository kubesphere/kubekey, pull requests merged in 2025-05, with the labels that each got.

#2552 Fix(connector): gracefully handle LANG environment setup failures-Update ssh.go
  cmd/kk/pkg/core/connector/ssh.go
  cmd/kk/pkg/filesystem/task.go
Labels: approved, lgtm, size/S, release-note

#2555 feat: Parse YAML parameters sequentially.
  .golangci.yaml
  api/project/v1/base.go
  go.mod
  pkg/converter/converter.go
  pkg/converter/converter_test.go
  pkg/executor/executor_test.go
  pkg/executor/task_executor.go
  pkg/executor/task_executor_test.go
  pkg/modules/set_fact.go
  pkg/modules/set_fact_test.go
  pkg/project/project.go
  pkg/project/project_test.go
  pkg/project/testdata/playbook_var1.yaml
  pkg/project/testdata/playbook_var2.yaml
  pkg/project/testdata/playbook_var3.yaml
  pkg/project/testdata/vars/var1.yaml
  pkg/project/testdata/vars/var2.yaml
  pkg/variable/helper.go
  pkg/variable/helper_test.go
  pkg/variable/variable_get.go
  pkg/variable/variable_get_test.go
  pkg/variable/variable_merge.go
  pkg/variable/variable_merge_test.go
  pkg/variable/yaml.go
  pkg/variable/yaml_test.go
Labels: approved, kind/feature, size/XXL, release-note

#2556 feat: delete /var/log/pods/
  .github/workflows/golangci-lint.yaml
  builtin/core/roles/uninstall/kubernetes/tasks/main.yaml
Labels: approved, lgtm, size/XS, release-note

#2557 feat: add command add nodes
  builtin/core/playbooks/add_nodes.yaml
  builtin/core/roles/kubernetes/init-kubernetes/tasks/deploy_cluster_dns.yaml
  cmd/kk/app/builtin.go
  cmd/kk/app/builtin/add.go
  cmd/kk/app/options/builtin/add.go
  pkg/variable/helper.go
Labels: approved, kind/feature, size/L, release-note

#2558 feat: add gather_facts cache
  api/core/v1/config_types.go
  builtin/core/playbooks/hook/pre_install.yaml
  builtin/core/playbooks/precheck.yaml
  cmd/kk/app/options/option.go
  pkg/connector/connector.go
  pkg/connector/gather_facts.go
  pkg/connector/kubernetes_connector.go
  pkg/connector/local_connector.go
  pkg/connector/ssh_connector.go
  pkg/const/common.go
  pkg/const/workdir.go
  pkg/modules/command_test.go
  pkg/variable/helper.go
Labels: approved, lgtm, size/L, release-note

#2560 feat: Support for auto-detecting nodes to add.
  builtin/core/playbooks/add_nodes.yaml
  builtin/core/playbooks/create_cluster.yaml
  builtin/core/roles/precheck/env_check/tasks/etcd.yaml
  builtin/core/roles/precheck/env_check/tasks/network.yaml
  cmd/kk/app/builtin/add.go
  cmd/kk/app/options/builtin/add.go
  cmd/kk/app/options/builtin/builtin.go
  cmd/kk/app/options/builtin/create.go
  cmd/kk/app/options/builtin/delete.go
  pkg/controllers/infrastructure/inventory_hostselector.go
  pkg/variable/helper.go
  pkg/variable/helper_test.go
  pkg/variable/variable.go
  pkg/variable/variable_get.go
  pkg/variable/variable_get_test.go
Labels: approved, kind/feature, lgtm, size/L, release-note

#2561 feat: change builtin defined variable
  builtin/capkk/roles/init/init-os/tasks/init_ntpserver.yaml
  builtin/capkk/roles/init/init-os/tasks/main.yaml
  builtin/capkk/roles/init/init-os/templates/init-os.sh
  builtin/capkk/roles/precheck/env_check/tasks/kubernetes.yaml
  builtin/capkk/roles/precheck/env_check/tasks/network.yaml
  builtin/capkk/roles/precheck/env_check/tasks/os.yaml
  builtin/core/playbooks/add_nodes.yaml
  builtin/core/playbooks/create_cluster.yaml
  builtin/core/playbooks/hook/post_install.yaml
  builtin/core/playbooks/hook/pre_install.yaml
  builtin/core/roles/init/init-cert/tasks/main.yaml
  builtin/core/roles/init/init-os/tasks/init_ntpserver.yaml
  builtin/core/roles/init/init-os/tasks/init_repository.yaml
  builtin/core/roles/init/init-os/tasks/main.yaml
  builtin/core/roles/init/init-os/templates/init-os.sh
  builtin/core/roles/install/cni/defaults/main.yaml
  builtin/core/roles/install/cri/defaults/main.yaml
  builtin/core/roles/install/etcd/templates/etcd.env
  builtin/core/roles/install/image-registry/defaults/main.yaml
  builtin/core/roles/install/image-registry/tasks/install_registry.yaml
  builtin/core/roles/install/security/tasks/main.yaml
  builtin/core/roles/kubernetes/init-kubernetes/tasks/init_kubernetes.yaml
  builtin/core/roles/kubernetes/init-kubernetes/tasks/main.yaml
  builtin/core/roles/kubernetes/init-kubernetes/templates/kubeadm/kubeadm-init.v1beta2
  builtin/core/roles/kubernetes/init-kubernetes/templates/kubeadm/kubeadm-init.v1beta3
  builtin/core/roles/kubernetes/join-kubernetes/tasks/join_kubernetes.yaml
  builtin/core/roles/kubernetes/join-kubernetes/tasks/main.yaml
  builtin/core/roles/kubernetes/join-kubernetes/templates/kubeadm/kubeadm-join.v1beta2
  builtin/core/roles/kubernetes/join-kubernetes/templates/kubeadm/kubeadm-join.v1beta3
  builtin/core/roles/kubernetes/pre-kubernetes/tasks/high-availability/main.yaml
  builtin/core/roles/kubernetes/pre-kubernetes/templates/haproxy/haproxy.cfg
  builtin/core/roles/kubernetes/pre-kubernetes/templates/kubevip/kubevip.BGP
  builtin/core/roles/precheck/env_check/tasks/etcd.yaml
  builtin/core/roles/precheck/env_check/tasks/kubernetes.yaml
  builtin/core/roles/precheck/env_check/tasks/network.yaml
  builtin/core/roles/precheck/env_check/tasks/os.yaml
  pkg/const/common.go
  pkg/const/workdir.go
  pkg/variable/variable_get_test.go
  plugins/roles/etcd/restore/tasks/main.yaml
Labels: approved, lgtm, size/L, release-note

#2562 Update DefaultTimeout to 5h
  cmd/kk/pkg/core/task/const.go
Labels: approved, lgtm, size/XS, release-note

#2563 feat: More detailed init-os rules
  builtin/core/playbooks/add_nodes.yaml
  builtin/core/roles/init/init-os/tasks/init_localdns.yaml
  builtin/core/roles/init/init-os/tasks/main.yaml
  builtin/core/roles/init/init-os/templates/init-os.sh
  plugins/roles/etcd/restore/tasks/main.yaml
Labels: approved, kind/feature, lgtm, size/L, release-note

#2565 feat: add delete nodes command
  builtin/core/playbooks/delete_nodes.yaml
  cmd/kk/app/builtin/add.go
  cmd/kk/app/builtin/delete.go
  cmd/kk/app/options/builtin/delete.go
  pkg/converter/internal/functions.go
  pkg/converter/tmpl/template_test.go
Labels: approved, kind/feature, size/L, release-note

#2567 feat: Configurable local DNS file
  builtin/core/playbooks/delete_cluster.yaml
  builtin/core/playbooks/delete_nodes.yaml
  builtin/core/playbooks/vars/create_cluster_kubernetes.yaml
  builtin/core/playbooks/vars/delete_cluster.yaml
  builtin/core/roles/init/init-os/tasks/init_localdns.yaml
  builtin/core/roles/init/init-os/tasks/main.yaml
  builtin/core/roles/kubernetes/init-kubernetes/tasks/init_kubernetes.yaml
  builtin/core/roles/kubernetes/init-kubernetes/tasks/main.yaml
  builtin/core/roles/kubernetes/join-kubernetes/tasks/join_kubernetes.yaml
  builtin/core/roles/kubernetes/join-kubernetes/tasks/main.yaml
Labels: approved, kind/feature, lgtm, size/M, release-note

#2569 fix: support [a].[b] in set argument
  cmd/kk/app/options/option.go
Labels: approved, kind/bug, lgtm, size/S, release-note

#2571 fix: configurable sandbox image
  builtin/capkk/roles/install/cri/defaults/main.yaml
  builtin/capkk/roles/install/cri/templates/containerd.config
  builtin/capkk/roles/install/cri/templates/cri_docker.service
  builtin/core/defaults/config/v1.23.15.yaml
  builtin/core/roles/install/cri/templates/containerd.config
  builtin/core/roles/install/cri/templates/cri_docker.service
  builtin/core/roles/kubernetes/init-kubernetes/templates/kubeadm/kubeadm-init.v1beta2
  builtin/core/roles/kubernetes/init-kubernetes/templates/kubeadm/kubeadm-init.v1beta3
  builtin/core/roles/kubernetes/join-kubernetes/templates/kubeadm/kubeadm-join.v1beta2
  builtin/core/roles/kubernetes/join-kubernetes/templates/kubeadm/kubeadm-join.v1beta3
Labels: approved, kind/design, lgtm, size/S, release-note

#2572 fix: change kubernetes download url
  builtin/core/roles/init/init-artifact/defaults/main.yaml
Labels: approved, kind/design, lgtm, size/S, release-note

#2573 support prometheus tasks
  api/project/v1/playbook.go
  cmd/kk/app/options/run.go
  docs/zh/modules/prometheus.md
  pkg/connector/connector.go
  pkg/connector/prometheus_connector.go
  pkg/const/common.go
  pkg/executor/task_executor.go
  pkg/modules/debug.go
  pkg/modules/debug_test.go
  pkg/modules/module.go
  pkg/modules/prometheus.go
  pkg/modules/prometheus_test.go
  pkg/variable/helper.go
  pkg/variable/helper_test.go
Labels: approved, kind/feature, lgtm, size/XXL, release-note

#2577 feat: delete --container-manager argument
  cmd/kk/app/options/builtin/add.go
  cmd/kk/app/options/builtin/builtin.go
  cmd/kk/app/options/builtin/create.go
  cmd/kk/app/options/builtin/delete.go
Labels: approved, lgtm, size/M, release-note

#2579 fix: Unexpected error during initial resource listing
  pkg/proxy/internal/file_storage.go
Labels: approved, lgtm, size/XS, release-note

#2584 fix: error cri_socket
  builtin/capkk/roles/install/cri/defaults/main.yaml
  builtin/core/roles/install/cri/defaults/main.yaml
Labels: approved, kind/bug, lgtm, size/XS, release-note-none

#2585 feat: add ssh auth private_key_content
  pkg/connector/ssh_connector.go
  pkg/const/common.go
Labels: approved, kind/feature, lgtm, size/M, release-note

#2586 fix: change failed_when execute time
  pkg/controllers/core/playbook_controller.go
  pkg/controllers/infrastructure/helper.go
  pkg/controllers/infrastructure/inventory_controller.go
  pkg/controllers/infrastructure/kkcluster_controller.go
  pkg/controllers/infrastructure/kkmachine_controller.go
  pkg/controllers/util/patch.go
  pkg/controllers/util/util.go
  pkg/executor/task_executor.go
Labels: approved, kind/bug, lgtm, size/S, release-note

#2587 doc: Add details to the module comments.
  pkg/modules/assert.go
  pkg/modules/command.go
  pkg/modules/copy.go
  pkg/modules/debug.go
  pkg/modules/fetch.go
  pkg/modules/gen_cert.go
  pkg/modules/image.go
  pkg/modules/module.go
  pkg/modules/set_fact.go
  pkg/modules/template.go
Labels: approved, lgtm, size/L, release-note-none

#2588 feat: run gather_facts by module
  pkg/executor/block_executor.go
  pkg/executor/playbook_executor.go
  pkg/executor/task_executor.go
  pkg/modules/setup.go
  pkg/modules/setup_test.go
Labels: approved, kind/feature, lgtm, size/L, release-note

#2591 feat: add web api
  .golangci.yaml
  builtin/core/playbooks/host_check.yaml
  cmd/kk/app/options/option.go
  cmd/kk/app/options/web.go
  cmd/kk/app/root.go
  cmd/kk/app/web.go
  config/file.go
  config/swagger-ui/favicon-16x16.png
  config/swagger-ui/favicon-32x32.png
  config/swagger-ui/index.css
  config/swagger-ui/index.html
  config/swagger-ui/oauth2-redirect.html
  config/swagger-ui/swagger-initializer.js
  config/swagger-ui/swagger-ui-bundle.js
  config/swagger-ui/swagger-ui-bundle.js.map
  config/swagger-ui/swagger-ui-es-bundle-core.js
  config/swagger-ui/swagger-ui-es-bundle-core.js.map
  config/swagger-ui/swagger-ui-es-bundle.js
  config/swagger-ui/swagger-ui-es-bundle.js.map
  config/swagger-ui/swagger-ui-standalone-preset.js
  config/swagger-ui/swagger-ui-standalone-preset.js.map
  config/swagger-ui/swagger-ui.css
  config/swagger-ui/swagger-ui.css.map
  config/swagger-ui/swagger-ui.js
  config/swagger-ui/swagger-ui.js.map
  go.mod
  go.sum
  pkg/const/env.go
  pkg/const/web.go
  pkg/executor/playbook_executor.go
  pkg/manager/command_manager.go
  pkg/manager/manager.go
  pkg/manager/web_manager.go
  pkg/modules/module.go
  pkg/modules/setup.go
  pkg/proxy/resources/task/strategy.go
  pkg/web/api/helper.go
  pkg/web/api/result.go
  pkg/web/handler.go
  pkg/web/openapi.go
  pkg/web/query/field.go
  pkg/web/query/helper.go
  pkg/web/query/types.go
  pkg/web/query/types_test.go
  pkg/web/service.go
Labels: approved, lgtm, size/XXL, release-note

#2593 feat: add schema service
  cmd/kk/app/options/web.go
  cmd/kk/app/web.go
  pkg/manager/manager.go
  pkg/manager/web_manager.go
  pkg/web/openapi.go
  pkg/web/schema.go
Labels: approved, kind/feature, lgtm, size/M, release-note

#2594 feat: add annotations to node
  builtin/core/roles/kubernetes/init-kubernetes/tasks/init_kubernetes.yaml
  builtin/core/roles/kubernetes/join-kubernetes/tasks/join_kubernetes.yaml
  pkg/converter/tmpl/template_test.go
Labels: approved, kind/feature, lgtm, size/S, release-note

#2599 fix: display task progressbar in file.
  .golangci.yaml
  builtin/core/roles/precheck/env_check/tasks/kubernetes.yaml
  pkg/executor/task_executor.go
  pkg/web/handler.go
Labels: approved, kind/bug, lgtm, size/M, release-note
