Repository kubesphere/kubekey, pull requests merged in 2025-09, with the labels that each got.

#2749 bugfix : fix issue 6795
  builtin/core/playbooks/add_nodes.yaml
  builtin/core/playbooks/artifact_export.yaml
  builtin/core/playbooks/artifact_images.yaml
  builtin/core/playbooks/certs_renew.yaml
  builtin/core/playbooks/create_cluster.yaml
  builtin/core/playbooks/delete_cluster.yaml
  builtin/core/playbooks/delete_nodes.yaml
  builtin/core/playbooks/delete_registry.yaml
  builtin/core/playbooks/init_os.yaml
  builtin/core/playbooks/init_registry.yaml
  builtin/core/playbooks/precheck.yaml
  builtin/core/roles/native/root/tasks/main.yaml
Labels: approved, kind/bug, lgtm, size/M, release-note

#2751 bugfix : change openebs version from 4.3 to 4.2
  builtin/core/defaults/config/v1.33.yaml
  builtin/core/roles/defaults/vars/v1.33.yaml
Labels: approved, kind/bug, lgtm, size/S, release-note

#2748 bugfix : fix issue 6764
  builtin/core/roles/native/dns/tasks/main.yaml
Labels: approved, kind/bug, lgtm, size/XS, release-note

#2753 bugfix : fix a bug, openebs can not use leases
  builtin/capkk/roles/install/storageclass/templates/local-volume.yaml
  builtin/core/roles/storage-class/local/templates/local-volume.yaml
Labels: approved, kind/bug, lgtm, size/XS, release-note

#2769 fix: add condition to check download_image in playbooks and tasks
  builtin/core/playbooks/artifact_images.yaml
  builtin/core/roles/download/tasks/images.yaml
  builtin/core/roles/image-registry/tasks/main.yaml
Labels: approved, kind/feature, lgtm, size/XS, release-note

#2770 bugfix: fix some system id error
  builtin/capkk/roles/init/init-os/tasks/init_repository.yaml
  builtin/core/roles/image-registry/docker-registry/tasks/main.yaml
  builtin/core/roles/native/nfs/tasks/main.yaml
  builtin/core/roles/native/repository/tasks/install_package.yaml
  builtin/core/roles/native/repository/tasks/main.yaml
  pkg/converter/tmpl/functions.go
Labels: approved, kind/bug, lgtm, size/M, release-note

#2764 feat : add issue 6787
  pkg/const/common.go
  pkg/web/api/result.go
  pkg/web/handler/resources.go
  pkg/web/service.go
Labels: approved, kind/feature, lgtm, size/L, release-note

#2777 fix: backup not support in apiV3
  builtin/core/roles/etcd/templates/backup.sh
Labels: approved, lgtm, size/XS, release-note

#2778 bugfix: change download data config in some playbooks
  builtin/core/playbooks/artifact_images.yaml
  builtin/core/roles/download/tasks/images.yaml
  builtin/core/roles/image-registry/tasks/main.yaml
Labels: approved, kind/bug, lgtm, size/XS, release-note

#2779 feat: add validation for unique host variables in inventory
  pkg/web/handler/inventory.go
Labels: approved, kind/bug, lgtm, size/M, release-note

#2781 feat: change some image tags
  builtin/core/defaults/config/v1.29.yaml
  builtin/core/roles/defaults/vars/v1.33.yaml
Labels: approved, kind/feature, lgtm, size/S, release-note

#2739 默认etcd版本3.5.22并更新支持k8s1.34.0
  cmd/kk/apis/kubekey/v1alpha2/default.go
  version/components.json
Labels: approved, lgtm, size/S, release-note

#2744 fix: cgroups not supported on darwin
  cmd/kk/pkg/bootstrap/os/tasks.go
  cmd/kk/pkg/utils/cgroups_linux.go
  cmd/kk/pkg/utils/cgroups_unsupported.go
Labels: lgtm, size/S, do-not-merge/release-note-label-needed

#2791 feat: add Chinese README and documentation updates
  README.md
  README_zh-CN.md
  docs/en/001-project.md
  docs/en/002-playbook.md
  docs/en/003-role.md
  docs/en/004-task.md
  docs/en/101-syntax.md
  docs/en/201-variable.md
  docs/en/core/README.md
  docs/en/core/architecture.md
  docs/en/core/image_registry.md
  docs/en/modules/add_hostvars.md
  docs/en/modules/assert.md
  docs/en/modules/command.md
  docs/en/modules/copy.md
  docs/en/modules/debug.md
  docs/en/modules/fetch.md
  docs/en/modules/gen_cert.md
  docs/en/modules/image.md
  docs/en/modules/include_vars.md
  docs/en/modules/prometheus.md
  docs/en/modules/result.md
  docs/en/modules/set_fact.md
  docs/en/modules/setup.md
  docs/en/modules/template.md
  docs/images/kubekey-logo.svg
  docs/zh/core/architecture.md
Labels: approved, kind/documentation, lgtm, size/XXL, release-note
