Repository kubesphere/kubekey, pull requests merged in 2025-04, with the labels that each got.

#2521 fix: Remove the error stack from the intermediate layer.
  cmd/controller-manager/app/options/common.go
  cmd/controller-manager/app/server.go
  cmd/controller-manager/controller_manager.go
  cmd/kk/app/builtin/artifact.go
  cmd/kk/app/builtin/certs.go
  cmd/kk/app/builtin/create.go
  cmd/kk/app/builtin/init.go
  cmd/kk/app/builtin/precheck.go
  cmd/kk/app/options/builtin/artifact.go
  cmd/kk/app/options/builtin/certs.go
  cmd/kk/app/options/builtin/create.go
  cmd/kk/app/options/builtin/init.go
  cmd/kk/app/options/builtin/precheck.go
  cmd/kk/app/options/option.go
  cmd/kk/app/options/other.go
  cmd/kk/app/options/run.go
  cmd/kk/app/playbook.go
  cmd/kk/app/root.go
  cmd/kk/app/run.go
  cmd/kk/kubekey.go
  pkg/connector/connector.go
  pkg/connector/kubernetes_connector.go
  pkg/connector/local_connector.go
  pkg/connector/ssh_connector.go
  pkg/controllers/core/playbook_controller.go
  pkg/controllers/core/playbook_webhook.go
  pkg/controllers/infrastructure/helper.go
  pkg/controllers/infrastructure/inventory_controller.go
  pkg/controllers/infrastructure/kkcluster_controller.go
  pkg/controllers/infrastructure/kkmachine_controller.go
  pkg/converter/tmpl/template.go
  pkg/executor/block_executor.go
  pkg/executor/playbook_executor.go
  pkg/executor/task_executor.go
  pkg/manager/command_manager.go
  pkg/manager/controller_manager.go
  pkg/modules/command_test.go
  pkg/modules/copy.go
  pkg/modules/gen_cert.go
  pkg/modules/image.go
  pkg/modules/module.go
  pkg/modules/template.go
  pkg/project/git.go
  pkg/project/helper.go
  pkg/project/local.go
  pkg/proxy/api_resources.go
  pkg/proxy/internal/file_storage.go
  pkg/proxy/internal/rest_option.go
  pkg/proxy/transport.go
  pkg/variable/helper.go
  pkg/variable/source/file.go
  pkg/variable/variable.go
  pkg/variable/variable_merge.go
Labels: approved, size/XL, release-note

#2522 feat: more type to defined playbook file
  api/core/v1/config_types.go
  api/core/v1alpha1/task_types.go
  builtin/capkk/playbooks/add_node.yaml
  builtin/capkk/playbooks/vars/main.yaml
  builtin/capkk/roles/uninstall/kubernetes/tasks/kubernetes.yaml
  builtin/core/playbooks/certs_renew.yaml
  builtin/core/playbooks/create_cluster.yaml
  builtin/core/playbooks/vars/certs_renew.yaml
  builtin/core/playbooks/vars/cluster_requirements.yaml
  builtin/core/playbooks/vars/create_cluster.yaml
  builtin/core/playbooks/vars/init_artifact.yaml
  builtin/core/roles/install/cri/defaults/main.yaml
  builtin/core/roles/install/kubernetes/defaults/main.yaml
  builtin/core/roles/precheck/env_check/defaults/main.yaml
  builtin/core/roles/precheck/env_check/tasks/etcd.yaml
  cmd/kk/app/options/builtin/create.go
  pkg/const/workdir.go
  pkg/controllers/infrastructure/kkmachine_controller.go
  pkg/converter/converter.go
  pkg/converter/internal/functions.go
  pkg/converter/tmpl/template_test.go
  pkg/executor/block_executor.go
  pkg/executor/playbook_executor.go
  pkg/executor/task_executor.go
  pkg/modules/copy.go
  pkg/modules/template.go
  pkg/project/builtin.go
  pkg/project/git.go
  pkg/project/helper.go
  pkg/project/helper_test.go
  pkg/project/local.go
  pkg/project/path.go
  pkg/project/project.go
  pkg/project/project_test.go
  pkg/project/testdata/playbook1.yaml
  pkg/project/testdata/playbook2.yaml
  pkg/project/testdata/playbook3.yaml
  pkg/project/testdata/playbooks/import_playbook1/import_playbook1.yaml
  pkg/project/testdata/playbooks/playbook1.yaml
  pkg/project/testdata/playbooks/playbook2.yaml
  pkg/project/testdata/playbooks/playbook2.yml
  pkg/project/testdata/playbooks/playbook3.yml
  pkg/project/testdata/playbooks/playbook4.yaml
  pkg/project/testdata/playbooks/playbooks/playbook3.yaml
  pkg/project/testdata/playbooks/roles/role2/tasks/main.yaml
  pkg/project/testdata/roles/role1/tasks/main.yaml
  pkg/project/testdata/roles/role2/tasks/include_task1/include_task1.yaml
  pkg/project/testdata/roles/role2/tasks/include_task1/include_task2.yaml
  pkg/project/testdata/roles/role2/tasks/include_task3.yaml
  pkg/project/testdata/roles/role2/tasks/main.yaml
  pkg/project/testdata/tasks/include_task1.yaml
  pkg/project/testdata/tasks/include_task1/include_task1_2.yaml
  pkg/project/testdata/tasks/include_task1_1.yaml
  pkg/proxy/transport.go
Labels: approved, kind/feature, size/XXL, release-note

#2527 feat: add create config command
  cmd/kk/app/builtin/create.go
  cmd/kk/app/options/builtin/create.go
Labels: approved, kind/feature, lgtm, size/M, release-note

#2528 feat: add delete cluster command
  api/core/v1alpha1/conversion.go
  builtin/core/playbooks/delete_cluster.yaml
  builtin/core/playbooks/vars/delete_cluster.yaml
  builtin/core/roles/install/etcd/tasks/install_etcd.yaml
  builtin/core/roles/install/etcd/tasks/main.yaml
  builtin/core/roles/uninstall/cri/defaults/main.yaml
  builtin/core/roles/uninstall/cri/tasks/main.yaml
  builtin/core/roles/uninstall/cri/tasks/uninstall_containerd.yaml
  builtin/core/roles/uninstall/cri/tasks/uninstall_cridockerd.yaml
  builtin/core/roles/uninstall/cri/tasks/uninstall_docker.yaml
  builtin/core/roles/uninstall/etcd/defaults/main.yaml
  builtin/core/roles/uninstall/etcd/tasks/main.yaml
  builtin/core/roles/uninstall/kubernetes/tasks/main.yaml
  cmd/kk/app/builtin.go
  cmd/kk/app/builtin/delete.go
  cmd/kk/app/options/builtin/delete.go
  pkg/connector/local_connector.go
  pkg/const/scheme.go
  pkg/proxy/resources/task/storage.go
  pkg/proxy/resources/task/strategy.go
Labels: approved, kind/feature, lgtm, size/L, release-note

#2525 fix: Disabling ufw clears ipvs rules, and drop cache affects stability
  cmd/kk/pkg/bootstrap/os/templates/init_script.go
  feature/builtin/roles/init/init-os/templates/init-os.sh
  pkg/service/bootstrap/templates/initOS.sh
Labels: approved, kind/bug, lgtm, size/M, release-note

#2531 feat: Thread-safe reading and writing
  cmd/kk/app/builtin/delete.go
  cmd/kk/app/options/builtin/delete.go
  pkg/converter/tmpl/template_test.go
  pkg/variable/helper.go
  pkg/variable/variable.go
  pkg/variable/variable_get.go
  pkg/variable/variable_merge.go
Labels: approved, size/L, release-note

#2532 feat: add register_type
  api/core/v1alpha1/task_types.go
  api/project/v1/block.go
  builtin/capkk/playbooks/add_node.yaml
  builtin/capkk/roles/install/cni/tasks/calico.yaml
  builtin/capkk/roles/install/cni/tasks/main.yaml
  builtin/capkk/roles/install/kubernetes/tasks/main.yaml
  builtin/core/roles/install/cni/tasks/calico.yaml
  builtin/core/roles/precheck/env_check/tasks/etcd.yaml
  pkg/converter/converter.go
  pkg/executor/task_executor.go
Labels: approved, kind/feature, lgtm, size/M, release-note

#2533 feat: add more ignore_errors when kk delete
  builtin/capkk/roles/uninstall/cri/tasks/uninstall_cridockerd.yaml
  builtin/capkk/roles/uninstall/cri/tasks/uninstall_docker.yaml
  builtin/core/roles/uninstall/cri/tasks/uninstall_cridockerd.yaml
  builtin/core/roles/uninstall/cri/tasks/uninstall_docker.yaml
  builtin/core/roles/uninstall/etcd/tasks/main.yaml
  builtin/core/roles/uninstall/kubernetes/tasks/main.yaml
Labels: approved, kind/feature, lgtm, size/M, release-note

#2534 fix: Fixed kubelet's cgroup configuration always using the default systemd
  cmd/kk/pkg/kubernetes/templates/kubeadm_config.go
Labels: approved, kind/bug, lgtm, size/XS, release-note

#2538 feat: Silence logs
  cmd/kk/app/root.go
  cmd/kk/kubekey.go
Labels: approved, kind/feature, lgtm, size/XS, release-note

#2544 Supported upgrade k8s to v1.33
  cmd/kk/pkg/version/kubernetes/version_enum.go
Labels: approved, kind/cleanup, lgtm, size/XS, release-note
