Repository kubesphere/kubekey, pull requests merged in 2025-01, with the labels that each got.

#2487 support only etcd
  cmd/kk/cmd/create/cluster.go
  cmd/kk/pkg/common/kube_runtime.go
  cmd/kk/pkg/pipelines/create_cluster.go
  cmd/kk/pkg/pipelines/create_k3s_cluster.go
  cmd/kk/pkg/pipelines/create_k8e_cluster.go
Labels: approved, kind/feature, size/L, release-note

#2485 Refactor image pulling logic to support different pull commands, fix crictl pull failure
  cmd/kk/pkg/images/images.go
Labels: approved, lgtm, size/M, do-not-merge/release-note-label-needed

#2489 add set env to en_US.UTF-8. make sure work with en language
  cmd/kk/pkg/core/connector/ssh.go
Labels: approved, lgtm, size/XS, release-note-none

#2488 Refine IPv6 Supported
  cmd/kk/apis/kubekey/v1alpha2/default.go
  cmd/kk/apis/kubekey/v1alpha2/kubernetes_types.go
  cmd/kk/apis/kubekey/v1alpha2/network_types.go
  cmd/kk/pkg/bootstrap/os/module.go
  cmd/kk/pkg/bootstrap/os/templates/init_script.go
  cmd/kk/pkg/kubernetes/tasks.go
  cmd/kk/pkg/kubernetes/templates/kubeadm_config.go
  cmd/kk/pkg/plugins/network/tasks.go
  cmd/kk/pkg/plugins/network/templates/calico.tmpl
  docs/config-example.md
Labels: approved, lgtm, size/L, release-note
