Repository kubesphere/kubekey, pull requests merged in 2025-03, with the labels that each got.

#2503 feat: Adding generic methods to template parsing
  api/project/v1/conditional.go
  api/project/v1/playbook.go
  pkg/const/common.go
  pkg/converter/tmpl/template.go
  pkg/converter/tmpl/template_test.go
  pkg/executor/task_executor.go
  pkg/modules/assert.go
  pkg/modules/assert_test.go
  pkg/modules/copy.go
  pkg/modules/debug.go
  pkg/modules/set_fact.go
  pkg/modules/template.go
  pkg/variable/helper.go
  pkg/variable/helper_test.go
  pkg/variable/variable_get.go
  pkg/variable/variable_merge.go
Labels: approved, kind/feature, size/L, release-note

#2505 fix: error parse when
  api/project/v1/conditional.go
  pkg/converter/tmpl/template.go
Labels: approved, kind/bug, lgtm, size/XS, release-note-none

#2507 fix: command no need to escape
  builtin/capkk/roles/precheck/env_check/tasks/network.yaml
  builtin/capkk/roles/uninstall/kubernetes/tasks/network.yaml
  pkg/connector/connector.go
  pkg/connector/kubernetes_connector.go
  pkg/connector/local_connector.go
  pkg/connector/ssh_connector.go
  pkg/const/common.go
  pkg/controllers/core/pipeline_controller.go
  pkg/executor/task_executor.go
Labels: approved, kind/bug, lgtm, size/L, release-note

#2514 Supported upgrade k8s to v1.32
  .github/workflows/kubernetes-auto-support.yaml
  cmd/kk/pkg/version/kubernetes/version_enum.go
Labels: approved, kind/cleanup, lgtm, size/S, release-note

#2517 feat: change default criSocket as same as dockerd
  config/capkk/release/cluster-template.yaml
  pkg/controllers/infrastructure/inventory_controller.go
Labels: approved, kind/feature, lgtm, size/XS, release-note-none
