Repository kubesphere/kubekey, pull requests merged in 2025-06, with the labels that each got.

#2603 feat: more fast execute task
  pkg/executor/task_executor.go
Labels: approved, kind/feature, lgtm, size/M, release-note

#2607 fix: Modify the node parsing order.
  pkg/project/project.go
  pkg/variable/helper.go
  pkg/variable/yaml.go
Labels: approved, lgtm, size/S, release-note

#2609 feat: Add LimitMEMLOCK=infinity to containerd systemd service
  cmd/kk/pkg/container/templates/containerd_service.go
  pkg/service/containermanager/templates/containerd.service
Labels: approved, lgtm, size/XS, do-not-merge/release-note-label-needed

#2618 feat: add more default kubernetes version
  builtin/capkk/roles/precheck/env_check/defaults/main.yaml
  builtin/core/defaults/config/v1.23.yaml
  builtin/core/defaults/config/v1.24.yaml
  builtin/core/defaults/config/v1.25.yaml
  builtin/core/defaults/config/v1.26.yaml
  builtin/core/defaults/config/v1.27.yaml
  builtin/core/defaults/config/v1.28.yaml
  builtin/core/defaults/config/v1.29.yaml
  builtin/core/defaults/config/v1.30.yaml
  builtin/core/defaults/config/v1.31.yaml
  builtin/core/defaults/config/v1.32.yaml
  builtin/core/defaults/config/v1.33.yaml
  builtin/core/roles/precheck/env_check/defaults/main.yaml
  cmd/kk/app/options/builtin/builtin.go
  cmd/kk/app/options/builtin/create.go
Labels: approved, lgtm, size/XXL, release-note

#2622 fix: more deep clear
  builtin/capkk/roles/uninstall/cri/tasks/uninstall_containerd.yaml
  builtin/capkk/roles/uninstall/cri/tasks/uninstall_cridockerd.yaml
  builtin/capkk/roles/uninstall/cri/tasks/uninstall_docker.yaml
  builtin/capkk/roles/uninstall/kubernetes/tasks/kubernetes.yaml
  builtin/core/roles/uninstall/cri/tasks/uninstall_containerd.yaml
  builtin/core/roles/uninstall/cri/tasks/uninstall_cridockerd.yaml
  builtin/core/roles/uninstall/cri/tasks/uninstall_docker.yaml
  builtin/core/roles/uninstall/etcd/tasks/main.yaml
  builtin/core/roles/uninstall/kubernetes/tasks/kubernetes.yaml
Labels: approved, kind/cleanup, lgtm, size/M, release-note-none

#2623 feat: docs for modules
  docs/zh/001-project.md
  docs/zh/004-task.md
  docs/zh/005-module.md
  docs/zh/101-syntax.md
  docs/zh/201-variable.md
  docs/zh/modules/assert.md
  docs/zh/modules/command.md
  docs/zh/modules/copy.md
  docs/zh/modules/debug.md
  docs/zh/modules/fetch.md
  docs/zh/modules/gen_cert.md
  docs/zh/modules/image.md
  docs/zh/modules/set_fact.md
  docs/zh/modules/setup.md
  docs/zh/modules/template.md
  pkg/modules/image.go
Labels: approved, kind/documentation, lgtm, size/XL, release-note-none

#2626 docs: kubernetes cluster manager docs
  README.md
  docs/images/architecture.excalidraw
  docs/images/architecture.png
  docs/zh/core/README.md
  docs/zh/core/architecture.md
Labels: approved, kind/documentation, lgtm, size/XXL, release-note-none

#2621 fix: umount /run/calico/cgroup first before clear cluster
  cmd/kk/pkg/bootstrap/os/tasks.go
  go.mod
  go.sum
Labels: approved, lgtm, size/M, do-not-merge/release-note-label-needed

#2631 fix: Eliminate duplicate parse logic.
  pkg/executor/task_executor.go
  pkg/modules/assert.go
  pkg/modules/assert_test.go
Labels: approved, kind/cleanup, lgtm, size/S, release-note-none

#2632 fix: clear default inventory and configuration logic.
  cmd/kk/app/options/builtin/add.go
  cmd/kk/app/options/builtin/artifact.go
  cmd/kk/app/options/builtin/builtin.go
  cmd/kk/app/options/builtin/certs.go
  cmd/kk/app/options/builtin/create.go
  cmd/kk/app/options/builtin/delete.go
  cmd/kk/app/options/builtin/init.go
  cmd/kk/app/options/builtin/precheck.go
  cmd/kk/app/options/option.go
Labels: approved, kind/cleanup, lgtm, size/L, release-note-none

#2633 cleanup: move the binary_type fact setting to the pre_install hook
  builtin/capkk/playbooks/add_node.yaml
  builtin/capkk/roles/precheck/env_check/defaults/main.yaml
  builtin/capkk/roles/precheck/env_check/tasks/kubernetes.yaml
  builtin/capkk/roles/precheck/env_check/tasks/os.yaml
  builtin/capkk/roles/uninstall/cri/tasks/main.yaml
  builtin/core/playbooks/add_nodes.yaml
  builtin/core/playbooks/hook/pre_install.yaml
  builtin/core/roles/install/cni/defaults/main.yaml
  builtin/core/roles/install/image-registry/tasks/install_docker.yaml
  builtin/core/roles/kubernetes/pre-kubernetes/tasks/high-availability/kube_vip.yaml
  builtin/core/roles/kubernetes/pre-kubernetes/templates/haproxy/haproxy.cfg
  builtin/core/roles/kubernetes/pre-kubernetes/templates/kubelet/kubelet.env
  builtin/core/roles/precheck/env_check/defaults/main.yaml
  builtin/core/roles/precheck/env_check/tasks/kubernetes.yaml
  builtin/core/roles/precheck/env_check/tasks/network.yaml
  builtin/core/roles/precheck/env_check/tasks/os.yaml
  builtin/core/roles/uninstall/cri/tasks/main.yaml
Labels: approved, kind/cleanup, lgtm, size/L, release-note-none

#2642 fix: delete debug field
  api/core/v1/playbook_types.go
  cmd/kk/app/options/builtin/add.go
  cmd/kk/app/options/builtin/artifact.go
  cmd/kk/app/options/builtin/certs.go
  cmd/kk/app/options/builtin/create.go
  cmd/kk/app/options/builtin/delete.go
  cmd/kk/app/options/builtin/init.go
  cmd/kk/app/options/builtin/precheck.go
  cmd/kk/app/options/option.go
  cmd/kk/app/options/run.go
  pkg/executor/playbook_executor.go
Labels: approved, kind/cleanup, lgtm, size/M, release-note
