Repository kubesphere/kubekey, pull requests merged in 2025-08, with the labels that each got.

#2694 fix: more clear error
  api/core/v1/inventory_types.go
  builtin/core/playbooks/add_nodes.yaml
  builtin/core/playbooks/create_cluster.yaml
  builtin/core/playbooks/delete_cluster.yaml
  builtin/core/playbooks/delete_nodes.yaml
  builtin/core/playbooks/delete_registry.yaml
  builtin/core/playbooks/init_registry.yaml
  builtin/core/playbooks/vars/common.yaml
  builtin/core/playbooks/vars/create_cluster.yaml
  builtin/core/playbooks/vars/create_cluster_kubernetes.yaml
  builtin/core/playbooks/vars/delete_cluster.yaml
  builtin/core/playbooks/vars/kubernetes.yaml
  builtin/core/roles/init/init-os/tasks/main.yaml
  config/capkk/crds/kubekey.kubesphere.io_inventories.yaml
  config/kubekey/crds/kubekey.kubesphere.io_inventories.yaml
  pkg/project/builtin.go
  pkg/project/git.go
  pkg/project/local.go
  pkg/project/project.go
  pkg/proxy/internal/file_storage.go
  pkg/web/api/result.go
  pkg/web/handler/inventory.go
  pkg/web/handler/playbook.go
  pkg/web/handler/resources.go
Labels: approved, lgtm, size/XL, release-note-none

#2705 feature: add pull image platform
  docs/zh/modules/image.md
  pkg/modules/image.go
Labels: approved, kind/feature, lgtm, size/M, release-note-none

#2714 feature: support same key in different file
  api/project/v1/base.go
  pkg/executor/task_executor.go
  pkg/modules/set_fact.go
  pkg/project/project.go
  pkg/project/project_test.go
  pkg/variable/helper.go
  pkg/variable/variable_merge.go
  pkg/variable/variable_merge_test.go
Labels: approved, kind/feature, size/L, release-note

#2723 fix: error format for kubernetes version file
  builtin/core/roles/defaults/vars/v1.23.yaml
  builtin/core/roles/defaults/vars/v1.24.yaml
  builtin/core/roles/defaults/vars/v1.25.yaml
  builtin/core/roles/defaults/vars/v1.26.yaml
  builtin/core/roles/defaults/vars/v1.27.yaml
  builtin/core/roles/defaults/vars/v1.28.yaml
  builtin/core/roles/defaults/vars/v1.29.yaml
  builtin/core/roles/defaults/vars/v1.30.yaml
  builtin/core/roles/defaults/vars/v1.31.yaml
  builtin/core/roles/defaults/vars/v1.32.yaml
  builtin/core/roles/defaults/vars/v1.33.yaml
Labels: approved, kind/bug, lgtm, size/XXL, release-note-none

#2727 bugfix: fix harbor verson config path
  builtin/core/roles/image-registry/docker-compose/tasks/main.yaml
  builtin/core/roles/image-registry/harbor/tasks/main.yaml
  builtin/core/roles/image-registry/harbor/templates/harbor.service
  builtin/core/roles/image-registry/harbor/templates/harbor.yml
  builtin/core/roles/image-registry/tasks/main.yaml
Labels: approved, kind/bug, lgtm, size/S, release-note

#2737 feat: move web const to web api
  pkg/const/web.go
  pkg/web/api/result.go
  pkg/web/service.go
Labels: approved, kind/feature, lgtm, size/L, release-note
