Repository kubesphere/kubekey, pull requests merged in 2025-07, with the labels that each got.

#2620 fix: replace 'which' with 'command -v'
  cmd/kk/pkg/bootstrap/precheck/tasks.go
Labels: approved, lgtm, size/XS

#2649 fix: add index to groups
  .golangci.yaml
  builtin/core/playbooks/host_check.yaml
  pkg/const/env.go
  pkg/executor/playbook_executor.go
  pkg/modules/command.go
  pkg/modules/result.go
  pkg/variable/helper.go
  pkg/variable/variable.go
  pkg/variable/variable_get.go
  pkg/variable/variable_merge.go
  pkg/variable/variable_merge_test.go
  pkg/web/api/result.go
  pkg/web/corev1.go
  pkg/web/resources.go
Labels: approved, lgtm, size/L, release-note-none

#2652 feat: add role dependency
  api/project/v1/playbook_test.go
  api/project/v1/role.go
  pkg/const/workdir.go
  pkg/executor/block_executor.go
  pkg/executor/playbook_executor.go
  pkg/executor/role_executor.go
  pkg/project/path.go
  pkg/project/project.go
  pkg/project/project_test.go
  pkg/project/testdata/playbooks/playbook5.yaml
  pkg/project/testdata/roles/role3/meta/main.yaml
Labels: approved, kind/feature, lgtm, size/L, release-note

#2654 fix: playbook delete is error
  api/core/v1/conversion.go
  api/core/v1alpha1/conversion.go
  pkg/const/scheme.go
  pkg/executor/playbook_executor.go
  pkg/proxy/internal/watcher.go
  pkg/web/api/result.go
  pkg/web/corev1.go
  pkg/web/resources.go
Labels: approved, kind/bug, lgtm, size/L, release-note-none

#2656 fix: add sshPort of listIP result
  pkg/web/api/result.go
  pkg/web/resources.go
Labels: approved, lgtm, size/XS, release-note-none

#2660 fix: error update playbook
  pkg/executor/playbook_executor.go
Labels: approved, kind/bug, lgtm, size/XS, release-note-none

#2664 feat: rescue success continue execute playbook
  pkg/executor/block_executor.go
Labels: approved, kind/bug, lgtm, size/S, release-note

#2665 feat: make the nodelocaldns bind IP configurable.
  builtin/core/playbooks/vars/create_cluster_kubernetes.yaml
  builtin/core/roles/kubernetes/init-kubernetes/templates/dns/nodelocaldns.yaml
  builtin/core/roles/kubernetes/init-kubernetes/templates/kubeadm/kubeadm-init.v1beta2
  builtin/core/roles/kubernetes/init-kubernetes/templates/kubeadm/kubeadm-init.v1beta3
  pkg/executor/block_executor.go
Labels: approved, kind/feature, lgtm, size/M, release-note-none

#2666 feat: test variable store in memory
  pkg/const/test.go
  pkg/executor/executor_test.go
  pkg/executor/task_executor_test.go
  pkg/modules/add_hostvars_test.go
  pkg/modules/assert_test.go
  pkg/modules/command_test.go
  pkg/modules/copy_test.go
  pkg/modules/debug_test.go
  pkg/modules/fetch_test.go
  pkg/modules/gen_cert_test.go
  pkg/modules/image_test.go
  pkg/modules/module_test.go
  pkg/modules/prometheus_test.go
  pkg/modules/result_test.go
  pkg/modules/set_fact_test.go
  pkg/modules/setup_test.go
  pkg/modules/template_test.go
  pkg/variable/variable_merge.go
Labels: approved, kind/feature, size/L, release-note-none

#2663 feat: Add support for building Debian 12 Bookworm repository iso
  .github/workflows/gen-repository-iso.yaml
  README.md
  README_zh-CN.md
  hack/gen-repository-iso/dockerfile.debian12
  hack/gen-repository-iso/packages.yaml
Labels: kind/feature, size/M, do-not-merge/release-note-label-needed

#2668 feat: add webUI route
  config/file.go
  config/web/index.html
  pkg/const/web.go
  pkg/manager/web_manager.go
  pkg/modules/gen_cert.go
  pkg/web/corev1.go
  pkg/web/openapi.go
  pkg/web/resources.go
Labels: approved, kind/feature, lgtm, size/L, release-note

#2670 fix: add ui-path for kk web
  cmd/kk/app/options/web.go
  cmd/kk/app/web.go
  config/file.go
  config/web/index.html
  pkg/manager/manager.go
  pkg/manager/web_manager.go
  pkg/web/api/result.go
  pkg/web/openapi.go
  pkg/web/resources.go
Labels: approved, kind/feature, lgtm, size/L, release-note

#2675 feat: enhance connector interface and implementations
  pkg/connector/connector.go
  pkg/connector/kubernetes_connector.go
  pkg/connector/local_connector.go
  pkg/connector/prometheus_connector.go
  pkg/connector/ssh_connector.go
  pkg/const/ip.go
  pkg/executor/task_executor.go
  pkg/modules/command.go
  pkg/modules/module_test.go
  pkg/modules/prometheus.go
  pkg/web/api/result.go
  pkg/web/corev1.go
  pkg/web/handler/executor.go
  pkg/web/handler/inventory.go
  pkg/web/handler/playbook.go
  pkg/web/handler/resources.go
  pkg/web/openapi.go
  pkg/web/service.go
Labels: approved, kind/feature, lgtm, size/XXL, release-note-none
